<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Extrode.JauntyQ.Fuzz</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Extrode.JauntyQ.SqlParser\Extrode.JauntyQ.SqlParser.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SharpFuzz" Version="2.3.0" />
  </ItemGroup>
</Project>
