using JauntyQ.Schema;
using JauntyQ.SqlParser.IR;

namespace JauntyQ.Generator;
public static partial class CodeEmitter
{
    public static string EmitEntityCore(string entityName)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly System.Data.Common.DbConnection _conn;");
        sb.AppendLine("        private readonly JauntyDb? _db;");
        sb.AppendLine();
        sb.AppendLine($"        internal {entityName}(System.Data.Common.DbConnection conn) => _conn = conn;");
        sb.AppendLine();
        sb.AppendLine($"        internal {entityName}(JauntyDb db)");
        sb.AppendLine("        {");
        sb.AppendLine("            _db = db;");
        sb.AppendLine("            _conn = db.Connection;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitJauntyDb(
        System.Collections.Generic.IEnumerable<string> entityNames,
        DatabaseSchema? schema = null)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public class JauntyDb");
        sb.AppendLine("    {");
        sb.AppendLine("""
        private readonly System.Data.Common.DbConnection _conn;
        private System.Data.Common.DbTransaction? _tx;
        private bool _txOpenedConnection;

        public JauntyDb(System.Data.Common.DbConnection conn) => _conn = conn;

        internal System.Data.Common.DbConnection Connection => _conn;
        internal System.Data.Common.DbTransaction? CurrentTransaction => _tx;

        /// <summary>
        /// Opens the connection if needed and starts a transaction. Every
        /// db.* call automatically enlists until Commit/Rollback/Dispose;
        /// if the connection was opened here it is closed when the
        /// transaction ends. Dispose without Commit rolls back.
        /// </summary>
        public Transaction BeginTransaction()
        {
            if (_tx != null)
                throw new System.InvalidOperationException("A JauntyDb transaction is already active.");
            bool openedNow = _conn.State != System.Data.ConnectionState.Open;
            if (openedNow) _conn.Open();
            try
            {
                _tx = _conn.BeginTransaction();
            }
            catch
            {
                // A failed BeginTransaction must not leave a dangling "we opened
                // it" claim behind: if we opened the connection for this attempt,
                // close it again so a retry on this instance starts from a clean
                // slate instead of silently losing track of who opened it.
                if (openedNow) _conn.Close();
                throw;
            }
            _txOpenedConnection = openedNow;
            return new Transaction(this, _tx);
        }

        public async System.Threading.Tasks.Task<Transaction> BeginTransactionAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            if (_tx != null)
                throw new System.InvalidOperationException("A JauntyDb transaction is already active.");
            bool openedNow = _conn.State != System.Data.ConnectionState.Open;
            if (openedNow) await _conn.OpenAsync(cancellationToken).ConfigureAwait(false);
            try
            {
                _tx = await _conn.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
            }
            catch
            {
                if (openedNow) _conn.Close();
                throw;
            }
            _txOpenedConnection = openedNow;
            return new Transaction(this, _tx);
        }

        private void EndTransaction()
        {
            _tx = null;
            if (_txOpenedConnection && _conn.State != System.Data.ConnectionState.Closed)
                _conn.Close();
            _txOpenedConnection = false;
        }

        public sealed class Transaction : System.IDisposable
        {
            private readonly JauntyDb _db;
            private System.Data.Common.DbTransaction? _inner;

            internal Transaction(JauntyDb db, System.Data.Common.DbTransaction inner)
            {
                _db = db;
                _inner = inner;
            }

            public void Commit()
            {
                if (_inner == null)
                    throw new System.InvalidOperationException("Transaction already completed.");
                _inner.Commit();
                End();
            }

            public void Rollback()
            {
                if (_inner == null)
                    throw new System.InvalidOperationException("Transaction already completed.");
                _inner.Rollback();
                End();
            }

            public void Dispose()
            {
                if (_inner == null) return;
                End(); // disposing an uncommitted DbTransaction rolls back
            }

            private void End()
            {
                _inner!.Dispose();
                _inner = null;
                _db.EndTransaction();
            }
        }
""");

        foreach (var entity in entityNames)
        {
            string fieldName = "_" + ToCamelCase(entity);
            sb.AppendLine();
            sb.AppendLine($"        private {entity}? {fieldName};");
            sb.AppendLine($"        public {entity} {entity} => {fieldName} ??= new {entity}(this);");
        }

        EmitSequenceAccessor(sb, schema);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the lazily-constructed <c>db.Sequences</c> accessor plus its nested
    /// <c>SequenceAccessor</c> class, one <c>Next{Name}()</c>/<c>Next{Name}Async()</c>
    /// method per database sequence. Only SQL Server and PostgreSQL populate
    /// <see cref="DatabaseSchema.Sequences"/>, so this is a no-op for other
    /// dialects (and when the snapshot has no sequences at all). Each sequence
    /// name flows into both a C# method name and an embedded SQL literal, so it
    /// crosses the same trust boundary as table/column names: invalid raw
    /// identifiers are skipped and the SQL side is emitted through
    /// <see cref="IdentifierGuard.ToStringLiteral"/>.
    /// </summary>
    private static void EmitSequenceAccessor(System.Text.StringBuilder sb, DatabaseSchema? schema)
    {
        if (schema == null || schema.Sequences.Count == 0)
            return;

        // "SELECT NEXT VALUE FOR {name}" (SQL Server) vs "SELECT nextval('{name}')"
        // (PostgreSQL). Any other dialect never populates Sequences, but guard
        // anyway so a mislabeled snapshot emits nothing rather than wrong SQL.
        bool isSqlServer = string.Equals(schema.Dialect, "sqlserver", System.StringComparison.OrdinalIgnoreCase);
        bool isPostgres = string.Equals(schema.Dialect, "postgres", System.StringComparison.OrdinalIgnoreCase);
        if (!isSqlServer && !isPostgres)
            return;

        var emitted = new System.Collections.Generic.List<(string Method, string Sql)>();
        foreach (var seq in schema.Sequences.Values)
        {
            if (!IdentifierGuard.IsValidIdentifier(seq.Name))
                continue; // hostile/unusable name: refuse to embed it in SQL

            string method = "Next" + DialectMapper.ToPascalCase(seq.Name);
            string literal = isSqlServer
                ? "SELECT NEXT VALUE FOR " + seq.Name
                : "SELECT nextval('" + seq.Name + "')";
            emitted.Add((method, IdentifierGuard.ToStringLiteral(literal)));
        }

        if (emitted.Count == 0)
            return;

        sb.AppendLine();
        sb.AppendLine("        private SequenceAccessor? _sequences;");
        sb.AppendLine("        public SequenceAccessor Sequences => _sequences ??= new SequenceAccessor(this);");
        sb.AppendLine();
        sb.AppendLine("""
        /// <summary>Typed accessors for the database's sequence objects; each
        /// method advances the underlying sequence and returns the new value.</summary>
        public sealed class SequenceAccessor
        {
            private readonly JauntyDb _db;

            internal SequenceAccessor(JauntyDb db) => _db = db;

            private long Scalar(string sql)
            {
                bool opened = _db.Connection.State != System.Data.ConnectionState.Open;
                if (opened) _db.Connection.Open();
                try
                {
                    using var cmd = _db.Connection.CreateCommand();
                    cmd.CommandText = sql;
                    cmd.Transaction = _db.CurrentTransaction;
                    return System.Convert.ToInt64(cmd.ExecuteScalar());
                }
                finally
                {
                    if (opened) _db.Connection.Close();
                }
            }

            private async System.Threading.Tasks.Task<long> ScalarAsync(string sql, System.Threading.CancellationToken cancellationToken)
            {
                bool opened = _db.Connection.State != System.Data.ConnectionState.Open;
                if (opened) await _db.Connection.OpenAsync(cancellationToken).ConfigureAwait(false);
                try
                {
                    using var cmd = _db.Connection.CreateCommand();
                    cmd.CommandText = sql;
                    cmd.Transaction = _db.CurrentTransaction;
                    return System.Convert.ToInt64(await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false));
                }
                finally
                {
                    if (opened) _db.Connection.Close();
                }
            }
""");

        foreach (var (method, sqlLiteral) in emitted)
        {
            sb.AppendLine();
            sb.AppendLine($"            public long {method}() => Scalar(\"{sqlLiteral}\");");
            sb.AppendLine($"            public System.Threading.Tasks.Task<long> {method}Async(System.Threading.CancellationToken cancellationToken = default) => ScalarAsync(\"{sqlLiteral}\", cancellationToken);");
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Canonical per-table row POCO (e.g. Shipper for table Shippers).
    /// Property order mirrors the table's column order, matching the
    /// ordinals every full-row query reads.
    /// </summary>
    public static string EmitRowPoco(string rowTypeName, TableSchema tableSchema, string? dialect = null)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");

        // The "<Entity>Row" name only ever appears when Inflector.RowTypeName
        // fell back because singularizing the entity name was a no-op
        // (already-singular tables like MailQueue, or views). That's the one
        // case a reader can be looking at this data-carrying POCO right next
        // to the same-named-minus-"Row" query accessor class and not know
        // which is which — so call it out right here, not just in the design
        // docs, since this is the point a consumer actually looks.
        string entityPascalForComment = DialectMapper.ToPascalCase(tableSchema.Name);
        if (rowTypeName == entityPascalForComment + "Row")
        {
            sb.AppendLine($"    // Row type; see JauntyDb.{entityPascalForComment} for the query accessor.");
        }

        sb.AppendLine($"    public class {rowTypeName}");
        sb.AppendLine("    {");
        foreach (var col in tableSchema.Columns.Values)
        {
            string csharpType = DialectMapper.MapColumnToCSharp(col, dialect);
            // `required` only where CS8618 applies (non-nullable reference
            // types); value types stay optional so POCO-based Insert doesn't
            // force callers to zero-fill database-assigned keys.
            string modifier = csharpType == "string" || csharpType == "byte[]" ? "required " : "";
            sb.AppendLine($"        public {modifier}{csharpType} {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} {{ get; set; }}");
        }
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Materializes one row; shared by every full-row query of this table.</summary>");
        sb.AppendLine($"        public static {rowTypeName} Read(System.Data.Common.DbDataReader reader) => new {rowTypeName}");
        sb.AppendLine("        {");
        int ordinal = 0;
        int colCount = tableSchema.Columns.Count;
        foreach (var col in tableSchema.Columns.Values)
        {
            string csharpType = DialectMapper.MapColumnToCSharp(col, dialect);
            string comma = ordinal < colCount - 1 ? "," : "";
            sb.AppendLine($"            {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} = {GetReaderCall(csharpType, ordinal)}{comma}");
            ordinal++;
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

}
