using JauntyQ.Schema;
using JauntyQ.SqlParser.IR;

namespace JauntyQ.Generator;
public static partial class CodeEmitter
{
    private static void EmitProcScript(
        System.Text.StringBuilder sb,
        string procName,
        string methodName,
        string originalSql,
        QueryModel query,
        ProjectionModel? projection,
        DatabaseSchema? schema,
        Directives.DirectiveModel? directives,
        bool isCrud)
    {
        // Build parameter list for CREATE PROCEDURE
        var procParams = new System.Collections.Generic.List<string>();
        foreach (var param in query.Parameters)
        {
            string csharpType;
            if (isCrud)
                csharpType = InferCrudParameterType(param, query, schema, directives);
            else if (projection != null)
                csharpType = InferParameterType(param.Name, query, projection, schema, directives);
            else
                csharpType = "object";

            var sqlType = CSharpToSqlTypeMapper.Map(csharpType);
            procParams.Add($"    @{param.Name} {sqlType}");
        }

        var paramBlock = procParams.Count > 0
            ? "\n" + string.Join(",\n", procParams) + "\n"
            : "";

        var procSql = $"CREATE OR ALTER PROCEDURE [{procName}]{paramBlock}AS\nBEGIN\n    SET NOCOUNT ON;\n    {StripLeadingSqlComments(originalSql)}\nEND";

        sb.AppendLine("        public static partial class Proc");
        sb.AppendLine("        {");
        sb.AppendLine($"            public const string {methodName} = @\"{EscapeVerbatimString(procSql)}\";");
        sb.AppendLine("        }");
    }

    /// <summary>
    /// Emits a typed call to a stored procedure that already exists in the
    /// database (bound via -- @call). Unlike EmitProcScript, JauntyQ does not
    /// author the body — it reads the callable contract (params, result columns)
    /// from the schema snapshot and emits a CommandType.StoredProcedure call
    /// with ordinal result materialization. Supports IN and OUT/INOUT params;
    /// v1 handles a single result set.
    /// </summary>
    public static string EmitProcCall(string entityName, string methodName, JauntyQ.Schema.ProcedureSchema procedure, string? dialect)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        bool hasResults = procedure.Results.Count > 0;
        string resultType = $"Result.{methodName}";

        // Result DTO (only when the proc returns rows).
        if (hasResults)
        {
            sb.AppendLine("        public static partial class Result");
            sb.AppendLine("        {");
            sb.AppendLine($"            public class {methodName}");
            sb.AppendLine("            {");
            foreach (var col in procedure.Results)
            {
                string ct = DialectMapper.MapColumnToCSharp(col);
                sb.AppendLine($"                public required {ct} {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} {{ get; set; }}");
            }
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Ordinal materializer (mirrors the SELECT path).
            sb.AppendLine($"        private static {resultType} __Map{methodName}(System.Data.Common.DbDataReader reader) => new {resultType}");
            sb.AppendLine("        {");
            for (int i = 0; i < procedure.Results.Count; i++)
            {
                var col = procedure.Results[i];
                string ct = DialectMapper.MapColumnToCSharp(col);
                string comma = i < procedure.Results.Count - 1 ? "," : "";
                sb.AppendLine($"            {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} = {GetReaderCall(ct, i)}{comma}");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "_conn", isStatic: false, isAsync: false, dialect);
        sb.AppendLine();
        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "conn", isStatic: true, isAsync: false, dialect);
        sb.AppendLine();
        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "_conn", isStatic: false, isAsync: true, dialect);
        sb.AppendLine();
        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "conn", isStatic: true, isAsync: true, dialect);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

}
