using JauntyQ.Schema;
using JauntyQ.SqlParser.IR;

namespace JauntyQ.Generator;
public static partial class CodeEmitter
{
    public static string EmitEntityCore(string entityName)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly DbConnection _conn;");
        sb.AppendLine("        private readonly JauntyDb? _db;");
        sb.AppendLine();
        sb.AppendLine($"        internal {entityName}(DbConnection conn) => _conn = conn;");
        sb.AppendLine();
        sb.AppendLine($"        internal {entityName}(JauntyDb db)");
        sb.AppendLine("        {");
        sb.AppendLine("            _db = db;");
        sb.AppendLine("            _conn = db.Connection;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitJauntyDb(
        System.Collections.Generic.IEnumerable<string> entityNames,
        DatabaseSchema? schema = null)
    {
        var sb = new System.Text.StringBuilder();

        string taskType = TypeRef(schema, "Task", "System.Threading.Tasks");
        // AUD-R50-03 (residual): these BCL names appear as bare literals in the
        // template below; a table whose entity/row-POCO name equals one of them
        // (e.g. "invalid_operation_exceptions", "i_disposables") would shadow
        // the BCL type namespace-wide and break this always-emitted file.
        string invalidOpEx = TypeRef(schema, "InvalidOperationException", "System");
        string disposableType = TypeRef(schema, "IDisposable", "System");

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public class JauntyDb");
        sb.AppendLine("    {");
        sb.AppendLine($$"""
        private readonly DbConnection _conn;
        private DbTransaction? _tx;
        private bool _txOpenedConnection;

        public JauntyDb(DbConnection conn) => _conn = conn;

        internal DbConnection Connection => _conn;
        internal DbTransaction? CurrentTransaction => _tx;

        /// <summary>
        /// Opens the connection if needed and starts a transaction. Every
        /// db.* call automatically enlists until Commit/Rollback/Dispose;
        /// if the connection was opened here it is closed when the
        /// transaction ends. Dispose without Commit rolls back.
        /// </summary>
        public Transaction BeginTransaction()
        {
            if (_tx != null)
                throw new {{invalidOpEx}}("A JauntyDb transaction is already active.");
            bool openedNow = _conn.State != ConnectionState.Open;
            if (openedNow) _conn.Open();
            try
            {
                _tx = _conn.BeginTransaction();
            }
            catch
            {
                // A failed BeginTransaction must not leave a dangling "we opened
                // it" claim behind: if we opened the connection for this attempt,
                // close it again so a retry on this instance starts from a clean
                // slate instead of silently losing track of who opened it.
                if (openedNow) _conn.Close();
                throw;
            }
            _txOpenedConnection = openedNow;
            return new Transaction(this, _tx);
        }

        public async {{taskType}}<Transaction> BeginTransactionAsync(CancellationToken cancellationToken = default)
        {
            if (_tx != null)
                throw new {{invalidOpEx}}("A JauntyDb transaction is already active.");
            bool openedNow = _conn.State != ConnectionState.Open;
            if (openedNow) await _conn.OpenAsync(cancellationToken).ConfigureAwait(false);
            try
            {
                _tx = await _conn.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
            }
            catch
            {
                if (openedNow) _conn.Close();
                throw;
            }
            _txOpenedConnection = openedNow;
            return new Transaction(this, _tx);
        }

        private void EndTransaction()
        {
            _tx = null;
            if (_txOpenedConnection && _conn.State != ConnectionState.Closed)
                _conn.Close();
            _txOpenedConnection = false;
        }

        public sealed class Transaction : {{disposableType}}
        {
            private readonly JauntyDb _db;
            private DbTransaction? _inner;

            internal Transaction(JauntyDb db, DbTransaction inner)
            {
                _db = db;
                _inner = inner;
            }

            public void Commit()
            {
                if (_inner == null)
                    throw new {{invalidOpEx}}("Transaction already completed.");
                _inner.Commit();
                End();
            }

            public void Rollback()
            {
                if (_inner == null)
                    throw new {{invalidOpEx}}("Transaction already completed.");
                _inner.Rollback();
                End();
            }

            public void Dispose()
            {
                if (_inner == null) return;
                End(); // disposing an uncommitted DbTransaction rolls back
            }

            private void End()
            {
                _inner!.Dispose();
                _inner = null;
                _db.EndTransaction();
            }
        }
""");

        foreach (var entity in entityNames)
        {
            string fieldName = "_" + ToCamelCase(entity);
            sb.AppendLine();
            sb.AppendLine($"        private {entity}? {fieldName};");
            sb.AppendLine($"        public {entity} {entity} => {fieldName} ??= new {entity}(this);");
        }

        EmitSequenceAccessor(sb, schema);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the lazily-constructed <c>db.Sequences</c> accessor plus its nested
    /// <c>SequenceAccessor</c> class, one <c>Next{Name}()</c>/<c>Next{Name}Async()</c>
    /// method per database sequence. SQL Server, PostgreSQL, and MariaDB (under
    /// the "mysql" dialect string; real/Oracle MySQL never populates
    /// <see cref="DatabaseSchema.Sequences"/> at all, since it has no sequence
    /// object for the extractor to find) populate
    /// <see cref="DatabaseSchema.Sequences"/>; this is a no-op for any other
    /// dialect (and when the snapshot has no sequences at all). Each sequence
    /// name flows into both a C# method name and an embedded SQL literal, so it
    /// crosses the same trust boundary as table/column names: invalid raw
    /// identifiers are skipped and the SQL side is emitted through
    /// <see cref="IdentifierGuard.ToStringLiteral"/>.
    /// </summary>
    private static void EmitSequenceAccessor(System.Text.StringBuilder sb, DatabaseSchema? schema)
    {
        if (schema == null || schema.Sequences.Count == 0)
            return;

        // "SELECT NEXT VALUE FOR {name}" (SQL Server) vs "SELECT nextval('{name}')"
        // (PostgreSQL) vs "SELECT NEXTVAL({name})" (MariaDB, verified live against
        // mariadb:11 -- its NEXTVAL() takes a bare identifier, no quoting). Any
        // other dialect never populates Sequences, but guard anyway so a
        // mislabeled snapshot emits nothing rather than wrong SQL.
        bool isSqlServer = string.Equals(schema.Dialect, "sqlserver", System.StringComparison.OrdinalIgnoreCase);
        bool isPostgres = string.Equals(schema.Dialect, "postgres", System.StringComparison.OrdinalIgnoreCase);
        bool isMySql = string.Equals(schema.Dialect, "mysql", System.StringComparison.OrdinalIgnoreCase);
        if (!isSqlServer && !isPostgres && !isMySql)
            return;

        var emitted = new System.Collections.Generic.List<(string Method, string Sql)>();
        var seenMethods = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal);
        foreach (var seq in schema.Sequences.Values)
        {
            if (!IdentifierGuard.IsValidIdentifier(seq.Name))
                continue; // hostile/unusable name: refuse to embed it in SQL

            // AUD-R64-01: bare-identifier shape alone isn't enough -- a
            // sequence name reserved in the target engine's own grammar, or
            // (PostgreSQL only) containing an uppercase letter that would
            // silently fold away on an unquoted reference, must be skipped
            // the same way AutoCrud's own IsBareIdentifier gate now is.
            if (JauntyQ.Analysis.DialectReservedWords.IsReservedInDialect(seq.Name, schema.Dialect, JauntyQ.Analysis.SqlIdentifierPosition.Object))
                continue;
            if (JauntyQ.Analysis.DialectReservedWords.RequiresQuotingForCase(seq.Name, schema.Dialect))
                continue;

            string method = "Next" + DialectMapper.ToPascalCase(seq.Name);

            // Two distinct sequence names can fold to the same PascalCase method
            // name (e.g. "order_number" and "OrderNumber"); the generator reports
            // this as JNT2009. Keep only the first here regardless, so a snapshot
            // that somehow reaches this point without going through the generator's
            // own check (or a future caller) still can't produce a CS0111 duplicate
            // member -- silently dropping the same way the identifier-guard skip
            // above already does for a hostile name.
            if (!seenMethods.Add(method))
                continue;
            string literal = isSqlServer
                ? "SELECT NEXT VALUE FOR " + seq.Name
                : isPostgres
                    ? "SELECT nextval('" + seq.Name + "')"
                    : "SELECT NEXTVAL(" + seq.Name + ")";
            emitted.Add((method, IdentifierGuard.ToStringLiteral(literal)));
        }

        if (emitted.Count == 0)
            return;

        string taskType = TypeRef(schema, "Task", "System.Threading.Tasks");
        // AUD-R50-03 (residual): Convert appears bare in the template below —
        // a table named "converts" (row POCO "Convert") would otherwise shadow
        // System.Convert and break Convert.ToInt64 with CS0117.
        string convertType = TypeRef(schema, "Convert", "System");

        sb.AppendLine();
        sb.AppendLine("        private SequenceAccessor? _sequences;");
        sb.AppendLine("        public SequenceAccessor Sequences => _sequences ??= new SequenceAccessor(this);");
        sb.AppendLine();
        sb.AppendLine($$"""
        /// <summary>Typed accessors for the database's sequence objects; each
        /// method advances the underlying sequence and returns the new value.</summary>
        public sealed class SequenceAccessor
        {
            private readonly JauntyDb _db;

            internal SequenceAccessor(JauntyDb db) => _db = db;

            private long Scalar(string sql)
            {
                bool opened = _db.Connection.State != ConnectionState.Open;
                if (opened) _db.Connection.Open();
                try
                {
                    using DbCommand cmd = _db.Connection.CreateCommand();
                    cmd.CommandText = sql;
                    cmd.Transaction = _db.CurrentTransaction;
                    return {{convertType}}.ToInt64(cmd.ExecuteScalar());
                }
                finally
                {
                    if (opened) _db.Connection.Close();
                }
            }

            private async {{taskType}}<long> ScalarAsync(string sql, CancellationToken cancellationToken)
            {
                bool opened = _db.Connection.State != ConnectionState.Open;
                if (opened) await _db.Connection.OpenAsync(cancellationToken).ConfigureAwait(false);
                try
                {
                    using DbCommand cmd = _db.Connection.CreateCommand();
                    cmd.CommandText = sql;
                    cmd.Transaction = _db.CurrentTransaction;
                    return {{convertType}}.ToInt64(await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false));
                }
                finally
                {
                    if (opened) _db.Connection.Close();
                }
            }
""");

        foreach (var (method, sqlLiteral) in emitted)
        {
            sb.AppendLine();
            sb.AppendLine($"            public long {method}() => Scalar(\"{sqlLiteral}\");");
            sb.AppendLine($"            public {taskType}<long> {method}Async(CancellationToken cancellationToken = default) => ScalarAsync(\"{sqlLiteral}\", cancellationToken);");
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Canonical per-table row POCO (e.g. Shipper for table Shippers).
    /// Property order mirrors the table's column order, matching the
    /// ordinals every full-row query reads.
    /// </summary>
    public static string EmitRowPoco(string rowTypeName, TableSchema tableSchema, string? dialect = null, DatabaseSchema? schema = null)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");

        // The "<Entity>Row" name only ever appears when Inflector.RowTypeName
        // fell back because singularizing the entity name was a no-op
        // (already-singular tables like MailQueue, or views). That's the one
        // case a reader can be looking at this data-carrying POCO right next
        // to the same-named-minus-"Row" query accessor class and not know
        // which is which — so call it out right here, not just in the design
        // docs, since this is the point a consumer actually looks.
        string entityPascalForComment = DialectMapper.ToPascalCase(tableSchema.Name);
        if (rowTypeName == entityPascalForComment + "Row")
        {
            sb.AppendLine($"    // Row type; see JauntyDb.{entityPascalForComment} for the query accessor.");
        }

        sb.AppendLine($"    public class {rowTypeName}");
        sb.AppendLine("    {");
        foreach (var col in tableSchema.Columns.Values)
        {
            string csharpType = DialectMapper.MapColumnToCSharp(col, dialect, schema);
            // `required` only where CS8618 applies (non-nullable reference
            // types); value types stay optional so POCO-based Insert doesn't
            // force callers to zero-fill database-assigned keys.
            string modifier = csharpType == "string" || csharpType == "byte[]" ? "required " : "";
            sb.AppendLine($"        public {modifier}{ShortenValueTypeName(schema, csharpType)} {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} {{ get; set; }}");
        }
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Materializes one row; shared by every full-row query of this table.</summary>");
        sb.AppendLine($"        public static {rowTypeName} Read(DbDataReader reader) => new {rowTypeName}");
        sb.AppendLine("        {");
        int ordinal = 0;
        int colCount = tableSchema.Columns.Count;
        foreach (var col in tableSchema.Columns.Values)
        {
            string csharpType = DialectMapper.MapColumnToCSharp(col, dialect, schema);
            string comma = ordinal < colCount - 1 ? "," : "";
            sb.AppendLine($"            {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} = {GetReaderCall(csharpType, ordinal, schema)}{comma}");
            ordinal++;
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

}
