using JauntyQ.Schema;
using JauntyQ.SqlParser.IR;

namespace JauntyQ.Generator;

public static partial class CodeEmitter
{
    private static void EmitProcScript(
        System.Text.StringBuilder sb,
        string procName,
        string methodName,
        string originalSql,
        QueryModel query,
        ProjectionModel? projection,
        DatabaseSchema? schema,
        Directives.DirectiveModel? directives,
        bool isCrud)
    {
        // Build parameter list for CREATE PROCEDURE
        var procParams = new System.Collections.Generic.List<string>();
        foreach (var param in OrderedParameters(query, directives))
        {
            string csharpType;
            if (isCrud)
                csharpType = InferCrudParameterType(param, query, schema, directives);
            else if (projection != null)
                csharpType = InferParameterType(param.Name, query, projection, schema, directives);
            else
                csharpType = "object";

            var sqlType = CSharpToSqlTypeMapper.Map(csharpType);
            // AUD-R4-17: the C# type alone carries no numeric precision, so the
            // mapper can only say decimal(18,2). When the parameter is bound to
            // a schema column that records its real precision, emit the column's
            // own decimal(p,s) instead -- a scaffold declaring decimal(18,2) for
            // a decimal(10,4) column silently rounds the fraction digits the
            // table itself accepts, before the body's comparison ever runs.
            if (csharpType.TrimEnd('?') == "decimal")
            {
                var column = ResolveBoundColumn(param, query, schema, out _);
                if (column is { Precision: > 0 })
                    sqlType = $"decimal({column.Precision},{column.Scale ?? 0})";
            }
            procParams.Add($"    @{param.Name} {sqlType}");
        }

        var paramBlock = procParams.Count > 0
            ? "\n" + string.Join(",\n", procParams) + "\n"
            : "";

        string bodySql = IndentSqlContinuationLines(StripLeadingSqlComments(originalSql), 4);
        // procName is deliberately kept bracketed: IdentifierGuard.IsValidIdentifier
        // only checks C#-identifier shape, not SQL reserved words, so a proc named
        // e.g. "User" or "Order" is reachable here and unbracketed would be a
        // T-SQL syntax error.
        var procSql = $"CREATE OR ALTER PROCEDURE [{procName}]{paramBlock}AS\nBEGIN\n    SET NOCOUNT ON;\n    {bodySql}\nEND";

        sb.AppendLine("        public static partial class Proc");
        sb.AppendLine("        {");
        sb.AppendLine($"            public const string {methodName} = @\"{EscapeVerbatimString(procSql)}\";");
        sb.AppendLine("        }");
    }

    /// <summary>
    /// Emits a typed call to a stored procedure that already exists in the
    /// database (bound via -- @call). Unlike EmitProcScript, JauntyQ does not
    /// author the body — it reads the callable contract (params, result columns)
    /// from the schema snapshot and emits a CommandType.StoredProcedure call
    /// with ordinal result materialization. Supports IN and OUT/INOUT params;
    /// v1 handles a single result set.
    /// </summary>
    public static string EmitProcCall(string entityName, string methodName, JauntyQ.Schema.ProcedureSchema procedure, string? dialect, DatabaseSchema? schema = null)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        bool hasResults = procedure.Results.Count > 0;
        string resultType = $"Result.{methodName}";

        // Result DTO (only when the proc returns rows).
        if (hasResults)
        {
            sb.AppendLine("        public static partial class Result");
            sb.AppendLine("        {");
            sb.AppendLine($"            public class {methodName}");
            sb.AppendLine("            {");
            foreach (var col in procedure.Results)
            {
                string ct = DialectMapper.MapColumnToCSharp(col, dialect, schema);
                sb.AppendLine($"                public required {ShortenValueTypeName(schema, ct)} {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} {{ get; set; }}");
            }
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Ordinal materializer (mirrors the SELECT path).
            sb.AppendLine($"        private static {resultType} __Map{methodName}(DbDataReader reader) => new {resultType}");
            sb.AppendLine("        {");
            for (int i = 0; i < procedure.Results.Count; i++)
            {
                var col = procedure.Results[i];
                string ct = DialectMapper.MapColumnToCSharp(col, dialect, schema);
                string comma = i < procedure.Results.Count - 1 ? "," : "";
                sb.AppendLine($"            {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} = {GetReaderCall(ct, i, schema)}{comma}");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "_conn", isStatic: false, isAsync: false, dialect, schema);
        sb.AppendLine();
        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "conn", isStatic: true, isAsync: false, dialect, schema);
        sb.AppendLine();
        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "_conn", isStatic: false, isAsync: true, dialect, schema);
        sb.AppendLine();
        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "conn", isStatic: true, isAsync: true, dialect, schema);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

}
