using JauntyQ.Analysis;
using JauntyQ.Schema;

namespace JauntyQ.Generator;

/// <summary>
/// Spec 013: emission of captured database enums.
///
/// Everything here is emitted rather than referenced from JauntyQ.Runtime.
/// The runtime's README forbids helpers that generated code calls
/// unconditionally, and an enum's wire mapping is per-snapshot data anyway —
/// there is nothing shareable to put in a library.
/// </summary>
public static partial class CodeEmitter
{
    /// <summary>
    /// The enums an emitted type actually references, in snapshot order. A
    /// captured type no column points at is deliberately not emitted: it stays
    /// in the snapshot so drift detection can see it disappear, but adding a
    /// public type no consumer can reach is surface for nothing.
    /// </summary>
    internal static System.Collections.Generic.List<string> ReferencedEnumNames(DatabaseSchema schema)
    {
        var referenced = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal);
        foreach (var table in schema.Tables.Values)
            foreach (var col in table.Columns.Values)
                if (!string.IsNullOrEmpty(col.EnumName) && schema.Enums.ContainsKey(col.EnumName!))
                    referenced.Add(col.EnumName!);

        // Snapshot order, not the HashSet's: a source generator that reorders
        // its output between runs defeats incremental compilation.
        var ordered = new System.Collections.Generic.List<string>();
        foreach (var pair in schema.Enums)
            if (referenced.Contains(pair.Key) && pair.Value.Members.Count > 0)
                ordered.Add(pair.Key);
        return ordered;
    }

    /// <summary>
    /// One file carrying every emitted enum, its <c>{EnumName}Values</c>
    /// companion, and the shared <c>JauntyQEnumValueException</c>. Returns
    /// null when the snapshot has no enum any column references, so the caller
    /// adds no source at all rather than an empty file.
    /// </summary>
    public static string? EmitEnums(DatabaseSchema schema)
    {
        var names = ReferencedEnumNames(schema);
        if (names.Count == 0)
            return null;

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");

        EmitEnumValueException(sb);

        foreach (string enumName in names)
        {
            var enumSchema = schema.Enums[enumName];
            string typeName = DialectMapper.EnumTypeName(enumName);

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Database enum '{XmlDocEscape(enumName)}'. Member order matches the database's own.</summary>");
            sb.AppendLine($"    public enum {typeName}");
            sb.AppendLine("    {");
            foreach (var member in enumSchema.Members)
            {
                sb.AppendLine($"        /// <summary>Wire value <c>{XmlDocEscape(member.Value)}</c>.</summary>");
                sb.AppendLine($"        {MemberName(member)},");
            }
            sb.AppendLine("    }");

            EmitEnumValuesCompanion(sb, enumName, typeName, enumSchema);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Escapes a raw database value for an XML doc comment. Member values are
    /// snapshot-derived, so a value containing &lt; or &amp; would otherwise
    /// emit a malformed doc comment (CS1570) on every build.
    /// </summary>
    private static string XmlDocEscape(string? value)
        => (value ?? string.Empty).Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    /// <summary>
    /// The captured C# identifier, or a fold of the wire value for a snapshot
    /// written before csharpName existed. Never re-derives when the snapshot
    /// already carries one: emission and capture must not be able to drift.
    /// </summary>
    private static string MemberName(EnumMember member)
        => IdentifierGuard.Escape(string.IsNullOrEmpty(member.CSharpName)
            ? EnumMemberNaming.Fold(member.Value)
            : member.CSharpName);

    private static void EmitEnumValueException(System.Text.StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Thrown when the database returns an enum value the schema snapshot");
        sb.AppendLine("    /// does not contain — almost always because the type gained a member");
        sb.AppendLine("    /// after the snapshot was pulled. Re-pull the schema and rebuild.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class JauntyQEnumValueException : InvalidOperationException");
        sb.AppendLine("    {");
        sb.AppendLine("        public JauntyQEnumValueException(string enumType, string column, string value)");
        sb.AppendLine("            : base(\"Database value '\" + value + \"' for column '\" + column + \"' is not a member of enum '\" + enumType +");
        sb.AppendLine("                   \"' as captured in the schema snapshot. Re-pull the schema (jaunty schema pull) and rebuild.\")");
        sb.AppendLine("        {");
        sb.AppendLine("            EnumType = enumType;");
        sb.AppendLine("            Column = column;");
        sb.AppendLine("            Value = value;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>The captured enum type the value did not belong to.</summary>");
        sb.AppendLine("        public string EnumType { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>The column the value was read from, as \"table.column\".</summary>");
        sb.AppendLine("        public string Column { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>The verbatim value the database returned.</summary>");
        sb.AppendLine("        public string Value { get; }");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Parse/ToWire for one enum, as switches over the verbatim wire values.
    /// No reflection and no Enum.Parse, so the trim and AOT analyzers have
    /// nothing to complain about and the mapping is exactly what the snapshot
    /// captured rather than whatever the member names happen to spell.
    /// </summary>
    private static void EmitEnumValuesCompanion(
        System.Text.StringBuilder sb, string enumName, string typeName, EnumSchema enumSchema)
    {
        string literalEnumName = IdentifierGuard.ToStringLiteral(enumName);

        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Wire-value conversion for <see cref=\"{typeName}\"/>.</summary>");
        sb.AppendLine($"    public static class {typeName}Values");
        sb.AppendLine("    {");

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Converts a database value to its member. <paramref name=\"column\"/> is");
        sb.AppendLine("        /// only used to name the offender if the value is unknown.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static {typeName} Parse(string value, string column)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (value)");
        sb.AppendLine("            {");
        foreach (var member in enumSchema.Members)
        {
            sb.AppendLine($"                case \"{IdentifierGuard.ToStringLiteral(member.Value)}\":");
            sb.AppendLine($"                    return {typeName}.{MemberName(member)};");
        }
        sb.AppendLine("                default:");
        sb.AppendLine($"                    throw new JauntyQEnumValueException(\"{literalEnumName}\", column, value);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");

        sb.AppendLine();
        sb.AppendLine("        /// <summary>Converts a member back to the value the database stores.</summary>");
        sb.AppendLine($"        public static string ToWire({typeName} value)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (value)");
        sb.AppendLine("            {");
        foreach (var member in enumSchema.Members)
        {
            sb.AppendLine($"                case {typeName}.{MemberName(member)}:");
            sb.AppendLine($"                    return \"{IdentifierGuard.ToStringLiteral(member.Value)}\";");
        }
        // An enum is just its underlying integer in C#, so ((OrderStatus)999)
        // is a legal value a caller can construct and hand to a write. Binding
        // its integer would silently write garbage the database would reject
        // with a type error naming nothing useful; throwing here names it.
        sb.AppendLine("                default:");
        sb.AppendLine($"                    throw new JauntyQEnumValueException(\"{literalEnumName}\", \"{literalEnumName}\", value.ToString());");
        sb.AppendLine("            }");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
    }
}
