using JauntyQ.Schema;
using JauntyQ.SqlParser.IR;

namespace JauntyQ.Generator;
public static partial class CodeEmitter
{
    public static string EmitEntityCore(string entityName)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly System.Data.Common.DbConnection _conn;");
        sb.AppendLine("        private readonly JauntyDb? _db;");
        sb.AppendLine();
        sb.AppendLine($"        internal {entityName}(System.Data.Common.DbConnection conn) => _conn = conn;");
        sb.AppendLine();
        sb.AppendLine($"        internal {entityName}(JauntyDb db)");
        sb.AppendLine("        {");
        sb.AppendLine("            _db = db;");
        sb.AppendLine("            _conn = db.Connection;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitJauntyDb(System.Collections.Generic.IEnumerable<string> entityNames)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public class JauntyDb");
        sb.AppendLine("    {");
        sb.AppendLine("""
        private readonly System.Data.Common.DbConnection _conn;
        private System.Data.Common.DbTransaction? _tx;
        private bool _txOpenedConnection;

        public JauntyDb(System.Data.Common.DbConnection conn) => _conn = conn;

        internal System.Data.Common.DbConnection Connection => _conn;
        internal System.Data.Common.DbTransaction? CurrentTransaction => _tx;

        /// <summary>
        /// Opens the connection if needed and starts a transaction. Every
        /// db.* call automatically enlists until Commit/Rollback/Dispose;
        /// if the connection was opened here it is closed when the
        /// transaction ends. Dispose without Commit rolls back.
        /// </summary>
        public Transaction BeginTransaction()
        {
            if (_tx != null)
                throw new System.InvalidOperationException("A JauntyDb transaction is already active.");
            _txOpenedConnection = _conn.State != System.Data.ConnectionState.Open;
            if (_txOpenedConnection) _conn.Open();
            _tx = _conn.BeginTransaction();
            return new Transaction(this, _tx);
        }

        public async System.Threading.Tasks.Task<Transaction> BeginTransactionAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            if (_tx != null)
                throw new System.InvalidOperationException("A JauntyDb transaction is already active.");
            _txOpenedConnection = _conn.State != System.Data.ConnectionState.Open;
            if (_txOpenedConnection) await _conn.OpenAsync(cancellationToken).ConfigureAwait(false);
            _tx = await _conn.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
            return new Transaction(this, _tx);
        }

        private void EndTransaction()
        {
            _tx = null;
            if (_txOpenedConnection && _conn.State != System.Data.ConnectionState.Closed)
                _conn.Close();
            _txOpenedConnection = false;
        }

        public sealed class Transaction : System.IDisposable
        {
            private readonly JauntyDb _db;
            private System.Data.Common.DbTransaction? _inner;

            internal Transaction(JauntyDb db, System.Data.Common.DbTransaction inner)
            {
                _db = db;
                _inner = inner;
            }

            public void Commit()
            {
                if (_inner == null)
                    throw new System.InvalidOperationException("Transaction already completed.");
                _inner.Commit();
                End();
            }

            public void Rollback()
            {
                if (_inner == null)
                    throw new System.InvalidOperationException("Transaction already completed.");
                _inner.Rollback();
                End();
            }

            public void Dispose()
            {
                if (_inner == null) return;
                End(); // disposing an uncommitted DbTransaction rolls back
            }

            private void End()
            {
                _inner!.Dispose();
                _inner = null;
                _db.EndTransaction();
            }
        }
""");

        foreach (var entity in entityNames)
        {
            string fieldName = "_" + ToCamelCase(entity);
            sb.AppendLine();
            sb.AppendLine($"        private {entity}? {fieldName};");
            sb.AppendLine($"        public {entity} {entity} => {fieldName} ??= new {entity}(this);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Canonical per-table row POCO (e.g. Shipper for table Shippers).
    /// Property order mirrors the table's column order, matching the
    /// ordinals every full-row query reads.
    /// </summary>
    public static string EmitRowPoco(string rowTypeName, TableSchema tableSchema)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");

        // The "<Entity>Row" name only ever appears when Inflector.RowTypeName
        // fell back because singularizing the entity name was a no-op
        // (already-singular tables like MailQueue, or views). That's the one
        // case a reader can be looking at this data-carrying POCO right next
        // to the same-named-minus-"Row" query accessor class and not know
        // which is which — so call it out right here, not just in the design
        // docs, since this is the point a consumer actually looks.
        string entityPascalForComment = DialectMapper.ToPascalCase(tableSchema.Name);
        if (rowTypeName == entityPascalForComment + "Row")
        {
            sb.AppendLine($"    // Row type; see JauntyDb.{entityPascalForComment} for the query accessor.");
        }

        sb.AppendLine($"    public class {rowTypeName}");
        sb.AppendLine("    {");
        foreach (var col in tableSchema.Columns.Values)
        {
            string csharpType = DialectMapper.MapColumnToCSharp(col);
            // `required` only where CS8618 applies (non-nullable reference
            // types); value types stay optional so POCO-based Insert doesn't
            // force callers to zero-fill database-assigned keys.
            string modifier = csharpType == "string" || csharpType == "byte[]" ? "required " : "";
            sb.AppendLine($"        public {modifier}{csharpType} {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} {{ get; set; }}");
        }
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Materializes one row; shared by every full-row query of this table.</summary>");
        sb.AppendLine($"        public static {rowTypeName} Read(System.Data.Common.DbDataReader reader) => new {rowTypeName}");
        sb.AppendLine("        {");
        int ordinal = 0;
        int colCount = tableSchema.Columns.Count;
        foreach (var col in tableSchema.Columns.Values)
        {
            string csharpType = DialectMapper.MapColumnToCSharp(col);
            string comma = ordinal < colCount - 1 ? "," : "";
            sb.AppendLine($"            {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} = {GetReaderCall(csharpType, ordinal)}{comma}");
            ordinal++;
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

}
