using JauntyQ.Schema;
using JauntyQ.SqlParser.IR;

namespace JauntyQ.Generator;
public static partial class CodeEmitter
{
    /// <summary>
    /// POCO-taking overloads for the synthetic write methods:
    /// Update(product), Insert(shipper) (with identity write-back),
    /// Delete(product), Upsert(customer). Emitted only when the scalar
    /// method is the synthetic one - a user override owns its own signature.
    /// </summary>
    public static string EmitPocoOverloads(
        string entityName,
        string rowType,
        TableSchema tableSchema,
        string dialect,
        bool hasInsert,
        bool hasUpdate,
        bool hasDelete,
        bool hasUpsert)
    {
        var columns = new System.Collections.Generic.List<ColumnSchema>(tableSchema.Columns.Values);
        var versionCols = columns.FindAll(c => c.IsRowVersion);
        var pkCols = columns.FindAll(c => c.IsPrimaryKey);
        // Must mirror AutoCrud.Synthesize's own Update setCols filter exactly
        // (AutoCrud.cs) -- this list supplies the Update(row) POCO overload's
        // forwarded arguments and has to match the synthesized SQL's
        // @parameter list one-for-one, including excluding a non-PK identity
        // column (database-assigned; every dialect tested rejects an UPDATE
        // targeting an identity column).
        var setCols = columns.FindAll(c => !c.IsPrimaryKey && !c.IsIdentity && !c.IsRowVersion && !c.IsComputed);
        var insertCols = columns.FindAll(c => !c.IsIdentity && !c.IsRowVersion && !c.IsComputed);
        ColumnSchema? identityCol = null;
        foreach (var c in columns)
        {
            if (c.IsIdentity) { identityCol = identityCol == null ? c : null; if (identityCol == null) break; }
        }
        bool insertReturnsId = identityCol != null && !string.IsNullOrEmpty(dialect);

        string Args(System.Collections.Generic.List<ColumnSchema> cols)
            => string.Join(", ", cols.Select(c => $"row.{IdentifierGuard.Escape(DialectMapper.ToPascalCase(c.Name))}"));

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        // The scalar static targets only carry the optional DbTransaction when
        // no column parameter is itself named "transaction" (the same guard as
        // HasStaticTransactionParam); mirror that so forwarding stays in sync.
        bool TxForwardable(System.Collections.Generic.List<ColumnSchema> cols)
            => !cols.Exists(c => string.Equals(c.Name, "transaction", StringComparison.OrdinalIgnoreCase));

        void Forward(string method, System.Collections.Generic.List<ColumnSchema> cols)
        {
            string args = Args(cols);
            bool tx = TxForwardable(cols);
            string txParam = tx ? ", System.Data.Common.DbTransaction? transaction = null" : "";
            string txArg = tx ? ", transaction" : "";
            sb.AppendLine($"        public int {method}({rowType} row) => {method}({args});");
            sb.AppendLine($"        public static int {method}(System.Data.Common.DbConnection conn, {rowType} row{txParam}) => {method}(conn, {args}{txArg});");
            sb.AppendLine($"        public System.Threading.Tasks.Task<int> {method}Async({rowType} row, System.Threading.CancellationToken cancellationToken = default) => {method}Async({args}, cancellationToken);");
            sb.AppendLine($"        public static System.Threading.Tasks.Task<int> {method}Async(System.Data.Common.DbConnection conn, {rowType} row{txParam}, System.Threading.CancellationToken cancellationToken = default) => {method}Async(conn, {args}{txArg}, cancellationToken);");
            sb.AppendLine();
        }

        if (hasInsert && insertCols.Count > 0)
        {
            if (insertReturnsId)
            {
                string idProp = IdentifierGuard.Escape(DialectMapper.ToPascalCase(identityCol!.Name));
                string idType = DialectMapper.MapDbTypeToCSharp(identityCol.DbType, isNullable: false, dialect: dialect);
                string args = Args(insertCols);
                sb.AppendLine($"        /// <summary>Inserts the row and writes the database-assigned {idProp} back onto it.</summary>");
                sb.AppendLine($"        public {idType} Insert({rowType} row)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = Insert({args});");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                bool insertTx = TxForwardable(insertCols);
                string insertTxParam = insertTx ? ", System.Data.Common.DbTransaction? transaction = null" : "";
                string insertTxArg = insertTx ? ", transaction" : "";
                sb.AppendLine($"        public static {idType} Insert(System.Data.Common.DbConnection conn, {rowType} row{insertTxParam})");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = Insert(conn, {args}{insertTxArg});");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public async System.Threading.Tasks.Task<{idType}> InsertAsync({rowType} row, System.Threading.CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = await InsertAsync({args}, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public static async System.Threading.Tasks.Task<{idType}> InsertAsync(System.Data.Common.DbConnection conn, {rowType} row{insertTxParam}, System.Threading.CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = await InsertAsync(conn, {args}{insertTxArg}, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            else
            {
                Forward("Insert", insertCols);
            }
        }

        if (hasUpdate && setCols.Count > 0 && pkCols.Count > 0)
        {
            // scalar Update parameter order: SET columns then PK columns
            var updateArgsCols = new System.Collections.Generic.List<ColumnSchema>(setCols);
            updateArgsCols.AddRange(pkCols);
            updateArgsCols.AddRange(versionCols);
            Forward("Update", updateArgsCols);
        }

        if (hasDelete && pkCols.Count > 0)
        {
            var deleteArgsCols = new System.Collections.Generic.List<ColumnSchema>(pkCols);
            deleteArgsCols.AddRange(versionCols);
            Forward("Delete", deleteArgsCols);
        }

        if (hasUpsert)
        {
            // Must match EmitUpsert's own column set exactly: when the PK is
            // identity-only and a secondary UNIQUE index is the upsert key,
            // the identity column is database-assigned and never a caller-
            // supplied argument.
            var upsertKey = ResolveUpsertKey(tableSchema);
            bool upsertUsesAlternateKey = upsertKey != null && upsertKey.Exists(c => !c.IsPrimaryKey);
            var upsertCols = upsertUsesAlternateKey
                ? columns.FindAll(c => !c.IsRowVersion && !c.IsIdentity && !c.IsComputed)
                : columns.FindAll(c => !c.IsRowVersion && !c.IsComputed);
            Forward("Upsert", upsertCols);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDto(System.Text.StringBuilder sb, ProjectionModel projection)
    {
        sb.AppendLine($"            public class {projection.Name}");
        sb.AppendLine("            {");
        foreach (var col in projection.Columns)
        {
            // `required` keeps non-nullable reference properties honest (no CS8618)
            // and costs nothing: generated mapping always sets every property.
            sb.AppendLine($"                public required {col.Type} {IdentifierGuard.Escape(col.Name)} {{ get; set; }}");
        }
        sb.AppendLine("            }");
    }

}
