using JauntyQ.Schema;
using JauntyQ.SqlParser.IR;

namespace JauntyQ.Generator;
public static partial class CodeEmitter
{
    /// <summary>
    /// Dialect-native upsert keyed on the primary key. Bypasses the SQL
    /// parser deliberately: MERGE / ON CONFLICT / ON DUPLICATE KEY are
    /// outside the minimal grammar, and the SQL is correct by construction
    /// from the schema snapshot.
    /// </summary>
    public static string EmitUpsert(string entityName, TableSchema tableSchema, string dialect)
    {
        // Rowversion tokens are database-assigned: excluded from the upsert
        // column set entirely. Upsert is documented last-writer-wins.
        var columns = tableSchema.Columns.Values.Where(c => !c.IsRowVersion).ToList();
        var pkCols = columns.FindAll(c => c.IsPrimaryKey);
        var setCols = columns.FindAll(c => !c.IsPrimaryKey);

        string colList = string.Join(", ", columns.Select(c => c.Name));
        string paramList = string.Join(", ", columns.Select(c => $"@{c.Name}"));

        string sql;
        switch (dialect)
        {
            case "sqlserver":
            {
                string srcSelect = string.Join(", ", columns.Select(c => $"@{c.Name} as {c.Name}"));
                string onClause = string.Join(" and ", pkCols.Select(c => $"target.{c.Name} = src.{c.Name}"));
                string updateSet = string.Join(", ", setCols.Select(c => $"{c.Name} = src.{c.Name}"));
                string insertVals = string.Join(", ", columns.Select(c => $"src.{c.Name}"));
                sql = $"merge into {tableSchema.Name} with (holdlock) as target\n" +
                      $"using (select {srcSelect}) as src\n" +
                      $"on {onClause}\n" +
                      $"when matched then update set {updateSet}\n" +
                      $"when not matched then insert ({colList}) values ({insertVals});";
                break;
            }
            case "postgres":
            case "sqlite":
            {
                string conflictCols = string.Join(", ", pkCols.Select(c => c.Name));
                string updateSet = string.Join(", ", setCols.Select(c => $"{c.Name} = excluded.{c.Name}"));
                sql = $"insert into {tableSchema.Name} ({colList})\nvalues ({paramList})\n" +
                      $"on conflict ({conflictCols}) do update set {updateSet}";
                break;
            }
            case "mysql":
            {
                // VALUES(col) works on both MySQL and MariaDB (the 8.0.20+
                // alias form is not MariaDB-compatible).
                string updateSet = string.Join(", ", setCols.Select(c => $"{c.Name} = values({c.Name})"));
                sql = $"insert into {tableSchema.Name} ({colList})\nvalues ({paramList})\n" +
                      $"on duplicate key update {updateSet}";
                break;
            }
            default:
                throw new System.InvalidOperationException($"Upsert synthesis requires a known dialect (got '{dialect}').");
        }

        var paramInfos = new System.Collections.Generic.List<EmittedParam>();
        foreach (var col in columns)
        {
            paramInfos.Add(CreateEmittedParam(col.Name, DialectMapper.MapColumnToCSharp(col), col.IsNullable, col, tableSchema.Name, isWriteTarget: true));
        }

        var stub = new QueryModel { Name = "Upsert" };

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");
        EmitCrudMethodBody(sb, stub, sql, paramInfos, "_conn", isStatic: false, isAsync: false, dialect: dialect);
        sb.AppendLine();
        EmitCrudMethodBody(sb, stub, sql, paramInfos, "conn", isStatic: true, isAsync: false, dialect: dialect);
        sb.AppendLine();
        EmitCrudMethodBody(sb, stub, sql, paramInfos, "_conn", isStatic: false, isAsync: true, dialect: dialect);
        sb.AppendLine();
        EmitCrudMethodBody(sb, stub, sql, paramInfos, "conn", isStatic: true, isAsync: true, dialect: dialect);
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

}
