using JauntyQ.Schema;
using JauntyQ.SqlParser.IR;

namespace JauntyQ.Generator;

public static class CodeEmitter
{
    public static string Emit(QueryModel query, ProjectionModel projection, string originalSql, string entityName, DatabaseSchema? schema = null)
    {
        // Prefix entity name onto DTO class name to avoid collisions across entities
        // e.g. "GetAllRow" becomes "CategoriesGetAllRow"
        var prefixedProjection = new ProjectionModel
        {
            Name = entityName + projection.Name
        };
        foreach (var col in projection.Columns)
            prefixedProjection.Columns.Add(col);

        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        EmitDto(sb, prefixedProjection);
        sb.AppendLine();
        EmitQueryMethods(sb, query, prefixedProjection, originalSql, entityName, schema);
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitEntityCore(string entityName)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly System.Data.Common.DbConnection _conn;");
        sb.AppendLine($"        internal {entityName}(System.Data.Common.DbConnection conn) => _conn = conn;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitJauntyDb(System.Collections.Generic.IEnumerable<string> entityNames)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public class JauntyDb");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly System.Data.Common.DbConnection _conn;");
        sb.AppendLine();
        sb.AppendLine("        public JauntyDb(System.Data.Common.DbConnection conn) => _conn = conn;");

        foreach (var entity in entityNames)
        {
            string fieldName = "_" + ToCamelCase(entity);
            sb.AppendLine();
            sb.AppendLine($"        private {entity}? {fieldName};");
            sb.AppendLine($"        public {entity} {entity} => {fieldName} ??= new {entity}(_conn);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitDto(System.Text.StringBuilder sb, ProjectionModel projection)
    {
        sb.AppendLine($"    public class {projection.Name}");
        sb.AppendLine("    {");
        foreach (var col in projection.Columns)
        {
            sb.AppendLine($"        public {col.Type} {col.Name} {{ get; set; }}");
        }
        sb.AppendLine("    }");
    }

    private static void EmitQueryMethods(
        System.Text.StringBuilder sb,
        QueryModel query,
        ProjectionModel projection,
        string originalSql,
        string entityName,
        DatabaseSchema? schema)
    {
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        // Build parameter list (without connection)
        var paramListNoConn = new System.Text.StringBuilder();
        var paramListWithConn = new System.Text.StringBuilder();
        paramListWithConn.Append("System.Data.Common.DbConnection conn");

        foreach (var param in query.Parameters)
        {
            string paramType = InferParameterType(param.Name, query, projection, schema);
            string paramName = ToCamelCase(param.Name);
            if (paramListNoConn.Length > 0)
                paramListNoConn.Append(", ");
            paramListNoConn.Append($"{paramType} {paramName}");
            paramListWithConn.Append($", {paramType} {paramName}");
        }

        // Instance method
        EmitMethodBody(sb, query, projection, originalSql, paramListNoConn.ToString(), "_conn", isStatic: false);

        sb.AppendLine();

        // Static method
        EmitMethodBody(sb, query, projection, originalSql, paramListWithConn.ToString(), "conn", isStatic: true);

        sb.AppendLine("    }");
    }

    private static void EmitMethodBody(
        System.Text.StringBuilder sb,
        QueryModel query,
        ProjectionModel projection,
        string originalSql,
        string paramList,
        string connVar,
        bool isStatic)
    {
        string modifier = isStatic ? "public static" : "public";
        sb.AppendLine($"        {modifier} System.Collections.Generic.List<{projection.Name}> {query.Name}({paramList})");
        sb.AppendLine("        {");

        // Connection lifecycle
        sb.AppendLine($"            bool weOpened = {connVar}.State != System.Data.ConnectionState.Open;");
        sb.AppendLine($"            if (weOpened) {connVar}.Open();");
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        // Create command
        sb.AppendLine($"                using var cmd = {connVar}.CreateCommand();");
        sb.AppendLine($"                cmd.CommandText = @\"{EscapeVerbatimString(originalSql.Trim())}\";");

        // Bind parameters
        for (int i = 0; i < query.Parameters.Count; i++)
        {
            var param = query.Parameters[i];
            string varName = $"p{i}";
            string paramName = ToCamelCase(param.Name);
            sb.AppendLine();
            sb.AppendLine($"                var {varName} = cmd.CreateParameter();");
            sb.AppendLine($"                {varName}.ParameterName = \"@{param.Name}\";");
            sb.AppendLine($"                {varName}.Value = (object?){paramName} ?? System.DBNull.Value;");
            sb.AppendLine($"                cmd.Parameters.Add({varName});");
        }

        // Execute reader
        sb.AppendLine();
        sb.AppendLine("                using var reader = cmd.ExecuteReader();");
        sb.AppendLine($"                var results = new System.Collections.Generic.List<{projection.Name}>();");
        sb.AppendLine("                while (reader.Read())");
        sb.AppendLine("                {");
        sb.AppendLine($"                    results.Add(new {projection.Name}");
        sb.AppendLine("                    {");

        // Map columns by ordinal
        for (int i = 0; i < projection.Columns.Count; i++)
        {
            var col = projection.Columns[i];
            string readerCall = GetReaderCall(col.Type, col.Ordinal);
            string comma = i < projection.Columns.Count - 1 ? "," : "";
            sb.AppendLine($"                        {col.Name} = {readerCall}{comma}");
        }

        sb.AppendLine("                    });");
        sb.AppendLine("                }");
        sb.AppendLine("                return results;");

        // Close try/finally
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine($"                if (weOpened) {connVar}.Close();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static string GetReaderCall(string csharpType, int ordinal)
    {
        // Handle nullable types
        bool isNullable = csharpType.EndsWith("?");
        string baseType = isNullable ? csharpType.TrimEnd('?') : csharpType;

        string getMethod = baseType switch
        {
            "int" => $"reader.GetInt32({ordinal})",
            "long" => $"reader.GetInt64({ordinal})",
            "short" => $"reader.GetInt16({ordinal})",
            "bool" => $"reader.GetBoolean({ordinal})",
            "decimal" => $"reader.GetDecimal({ordinal})",
            "double" => $"reader.GetDouble({ordinal})",
            "float" => $"reader.GetFloat({ordinal})",
            "string" => $"reader.GetString({ordinal})",
            "System.DateTime" => $"reader.GetDateTime({ordinal})",
            "System.Guid" => $"reader.GetGuid({ordinal})",
            "byte[]" => $"(byte[])reader.GetValue({ordinal})",
            _ => $"reader.GetValue({ordinal})"
        };

        if (isNullable)
        {
            return $"reader.IsDBNull({ordinal}) ? default : {getMethod}";
        }

        // String is a reference type — always needs null check
        if (csharpType == "string")
        {
            return $"reader.IsDBNull({ordinal}) ? null! : {getMethod}";
        }

        return getMethod;
    }

    public static string InferParameterType(string paramName, QueryModel query, ProjectionModel projection, DatabaseSchema? schema = null)
    {
        // 1. Try binding-based inference (col = @param parsed by ExtractParameterBindings)
        var paramRef = query.Parameters.FirstOrDefault(p => p.Name == paramName);
        if (paramRef != null && !string.IsNullOrEmpty(paramRef.BoundColumnName) && schema != null)
        {
            var resolved = ResolveColumnType(paramRef.BoundTableAlias, paramRef.BoundColumnName, query, schema);
            if (resolved != null)
                return resolved;
        }

        // 2. Fallback: match parameter name to a projection column name
        foreach (var col in projection.Columns)
        {
            if (col.Name.Equals(DialectMapper.ToPascalCase(paramName), StringComparison.OrdinalIgnoreCase))
            {
                return col.Type;
            }
        }

        return "object";
    }

    private static string? ResolveColumnType(string tableAlias, string columnName, QueryModel query, DatabaseSchema schema)
    {
        if (!string.IsNullOrEmpty(tableAlias))
        {
            // Qualified — resolve alias to table name
            string? tableName = ResolveAlias(tableAlias, query);
            if (tableName != null &&
                schema.Tables.TryGetValue(tableName, out var tableSchema) &&
                tableSchema.Columns.TryGetValue(columnName, out var colSchema))
            {
                return DialectMapper.MapDbTypeToCSharp(colSchema.DbType, colSchema.IsNullable);
            }
        }
        else
        {
            // Unqualified — search all referenced tables
            foreach (var table in query.Tables)
            {
                if (schema.Tables.TryGetValue(table.TableName, out var tableSchema) &&
                    tableSchema.Columns.TryGetValue(columnName, out var colSchema))
                {
                    return DialectMapper.MapDbTypeToCSharp(colSchema.DbType, colSchema.IsNullable);
                }
            }
        }

        return null;
    }

    private static string? ResolveAlias(string alias, QueryModel query)
    {
        foreach (var table in query.Tables)
        {
            string key = !string.IsNullOrEmpty(table.Alias) ? table.Alias : table.TableName;
            if (string.Equals(key, alias, StringComparison.OrdinalIgnoreCase))
                return table.TableName;
        }
        return null;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string EscapeVerbatimString(string s)
    {
        return s.Replace("\"", "\"\"");
    }
}
