using JauntyQ.SqlParser.IR;

namespace JauntyQ.Generator;

public static class CodeEmitter
{
    public static string Emit(QueryModel query, ProjectionModel projection, string originalSql)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Generate DTO class
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        EmitDto(sb, projection);
        sb.AppendLine();
        EmitQueryMethod(sb, query, projection, originalSql);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitDto(System.Text.StringBuilder sb, ProjectionModel projection)
    {
        sb.AppendLine($"    public class {projection.Name}");
        sb.AppendLine("    {");
        foreach (var col in projection.Columns)
        {
            sb.AppendLine($"        public {col.Type} {col.Name} {{ get; set; }}");
        }
        sb.AppendLine("    }");
    }

    private static void EmitQueryMethod(
        System.Text.StringBuilder sb,
        QueryModel query,
        ProjectionModel projection,
        string originalSql)
    {
        sb.AppendLine("    public static partial class Queries");
        sb.AppendLine("    {");

        // Method signature
        var paramList = new System.Text.StringBuilder();
        paramList.Append("System.Data.Common.DbConnection conn");
        foreach (var param in query.Parameters)
        {
            string paramType = InferParameterType(param.Name, query, projection);
            string paramName = ToCamelCase(param.Name);
            paramList.Append($", {paramType} {paramName}");
        }

        sb.AppendLine($"        public static System.Collections.Generic.List<{projection.Name}> {query.Name}({paramList})");
        sb.AppendLine("        {");

        // Create command
        sb.AppendLine("            using var cmd = conn.CreateCommand();");
        sb.AppendLine($"            cmd.CommandText = @\"{EscapeVerbatimString(originalSql.Trim())}\";");

        // Bind parameters
        for (int i = 0; i < query.Parameters.Count; i++)
        {
            var param = query.Parameters[i];
            string varName = $"p{i}";
            string paramName = ToCamelCase(param.Name);
            sb.AppendLine();
            sb.AppendLine($"            var {varName} = cmd.CreateParameter();");
            sb.AppendLine($"            {varName}.ParameterName = \"@{param.Name}\";");
            sb.AppendLine($"            {varName}.Value = (object?){paramName} ?? System.DBNull.Value;");
            sb.AppendLine($"            cmd.Parameters.Add({varName});");
        }

        // Execute reader
        sb.AppendLine();
        sb.AppendLine("            if (conn.State != System.Data.ConnectionState.Open)");
        sb.AppendLine("                conn.Open();");
        sb.AppendLine();
        sb.AppendLine("            using var reader = cmd.ExecuteReader();");
        sb.AppendLine($"            var results = new System.Collections.Generic.List<{projection.Name}>();");
        sb.AppendLine("            while (reader.Read())");
        sb.AppendLine("            {");
        sb.AppendLine($"                results.Add(new {projection.Name}");
        sb.AppendLine("                {");

        // Map columns by ordinal
        for (int i = 0; i < projection.Columns.Count; i++)
        {
            var col = projection.Columns[i];
            string readerCall = GetReaderCall(col.Type, col.Ordinal);
            string comma = i < projection.Columns.Count - 1 ? "," : "";
            sb.AppendLine($"                    {col.Name} = {readerCall}{comma}");
        }

        sb.AppendLine("                });");
        sb.AppendLine("            }");
        sb.AppendLine("            return results;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static string GetReaderCall(string csharpType, int ordinal)
    {
        // Handle nullable types
        bool isNullable = csharpType.EndsWith("?");
        string baseType = isNullable ? csharpType.TrimEnd('?') : csharpType;

        string getMethod = baseType switch
        {
            "int" => $"reader.GetInt32({ordinal})",
            "long" => $"reader.GetInt64({ordinal})",
            "short" => $"reader.GetInt16({ordinal})",
            "bool" => $"reader.GetBoolean({ordinal})",
            "decimal" => $"reader.GetDecimal({ordinal})",
            "double" => $"reader.GetDouble({ordinal})",
            "float" => $"reader.GetFloat({ordinal})",
            "string" => $"reader.GetString({ordinal})",
            "System.DateTime" => $"reader.GetDateTime({ordinal})",
            "System.Guid" => $"reader.GetGuid({ordinal})",
            "byte[]" => $"(byte[])reader.GetValue({ordinal})",
            _ => $"reader.GetValue({ordinal})"
        };

        if (isNullable)
        {
            return $"reader.IsDBNull({ordinal}) ? default : {getMethod}";
        }

        // String is a reference type — always needs null check
        if (csharpType == "string")
        {
            return $"reader.IsDBNull({ordinal}) ? null! : {getMethod}";
        }

        return getMethod;
    }

    public static string InferParameterType(string paramName, QueryModel query, ProjectionModel projection)
    {
        // Try to find the parameter's type from the projection columns
        // (when the param is used in WHERE col = @param, the col type is the param type)
        // For now, default to object — the generator will refine this later
        // A simple heuristic: look for columns with similar names
        foreach (var col in projection.Columns)
        {
            if (col.Name.Equals(DialectMapper.ToPascalCase(paramName), StringComparison.OrdinalIgnoreCase))
            {
                return col.Type;
            }
        }

        // Default to object for now
        return "object";
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string EscapeVerbatimString(string s)
    {
        return s.Replace("\"", "\"\"");
    }
}
