using JauntyQ.Schema;
using JauntyQ.SqlParser.IR;

namespace JauntyQ.Generator;
public static partial class CodeEmitter
{
    /// <summary>
    /// POCO-taking overloads for the synthetic write methods:
    /// Update(product), Insert(shipper) (with identity write-back),
    /// Delete(product), Upsert(customer). Emitted only when the scalar
    /// method is the synthetic one - a user override owns its own signature.
    /// </summary>
    public static string EmitPocoOverloads(
        string entityName,
        string rowType,
        TableSchema tableSchema,
        string dialect,
        bool hasInsert,
        bool hasUpdate,
        bool hasDelete,
        bool hasUpsert)
    {
        var columns = new System.Collections.Generic.List<ColumnSchema>(tableSchema.Columns.Values);
        var versionCols = columns.FindAll(c => c.IsRowVersion);
        var pkCols = columns.FindAll(c => c.IsPrimaryKey);
        var setCols = columns.FindAll(c => !c.IsPrimaryKey && !c.IsRowVersion);
        var insertCols = columns.FindAll(c => !c.IsIdentity && !c.IsRowVersion);
        ColumnSchema? identityCol = null;
        foreach (var c in columns)
        {
            if (c.IsIdentity) { identityCol = identityCol == null ? c : null; if (identityCol == null) break; }
        }
        bool insertReturnsId = identityCol != null && !string.IsNullOrEmpty(dialect);

        string Args(System.Collections.Generic.List<ColumnSchema> cols)
            => string.Join(", ", cols.Select(c => $"row.{IdentifierGuard.Escape(DialectMapper.ToPascalCase(c.Name))}"));

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        void Forward(string method, System.Collections.Generic.List<ColumnSchema> cols)
        {
            string args = Args(cols);
            sb.AppendLine($"        public int {method}({rowType} row) => {method}({args});");
            sb.AppendLine($"        public static int {method}(System.Data.Common.DbConnection conn, {rowType} row) => {method}(conn, {args});");
            sb.AppendLine($"        public System.Threading.Tasks.Task<int> {method}Async({rowType} row, System.Threading.CancellationToken cancellationToken = default) => {method}Async({args}, cancellationToken);");
            sb.AppendLine($"        public static System.Threading.Tasks.Task<int> {method}Async(System.Data.Common.DbConnection conn, {rowType} row, System.Threading.CancellationToken cancellationToken = default) => {method}Async(conn, {args}, cancellationToken);");
            sb.AppendLine();
        }

        if (hasInsert && insertCols.Count > 0)
        {
            if (insertReturnsId)
            {
                string idProp = IdentifierGuard.Escape(DialectMapper.ToPascalCase(identityCol!.Name));
                string idType = DialectMapper.MapDbTypeToCSharp(identityCol.DbType, isNullable: false);
                string args = Args(insertCols);
                sb.AppendLine($"        /// <summary>Inserts the row and writes the database-assigned {idProp} back onto it.</summary>");
                sb.AppendLine($"        public {idType} Insert({rowType} row)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = Insert({args});");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public static {idType} Insert(System.Data.Common.DbConnection conn, {rowType} row)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = Insert(conn, {args});");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public async System.Threading.Tasks.Task<{idType}> InsertAsync({rowType} row, System.Threading.CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = await InsertAsync({args}, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public static async System.Threading.Tasks.Task<{idType}> InsertAsync(System.Data.Common.DbConnection conn, {rowType} row, System.Threading.CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = await InsertAsync(conn, {args}, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            else
            {
                Forward("Insert", insertCols);
            }
        }

        if (hasUpdate && setCols.Count > 0 && pkCols.Count > 0)
        {
            // scalar Update parameter order: SET columns then PK columns
            var updateArgsCols = new System.Collections.Generic.List<ColumnSchema>(setCols);
            updateArgsCols.AddRange(pkCols);
            updateArgsCols.AddRange(versionCols);
            Forward("Update", updateArgsCols);
        }

        if (hasDelete && pkCols.Count > 0)
        {
            var deleteArgsCols = new System.Collections.Generic.List<ColumnSchema>(pkCols);
            deleteArgsCols.AddRange(versionCols);
            Forward("Delete", deleteArgsCols);
        }

        if (hasUpsert)
        {
            Forward("Upsert", columns.FindAll(c => !c.IsRowVersion));
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDto(System.Text.StringBuilder sb, ProjectionModel projection)
    {
        sb.AppendLine($"            public class {projection.Name}");
        sb.AppendLine("            {");
        foreach (var col in projection.Columns)
        {
            // `required` keeps non-nullable reference properties honest (no CS8618)
            // and costs nothing: generated mapping always sets every property.
            sb.AppendLine($"                public required {col.Type} {IdentifierGuard.Escape(col.Name)} {{ get; set; }}");
        }
        sb.AppendLine("            }");
    }

}
