using JauntyQ.Schema;
using JauntyQ.SqlParser.IR;

namespace JauntyQ.Generator;

public static class CodeEmitter
{
    public static string Emit(QueryModel query, ProjectionModel projection, string originalSql, string entityName, DatabaseSchema? schema = null, Directives.DirectiveModel? directives = null, string? canonicalRowType = null)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");

        // Entity partial class containing nested Result class and query methods
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        // Full-row projections return the canonical per-table POCO (e.g.
        // Shipper) instead of a query-specific nested Result type; only
        // genuine custom projections (joins, partial selects) get their own.
        if (canonicalRowType == null)
        {
            sb.AppendLine("        public static partial class Result");
            sb.AppendLine("        {");
            EmitDto(sb, projection);
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // Expected result-set column names for the one-time shape guard
        EmitColumnNames(sb, query.Name, projection);
        sb.AppendLine();

        // Resolve proc name (null if not in proc mode)
        string? procName = ResolveProcName(directives, entityName, query.Name);

        bool isFirst = directives?.IsFirst == true;
        bool isStream = directives?.IsStream == true;

        // Query methods (use Result.X as the type)
        EmitQueryMethods(sb, query, projection, originalSql, entityName, schema, directives, procName, isFirst, canonicalRowType, isStream);

        // Emit Proc nested class with CREATE PROCEDURE script
        if (procName != null)
        {
            sb.AppendLine();
            EmitProcScript(sb, procName, query.Name, originalSql, query, projection, schema, directives, isCrud: false);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitCrud(QueryModel query, string originalSql, string entityName, DatabaseSchema? schema = null, Directives.DirectiveModel? directives = null)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");

        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        // Build parameter lists
        var paramInfos = new System.Collections.Generic.List<EmittedParam>();
        foreach (var param in query.Parameters)
        {
            string paramType = InferCrudParameterType(param, query, schema, directives);
            bool isNullable = IsBoundColumnNullable(param, query, schema);
            var column = ResolveBoundColumn(param, query, schema, out string? boundTable);
            paramInfos.Add(CreateEmittedParam(param.Name, paramType, isNullable, column, boundTable, param.IsWriteTarget));
        }

        // Resolve proc name (null if not in proc mode)
        string? procName = ResolveProcName(directives, entityName, query.Name);

        // -- @identity: resolve the single identity key column of the target
        // table (the generator validates preconditions and reports JNT7001;
        // by the time we emit, this either resolves or the file was skipped).
        IdentityInfo? identity = ResolveIdentityInfo(query, schema, directives);

        // Instance sync
        EmitCrudMethodBody(sb, query, originalSql, paramInfos, "_conn", isStatic: false, isAsync: false, procName: procName, identity: identity, dialect: schema?.Dialect);
        sb.AppendLine();
        // Static sync
        EmitCrudMethodBody(sb, query, originalSql, paramInfos, "conn", isStatic: true, isAsync: false, procName: procName, identity: identity, dialect: schema?.Dialect);
        sb.AppendLine();
        // Instance async
        EmitCrudMethodBody(sb, query, originalSql, paramInfos, "_conn", isStatic: false, isAsync: true, procName: procName, identity: identity, dialect: schema?.Dialect);
        sb.AppendLine();
        // Static async
        EmitCrudMethodBody(sb, query, originalSql, paramInfos, "conn", isStatic: true, isAsync: true, procName: procName, identity: identity, dialect: schema?.Dialect);

        // Emit Proc nested class with CREATE PROCEDURE script
        if (procName != null)
        {
            sb.AppendLine();
            EmitProcScript(sb, procName, query.Name, originalSql, query, null, schema, directives, isCrud: true);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Source for the shared one-time result-set shape guard. Registered by the
    /// generator as post-initialization output so it exists exactly once.
    /// </summary>
    public static string EmitShapeGuardSource()
    {
        return """
// <auto-generated/>
#nullable enable

namespace JauntyQ.Generated
{
    /// <summary>
    /// Validates the result-set shape against the schema snapshot. The caller
    /// latches this so it runs on the first execution of each query per process
    /// and never again (never per row, never per subsequent call). Catches drift
    /// between the live database and the snapshot instead of silently mapping
    /// wrong ordinals.
    /// </summary>
    public static class JauntyQShapeGuard
    {
        public static void Validate(System.Data.Common.DbDataReader reader, string[] expectedColumns, string queryId)
        {
            if (reader.FieldCount < expectedColumns.Length)
            {
                throw new System.InvalidOperationException(
                    $"JauntyQ schema drift in {queryId}: expected {expectedColumns.Length} columns but the result set has {reader.FieldCount}. " +
                    "The database no longer matches the schema snapshot; re-run 'jaunty schema pull' and rebuild.");
            }

            for (int i = 0; i < expectedColumns.Length; i++)
            {
                string actual = reader.GetName(i);
                if (!string.Equals(actual, expectedColumns[i], System.StringComparison.OrdinalIgnoreCase))
                {
                    throw new System.InvalidOperationException(
                        $"JauntyQ schema drift in {queryId}: expected column '{expectedColumns[i]}' at ordinal {i} but the result set returned '{actual}'. " +
                        "The database no longer matches the schema snapshot; re-run 'jaunty schema pull' and rebuild.");
                }
            }
        }
    }
}
""";
    }

    private readonly struct EmittedParam
    {
        public readonly string Name;
        public readonly string CSharpType;
        public readonly bool IsNullable;
        public readonly int? MaxLength;       // chars for text, bytes for binary; -1 = unbounded (MAX)
        public readonly int? Precision;
        public readonly int? Scale;
        public readonly bool IsWriteTarget;   // INSERT value / UPDATE SET / upsert column
        public readonly string? ColumnDisplay; // "table.column" for guard messages

        public EmittedParam(string name, string csharpType, bool isNullable = false,
            int? maxLength = null, int? precision = null, int? scale = null,
            bool isWriteTarget = false, string? columnDisplay = null)
        {
            Name = name;
            CSharpType = csharpType;
            IsNullable = isNullable;
            MaxLength = maxLength;
            Precision = precision;
            Scale = scale;
            IsWriteTarget = isWriteTarget;
            ColumnDisplay = columnDisplay;
        }
    }

    /// <summary>
    /// Resolves the schema column a parameter is bound to (CRUD target table
    /// first, then alias-qualified, then unique unqualified match).
    /// </summary>
    private static ColumnSchema? ResolveBoundColumn(ParameterRef param, QueryModel query, DatabaseSchema? schema, out string? tableName)
    {
        tableName = null;
        if (schema == null || string.IsNullOrEmpty(param.BoundColumnName))
            return null;

        if (query.TargetTable != null &&
            schema.Tables.TryGetValue(query.TargetTable, out var target) &&
            target.Columns.TryGetValue(param.BoundColumnName, out var targetCol))
        {
            tableName = query.TargetTable;
            return targetCol;
        }

        if (!string.IsNullOrEmpty(param.BoundTableAlias))
        {
            string? resolved = ResolveAlias(param.BoundTableAlias, query);
            if (resolved != null &&
                schema.Tables.TryGetValue(resolved, out var aliased) &&
                aliased.Columns.TryGetValue(param.BoundColumnName, out var aliasedCol))
            {
                tableName = resolved;
                return aliasedCol;
            }
            return null;
        }

        foreach (var table in query.Tables)
        {
            if (schema.Tables.TryGetValue(table.TableName, out var tableSchema) &&
                tableSchema.Columns.TryGetValue(param.BoundColumnName, out var col))
            {
                tableName = table.TableName;
                return col;
            }
        }
        return null;
    }

    private static EmittedParam CreateEmittedParam(string name, string csharpType, bool isNullable,
        ColumnSchema? column, string? tableName, bool isWriteTarget)
    {
        if (column == null)
            return new EmittedParam(name, csharpType, isNullable);
        return new EmittedParam(name, csharpType, isNullable,
            column.MaxLength, column.Precision, column.Scale, isWriteTarget,
            tableName != null ? $"{tableName}.{column.Name}" : column.Name);
    }

    /// <summary>
    /// Client-side length guards for write parameters. Fails fast with the
    /// exact column and limit instead of a server round-trip ending in a
    /// truncation error; also what makes the fixed DbParameter.Size safe
    /// (ADO.NET providers silently truncate oversize values to Size).
    /// </summary>
    private static void EmitValueGuards(System.Text.StringBuilder sb, System.Collections.Generic.List<EmittedParam> paramInfos)
    {
        bool any = false;
        foreach (var param in paramInfos)
        {
            if (!param.IsWriteTarget || param.MaxLength is not int max || max <= 0)
                continue;
            bool isText = param.CSharpType is "string" or "string?";
            bool isBinary = param.CSharpType is "byte[]" or "byte[]?";
            if (!isText && !isBinary)
                continue;
            string unit = isText ? "characters" : "bytes";
            string condition = param.CSharpType is "string" or "byte[]"
                ? $"{param.Name}.Length > {max}"
                : $"{param.Name} != null && {param.Name}.Length > {max}";
            sb.AppendLine($"            if ({condition})");
            sb.AppendLine($"                throw new System.ArgumentException($\"Value ({{{param.Name}.Length}} {unit}) exceeds {param.ColumnDisplay} max length ({max}).\", nameof({param.Name}));");
            any = true;
        }
        if (any)
            sb.AppendLine();
    }

    /// <summary>
    /// DbParameter.Size / Precision / Scale from the schema snapshot.
    /// Fixed Size keeps the server plan cache to one plan per query instead
    /// of one per distinct value length. Write parameters are guarded above,
    /// so the fixed Size can never truncate; comparison parameters size
    /// dynamically because a truncated key could match the wrong row.
    /// </summary>
    private static void EmitParameterSizing(System.Text.StringBuilder sb, EmittedParam param, string varName)
    {
        bool isText = param.CSharpType is "string" or "string?";
        bool isBinary = param.CSharpType is "byte[]" or "byte[]?";
        if ((isText || isBinary) && param.MaxLength is int max)
        {
            if (max < 0)
            {
                sb.AppendLine($"                {varName}.Size = -1;");
            }
            else if (param.IsWriteTarget)
            {
                sb.AppendLine($"                {varName}.Size = {max};");
            }
            else
            {
                string sizeExpr = param.CSharpType is "string" or "byte[]"
                    ? $"{param.Name}.Length > {max} ? {param.Name}.Length : {max}"
                    : $"{param.Name} == null ? {max} : ({param.Name}.Length > {max} ? {param.Name}.Length : {max})";
                sb.AppendLine($"                {varName}.Size = {sizeExpr};");
            }
        }

        if (param.CSharpType is "decimal" or "decimal?" && param.Precision is int precision && precision > 0)
        {
            sb.AppendLine($"                {varName}.Precision = {precision};");
            sb.AppendLine($"                {varName}.Scale = {param.Scale ?? 0};");
        }
    }

    private static void EmitColumnNames(System.Text.StringBuilder sb, string methodName, ProjectionModel projection)
    {
        sb.Append($"        private static readonly string[] __{methodName}Columns = {{ ");
        for (int i = 0; i < projection.Columns.Count; i++)
        {
            var col = projection.Columns[i];
            string sourceName = string.IsNullOrEmpty(col.SourceName) ? col.Name : col.SourceName;
            if (i > 0) sb.Append(", ");
            // JNT2004 (C3): sourceName comes from a SQL alias/column and is
            // embedded in a regular string literal; encode it so a quote or
            // backslash cannot break out of the literal.
            sb.Append($"\"{IdentifierGuard.ToStringLiteral(sourceName)}\"");
        }
        sb.AppendLine(" };");
        // One-time shape-guard latch (0 = not yet validated). The guard runs on
        // the first execution of this query per process and never again, so the
        // per-row-free drift check is also per-query-once, as documented.
        sb.AppendLine($"        private static int __{methodName}Validated;");
    }

    private static void EmitCrudMethodBody(
        System.Text.StringBuilder sb,
        QueryModel query,
        string originalSql,
        System.Collections.Generic.List<EmittedParam> paramInfos,
        string connVar,
        bool isStatic,
        bool isAsync,
        string? procName = null,
        IdentityInfo? identity = null,
        string? dialect = null)
    {
        string modifier = isStatic ? "public static" : "public";
        string asyncModifier = isAsync ? " async" : "";
        string syncReturn = identity != null ? identity.Value.CSharpType : "int";
        string returnType = isAsync ? $"System.Threading.Tasks.Task<{syncReturn}>" : syncReturn;
        string methodName = isAsync ? $"{query.Name}Async" : query.Name;
        string paramList = BuildParamList(paramInfos, isStatic, isAsync, trailingNullableDefaults: true);

        sb.AppendLine($"        {modifier}{asyncModifier} {returnType} {methodName}({paramList})");
        sb.AppendLine("        {");

        EmitValueGuards(sb, paramInfos);

        // Connection lifecycle
        sb.AppendLine($"            bool weOpened = {connVar}.State != System.Data.ConnectionState.Open;");
        sb.AppendLine(isAsync
            ? $"            if (weOpened) await {connVar}.OpenAsync(cancellationToken).ConfigureAwait(false);"
            : $"            if (weOpened) {connVar}.Open();");
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        // Create command
        sb.AppendLine($"                using var cmd = {connVar}.CreateCommand();");
        if (!isStatic)
        {
            sb.AppendLine("                if (_db?.CurrentTransaction != null) cmd.Transaction = _db.CurrentTransaction;");
        }
        if (procName != null)
        {
            sb.AppendLine($"                cmd.CommandText = \"{procName}\";");
            sb.AppendLine("                cmd.CommandType = System.Data.CommandType.StoredProcedure;");
        }
        else if (identity != null)
        {
            string identitySql = BuildIdentityInsertSql(
                StripLeadingSqlComments(originalSql), identity.Value.Dialect, identity.Value.ColumnName);
            sb.AppendLine($"                cmd.CommandText = @\"{EscapeVerbatimString(identitySql)}\";");
        }
        else
        {
            sb.AppendLine($"                cmd.CommandText = @\"{EscapeVerbatimString(StripLeadingSqlComments(originalSql))}\";");
        }

        EmitParameterBinding(sb, paramInfos, dialect);

        // Execute
        sb.AppendLine();
        if (identity != null)
        {
            string behavior = "System.Data.CommandBehavior.SingleRow | System.Data.CommandBehavior.SingleResult";
            sb.AppendLine(isAsync
                ? $"                using var reader = await cmd.ExecuteReaderAsync({behavior}, cancellationToken).ConfigureAwait(false);"
                : $"                using var reader = cmd.ExecuteReader({behavior});");
            string readCall = isAsync
                ? "await reader.ReadAsync(cancellationToken).ConfigureAwait(false)"
                : "reader.Read()";
            sb.AppendLine($"                if (!({readCall}))");
            sb.AppendLine("                    throw new System.InvalidOperationException(\"INSERT did not return an identity value.\");");
            sb.AppendLine($"                return {GetIdentityReaderCall(identity.Value)};");
        }
        else
        {
            sb.AppendLine(isAsync
                ? "                return await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);"
                : "                return cmd.ExecuteNonQuery();");
        }

        EmitFinallyClose(sb, connVar, isAsync);
        sb.AppendLine("        }");
    }

    private static string BuildParamList(System.Collections.Generic.List<EmittedParam> paramInfos, bool isStatic, bool isAsync, bool trailingNullableDefaults = false, bool enumeratorCancellation = false)
    {
        // C# optional parameters must be trailing: give `= default` to the
        // longest suffix of nullable-column parameters so callers pass only
        // what the schema actually requires.
        int firstDefault = paramInfos.Count;
        if (trailingNullableDefaults)
        {
            while (firstDefault > 0 && paramInfos[firstDefault - 1].IsNullable)
                firstDefault--;
        }

        var sb = new System.Text.StringBuilder();
        if (isStatic)
            sb.Append("System.Data.Common.DbConnection conn");

        for (int i = 0; i < paramInfos.Count; i++)
        {
            var p = paramInfos[i];
            if (sb.Length > 0) sb.Append(", ");
            sb.Append($"{p.CSharpType} {p.Name}");
            if (i >= firstDefault) sb.Append(" = default");
        }

        if (isAsync)
        {
            if (sb.Length > 0) sb.Append(", ");
            // Async streaming iterators annotate the token so the framework can
            // flow a token supplied via await foreach (...).WithCancellation(ct).
            if (enumeratorCancellation)
                sb.Append("[System.Runtime.CompilerServices.EnumeratorCancellation] ");
            sb.Append("System.Threading.CancellationToken cancellationToken = default");
        }

        return sb.ToString();
    }

    private static void EmitParameterBinding(System.Text.StringBuilder sb, System.Collections.Generic.List<EmittedParam> paramInfos, string? dialect = null)
    {
        for (int i = 0; i < paramInfos.Count; i++)
        {
            var param = paramInfos[i];
            string varName = $"p{i}";
            sb.AppendLine();

            // PostgreSQL: NpgsqlParameter<T>.TypedValue keeps the value
            // strongly typed end to end - no object boxing at the ADO.NET
            // boundary, and Npgsql infers the exact wire type from T (no
            // DbType). PostgreSQL parameter typing is OID-based, so the
            // per-length plan-cache concern does not apply and Size is not
            // emitted; the client-side write guards still run.
            if (string.Equals(dialect, "postgres", StringComparison.OrdinalIgnoreCase))
            {
                sb.AppendLine($"                var {varName} = new global::Npgsql.NpgsqlParameter<{param.CSharpType}> {{ ParameterName = \"@{param.Name}\", TypedValue = {param.Name} }};");
                sb.AppendLine($"                cmd.Parameters.Add({varName});");
                continue;
            }

            sb.AppendLine($"                var {varName} = cmd.CreateParameter();");
            sb.AppendLine($"                {varName}.ParameterName = \"@{param.Name}\";");
            string? adoDbType = MapCSharpTypeToAdoDbType(param.CSharpType);
            if (adoDbType != null)
            {
                sb.AppendLine($"                {varName}.DbType = System.Data.DbType.{adoDbType};");
            }
            EmitParameterSizing(sb, param, varName);
            // DbParameter.Value is object, so value types box exactly once per
            // call here - an ADO.NET boundary cost every library pays. For
            // non-nullable value types the DBNull coalesce is dead code, so
            // emit a plain assignment; the (object?) dance is only needed
            // where null is actually possible.
            if (IsNonNullableValueType(param.CSharpType))
            {
                sb.AppendLine($"                {varName}.Value = {param.Name};");
            }
            else
            {
                sb.AppendLine($"                {varName}.Value = (object?){param.Name} ?? System.DBNull.Value;");
            }
            sb.AppendLine($"                cmd.Parameters.Add({varName});");
        }
    }

    internal readonly struct IdentityInfo
    {
        public readonly string ColumnName;
        public readonly string CSharpType;
        public readonly string Dialect;

        public IdentityInfo(string columnName, string csharpType, string dialect)
        {
            ColumnName = columnName;
            CSharpType = csharpType;
            Dialect = dialect;
        }
    }

    /// <summary>
    /// Resolves the single identity key column for an -- @identity INSERT.
    /// Returns null when preconditions are not met (the generator reports
    /// JNT7001 for user files before emission; synthetics only carry the
    /// directive when resolvable).
    /// </summary>
    internal static IdentityInfo? ResolveIdentityInfo(QueryModel query, DatabaseSchema? schema, Directives.DirectiveModel? directives)
    {
        if (directives?.ReturnsIdentity != true || schema == null || string.IsNullOrEmpty(schema.Dialect))
            return null;
        if (query.StatementType != StatementType.Insert || query.TargetTable == null)
            return null;
        if (!schema.Tables.TryGetValue(query.TargetTable, out var tableSchema))
            return null;

        ColumnSchema? identityCol = null;
        foreach (var col in tableSchema.Columns.Values)
        {
            if (!col.IsIdentity)
                continue;
            if (identityCol != null)
                return null; // multiple identity columns: unsupported
            identityCol = col;
        }
        if (identityCol == null)
            return null;

        string csharpType = DialectMapper.MapDbTypeToCSharp(identityCol.DbType, isNullable: false);
        return new IdentityInfo(identityCol.Name, csharpType, schema.Dialect);
    }

    /// <summary>
    /// Rewrites a plain INSERT so it returns the database-assigned identity:
    /// OUTPUT INSERTED.x (SQL Server, before VALUES), RETURNING x
    /// (PostgreSQL/SQLite), or a trailing SELECT LAST_INSERT_ID() (MySQL).
    /// </summary>
    internal static string BuildIdentityInsertSql(string sql, string dialect, string identityColumn)
    {
        string trimmed = sql.TrimEnd();
        while (trimmed.EndsWith(";"))
            trimmed = trimmed.Substring(0, trimmed.Length - 1).TrimEnd();

        switch (dialect)
        {
            case "sqlserver":
            {
                int idx = FindValuesKeyword(trimmed);
                if (idx < 0)
                    return trimmed; // generator validated the shape; defensive only
                return trimmed.Substring(0, idx) + $"output inserted.{identityColumn}\n" + trimmed.Substring(idx);
            }
            case "postgres":
            case "sqlite":
                return trimmed + $"\nreturning {identityColumn}";
            case "mysql":
                return trimmed + ";\nselect last_insert_id()";
            default:
                return trimmed;
        }
    }

    private static int FindValuesKeyword(string sql)
    {
        for (int i = 0; i + 6 <= sql.Length; i++)
        {
            if (string.Compare(sql, i, "values", 0, 6, StringComparison.OrdinalIgnoreCase) != 0)
                continue;
            bool startOk = i == 0 || !char.IsLetterOrDigit(sql[i - 1]) && sql[i - 1] != '_' && sql[i - 1] != '@';
            bool endOk = i + 6 == sql.Length || !char.IsLetterOrDigit(sql[i + 6]) && sql[i + 6] != '_';
            if (startOk && endOk)
                return i;
        }
        return -1;
    }

    private static string GetIdentityReaderCall(IdentityInfo identity)
    {
        // MySQL's LAST_INSERT_ID() is BIGINT UNSIGNED regardless of the key
        // type; read as long and narrow explicitly.
        if (identity.Dialect == "mysql" && identity.CSharpType != "long")
            return $"checked(({identity.CSharpType})reader.GetInt64(0))";
        return GetReaderCall(identity.CSharpType, 0);
    }

    private static void EmitFinallyClose(System.Text.StringBuilder sb, string connVar, bool isAsync)
    {
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine(isAsync
            ? $"                if (weOpened) await {connVar}.CloseAsync().ConfigureAwait(false);"
            : $"                if (weOpened) {connVar}.Close();");
        sb.AppendLine("            }");
    }

    private static bool IsNonNullableValueType(string csharpType) => csharpType switch
    {
        "int" or "long" or "short" or "bool" or "decimal" or "double" or "float"
            or "System.DateTime" or "System.TimeSpan" or "System.Guid" => true,
        _ => false
    };

    /// <summary>
    /// Maps an emitted C# parameter type to System.Data.DbType so providers skip
    /// runtime type inference. Returns null when no static mapping exists.
    /// </summary>
    private static string? MapCSharpTypeToAdoDbType(string csharpType)
    {
        string baseType = csharpType.EndsWith("?") ? csharpType.Substring(0, csharpType.Length - 1) : csharpType;
        return baseType switch
        {
            "int" => "Int32",
            "long" => "Int64",
            "short" => "Int16",
            "bool" => "Boolean",
            "decimal" => "Decimal",
            "double" => "Double",
            "float" => "Single",
            "string" => "String",
            "System.DateTime" => "DateTime",
            "System.TimeSpan" => "Time",
            "System.Guid" => "Guid",
            "byte[]" => "Binary",
            _ => null
        };
    }

    private static bool IsBoundColumnNullable(ParameterRef param, QueryModel query, DatabaseSchema? schema)
    {
        if (schema == null || string.IsNullOrEmpty(param.BoundColumnName) || query.TargetTable == null)
            return false;
        return schema.Tables.TryGetValue(query.TargetTable, out var tableSchema)
            && tableSchema.Columns.TryGetValue(param.BoundColumnName, out var col)
            && col.IsNullable;
    }

    internal static string InferCrudParameterType(ParameterRef param, QueryModel query, DatabaseSchema? schema, Directives.DirectiveModel? directives = null)
    {
        // Check @params directive first
        if (directives?.ExplicitParams != null)
        {
            foreach (var ep in directives.ExplicitParams)
            {
                if (string.Equals(ep.Name, param.Name, StringComparison.OrdinalIgnoreCase))
                    return ep.CSharpType;
            }
        }

        if (!string.IsNullOrEmpty(param.BoundColumnName) && schema != null)
        {
            // For CRUD, the target table is the primary table
            string? targetTable = query.TargetTable;
            if (targetTable != null && schema.Tables.TryGetValue(targetTable, out var tableSchema))
            {
                if (tableSchema.Columns.TryGetValue(param.BoundColumnName, out var colSchema))
                {
                    return DialectMapper.MapColumnToCSharp(colSchema);
                }
            }

            // Fallback: try alias-based resolution
            var resolved = ResolveColumnType(param.BoundTableAlias, param.BoundColumnName, query, schema);
            if (resolved != null)
                return resolved;
        }

        return "object";
    }

    public static string EmitEntityCore(string entityName)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly System.Data.Common.DbConnection _conn;");
        sb.AppendLine("        private readonly JauntyDb? _db;");
        sb.AppendLine();
        sb.AppendLine($"        internal {entityName}(System.Data.Common.DbConnection conn) => _conn = conn;");
        sb.AppendLine();
        sb.AppendLine($"        internal {entityName}(JauntyDb db)");
        sb.AppendLine("        {");
        sb.AppendLine("            _db = db;");
        sb.AppendLine("            _conn = db.Connection;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitJauntyDb(System.Collections.Generic.IEnumerable<string> entityNames)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public class JauntyDb");
        sb.AppendLine("    {");
        sb.AppendLine("""
        private readonly System.Data.Common.DbConnection _conn;
        private System.Data.Common.DbTransaction? _tx;
        private bool _txOpenedConnection;

        public JauntyDb(System.Data.Common.DbConnection conn) => _conn = conn;

        internal System.Data.Common.DbConnection Connection => _conn;
        internal System.Data.Common.DbTransaction? CurrentTransaction => _tx;

        /// <summary>
        /// Opens the connection if needed and starts a transaction. Every
        /// db.* call automatically enlists until Commit/Rollback/Dispose;
        /// if the connection was opened here it is closed when the
        /// transaction ends. Dispose without Commit rolls back.
        /// </summary>
        public Transaction BeginTransaction()
        {
            if (_tx != null)
                throw new System.InvalidOperationException("A JauntyDb transaction is already active.");
            _txOpenedConnection = _conn.State != System.Data.ConnectionState.Open;
            if (_txOpenedConnection) _conn.Open();
            _tx = _conn.BeginTransaction();
            return new Transaction(this, _tx);
        }

        public async System.Threading.Tasks.Task<Transaction> BeginTransactionAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            if (_tx != null)
                throw new System.InvalidOperationException("A JauntyDb transaction is already active.");
            _txOpenedConnection = _conn.State != System.Data.ConnectionState.Open;
            if (_txOpenedConnection) await _conn.OpenAsync(cancellationToken).ConfigureAwait(false);
            _tx = await _conn.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
            return new Transaction(this, _tx);
        }

        private void EndTransaction()
        {
            _tx = null;
            if (_txOpenedConnection && _conn.State != System.Data.ConnectionState.Closed)
                _conn.Close();
            _txOpenedConnection = false;
        }

        public sealed class Transaction : System.IDisposable
        {
            private readonly JauntyDb _db;
            private System.Data.Common.DbTransaction? _inner;

            internal Transaction(JauntyDb db, System.Data.Common.DbTransaction inner)
            {
                _db = db;
                _inner = inner;
            }

            public void Commit()
            {
                if (_inner == null)
                    throw new System.InvalidOperationException("Transaction already completed.");
                _inner.Commit();
                End();
            }

            public void Rollback()
            {
                if (_inner == null)
                    throw new System.InvalidOperationException("Transaction already completed.");
                _inner.Rollback();
                End();
            }

            public void Dispose()
            {
                if (_inner == null) return;
                End(); // disposing an uncommitted DbTransaction rolls back
            }

            private void End()
            {
                _inner!.Dispose();
                _inner = null;
                _db.EndTransaction();
            }
        }
""");

        foreach (var entity in entityNames)
        {
            string fieldName = "_" + ToCamelCase(entity);
            sb.AppendLine();
            sb.AppendLine($"        private {entity}? {fieldName};");
            sb.AppendLine($"        public {entity} {entity} => {fieldName} ??= new {entity}(this);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Canonical per-table row POCO (e.g. Shipper for table Shippers).
    /// Property order mirrors the table's column order, matching the
    /// ordinals every full-row query reads.
    /// </summary>
    public static string EmitRowPoco(string rowTypeName, TableSchema tableSchema)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public class {rowTypeName}");
        sb.AppendLine("    {");
        foreach (var col in tableSchema.Columns.Values)
        {
            string csharpType = DialectMapper.MapColumnToCSharp(col);
            // `required` only where CS8618 applies (non-nullable reference
            // types); value types stay optional so POCO-based Insert doesn't
            // force callers to zero-fill database-assigned keys.
            string modifier = csharpType == "string" || csharpType == "byte[]" ? "required " : "";
            sb.AppendLine($"        public {modifier}{csharpType} {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} {{ get; set; }}");
        }
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Materializes one row; shared by every full-row query of this table.</summary>");
        sb.AppendLine($"        public static {rowTypeName} Read(System.Data.Common.DbDataReader reader) => new {rowTypeName}");
        sb.AppendLine("        {");
        int ordinal = 0;
        int colCount = tableSchema.Columns.Count;
        foreach (var col in tableSchema.Columns.Values)
        {
            string csharpType = DialectMapper.MapColumnToCSharp(col);
            string comma = ordinal < colCount - 1 ? "," : "";
            sb.AppendLine($"            {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} = {GetReaderCall(csharpType, ordinal)}{comma}");
            ordinal++;
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Dialect-native upsert keyed on the primary key. Bypasses the SQL
    /// parser deliberately: MERGE / ON CONFLICT / ON DUPLICATE KEY are
    /// outside the minimal grammar, and the SQL is correct by construction
    /// from the schema snapshot.
    /// </summary>
    public static string EmitUpsert(string entityName, TableSchema tableSchema, string dialect)
    {
        // Rowversion tokens are database-assigned: excluded from the upsert
        // column set entirely. Upsert is documented last-writer-wins.
        var columns = tableSchema.Columns.Values.Where(c => !c.IsRowVersion).ToList();
        var pkCols = columns.FindAll(c => c.IsPrimaryKey);
        var setCols = columns.FindAll(c => !c.IsPrimaryKey);

        string colList = string.Join(", ", columns.Select(c => c.Name));
        string paramList = string.Join(", ", columns.Select(c => $"@{c.Name}"));

        string sql;
        switch (dialect)
        {
            case "sqlserver":
            {
                string srcSelect = string.Join(", ", columns.Select(c => $"@{c.Name} as {c.Name}"));
                string onClause = string.Join(" and ", pkCols.Select(c => $"target.{c.Name} = src.{c.Name}"));
                string updateSet = string.Join(", ", setCols.Select(c => $"{c.Name} = src.{c.Name}"));
                string insertVals = string.Join(", ", columns.Select(c => $"src.{c.Name}"));
                sql = $"merge into {tableSchema.Name} with (holdlock) as target\n" +
                      $"using (select {srcSelect}) as src\n" +
                      $"on {onClause}\n" +
                      $"when matched then update set {updateSet}\n" +
                      $"when not matched then insert ({colList}) values ({insertVals});";
                break;
            }
            case "postgres":
            case "sqlite":
            {
                string conflictCols = string.Join(", ", pkCols.Select(c => c.Name));
                string updateSet = string.Join(", ", setCols.Select(c => $"{c.Name} = excluded.{c.Name}"));
                sql = $"insert into {tableSchema.Name} ({colList})\nvalues ({paramList})\n" +
                      $"on conflict ({conflictCols}) do update set {updateSet}";
                break;
            }
            case "mysql":
            {
                // VALUES(col) works on both MySQL and MariaDB (the 8.0.20+
                // alias form is not MariaDB-compatible).
                string updateSet = string.Join(", ", setCols.Select(c => $"{c.Name} = values({c.Name})"));
                sql = $"insert into {tableSchema.Name} ({colList})\nvalues ({paramList})\n" +
                      $"on duplicate key update {updateSet}";
                break;
            }
            default:
                throw new System.InvalidOperationException($"Upsert synthesis requires a known dialect (got '{dialect}').");
        }

        var paramInfos = new System.Collections.Generic.List<EmittedParam>();
        foreach (var col in columns)
        {
            paramInfos.Add(CreateEmittedParam(col.Name, DialectMapper.MapColumnToCSharp(col), col.IsNullable, col, tableSchema.Name, isWriteTarget: true));
        }

        var stub = new QueryModel { Name = "Upsert" };

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");
        EmitCrudMethodBody(sb, stub, sql, paramInfos, "_conn", isStatic: false, isAsync: false, dialect: dialect);
        sb.AppendLine();
        EmitCrudMethodBody(sb, stub, sql, paramInfos, "conn", isStatic: true, isAsync: false, dialect: dialect);
        sb.AppendLine();
        EmitCrudMethodBody(sb, stub, sql, paramInfos, "_conn", isStatic: false, isAsync: true, dialect: dialect);
        sb.AppendLine();
        EmitCrudMethodBody(sb, stub, sql, paramInfos, "conn", isStatic: true, isAsync: true, dialect: dialect);
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// POCO-taking overloads for the synthetic write methods:
    /// Update(product), Insert(shipper) (with identity write-back),
    /// Delete(product), Upsert(customer). Emitted only when the scalar
    /// method is the synthetic one - a user override owns its own signature.
    /// </summary>
    public static string EmitPocoOverloads(
        string entityName,
        string rowType,
        TableSchema tableSchema,
        string dialect,
        bool hasInsert,
        bool hasUpdate,
        bool hasDelete,
        bool hasUpsert)
    {
        var columns = new System.Collections.Generic.List<ColumnSchema>(tableSchema.Columns.Values);
        var versionCols = columns.FindAll(c => c.IsRowVersion);
        var pkCols = columns.FindAll(c => c.IsPrimaryKey);
        var setCols = columns.FindAll(c => !c.IsPrimaryKey && !c.IsRowVersion);
        var insertCols = columns.FindAll(c => !c.IsIdentity && !c.IsRowVersion);
        ColumnSchema? identityCol = null;
        foreach (var c in columns)
        {
            if (c.IsIdentity) { identityCol = identityCol == null ? c : null; if (identityCol == null) break; }
        }
        bool insertReturnsId = identityCol != null && !string.IsNullOrEmpty(dialect);

        string Args(System.Collections.Generic.List<ColumnSchema> cols)
            => string.Join(", ", cols.Select(c => $"row.{IdentifierGuard.Escape(DialectMapper.ToPascalCase(c.Name))}"));

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        void Forward(string method, System.Collections.Generic.List<ColumnSchema> cols)
        {
            string args = Args(cols);
            sb.AppendLine($"        public int {method}({rowType} row) => {method}({args});");
            sb.AppendLine($"        public static int {method}(System.Data.Common.DbConnection conn, {rowType} row) => {method}(conn, {args});");
            sb.AppendLine($"        public System.Threading.Tasks.Task<int> {method}Async({rowType} row, System.Threading.CancellationToken cancellationToken = default) => {method}Async({args}, cancellationToken);");
            sb.AppendLine($"        public static System.Threading.Tasks.Task<int> {method}Async(System.Data.Common.DbConnection conn, {rowType} row, System.Threading.CancellationToken cancellationToken = default) => {method}Async(conn, {args}, cancellationToken);");
            sb.AppendLine();
        }

        if (hasInsert && insertCols.Count > 0)
        {
            if (insertReturnsId)
            {
                string idProp = IdentifierGuard.Escape(DialectMapper.ToPascalCase(identityCol!.Name));
                string idType = DialectMapper.MapDbTypeToCSharp(identityCol.DbType, isNullable: false);
                string args = Args(insertCols);
                sb.AppendLine($"        /// <summary>Inserts the row and writes the database-assigned {idProp} back onto it.</summary>");
                sb.AppendLine($"        public {idType} Insert({rowType} row)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = Insert({args});");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public static {idType} Insert(System.Data.Common.DbConnection conn, {rowType} row)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = Insert(conn, {args});");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public async System.Threading.Tasks.Task<{idType}> InsertAsync({rowType} row, System.Threading.CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = await InsertAsync({args}, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public static async System.Threading.Tasks.Task<{idType}> InsertAsync(System.Data.Common.DbConnection conn, {rowType} row, System.Threading.CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = await InsertAsync(conn, {args}, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            else
            {
                Forward("Insert", insertCols);
            }
        }

        if (hasUpdate && setCols.Count > 0 && pkCols.Count > 0)
        {
            // scalar Update parameter order: SET columns then PK columns
            var updateArgsCols = new System.Collections.Generic.List<ColumnSchema>(setCols);
            updateArgsCols.AddRange(pkCols);
            updateArgsCols.AddRange(versionCols);
            Forward("Update", updateArgsCols);
        }

        if (hasDelete && pkCols.Count > 0)
        {
            var deleteArgsCols = new System.Collections.Generic.List<ColumnSchema>(pkCols);
            deleteArgsCols.AddRange(versionCols);
            Forward("Delete", deleteArgsCols);
        }

        if (hasUpsert)
        {
            Forward("Upsert", columns.FindAll(c => !c.IsRowVersion));
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDto(System.Text.StringBuilder sb, ProjectionModel projection)
    {
        sb.AppendLine($"            public class {projection.Name}");
        sb.AppendLine("            {");
        foreach (var col in projection.Columns)
        {
            // `required` keeps non-nullable reference properties honest (no CS8618)
            // and costs nothing: generated mapping always sets every property.
            sb.AppendLine($"                public required {col.Type} {IdentifierGuard.Escape(col.Name)} {{ get; set; }}");
        }
        sb.AppendLine("            }");
    }

    private static void EmitQueryMethods(
        System.Text.StringBuilder sb,
        QueryModel query,
        ProjectionModel projection,
        string originalSql,
        string entityName,
        DatabaseSchema? schema,
        Directives.DirectiveModel? directives = null,
        string? procName = null,
        bool isFirst = false,
        string? canonicalRowType = null,
        bool isStream = false)
    {
        string returnType = canonicalRowType ?? $"Result.{projection.Name}";

        var paramInfos = new System.Collections.Generic.List<EmittedParam>();
        foreach (var param in query.Parameters)
        {
            string paramType = InferParameterType(param.Name, query, projection, schema, directives);
            var column = ResolveBoundColumn(param, query, schema, out string? boundTable);
            paramInfos.Add(CreateEmittedParam(param.Name, paramType, isNullable: false, column, boundTable, isWriteTarget: false));
        }

        string queryId = $"{entityName}.{query.Name}";

        // One materializer shared by all four variants. A direct static call
        // (not a delegate): the JIT inlines small static methods, while
        // delegate invocations are indirect calls it will not reliably
        // inline - see docs/design-decisions.md (row materialization).
        // Canonical full-row queries go one step further and share the
        // single Read() materializer on the row POCO itself.
        string mapperCall;
        if (canonicalRowType != null)
        {
            mapperCall = $"{canonicalRowType}.Read(reader)";
        }
        else
        {
            mapperCall = $"__Map{query.Name}(reader)";
            sb.AppendLine($"        private static {returnType} __Map{query.Name}(System.Data.Common.DbDataReader reader) => new {returnType}");
            sb.AppendLine("        {");
            EmitColumnAssignments(sb, projection, indent: "            ");
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        // Instance sync
        EmitMethodBody(sb, query, projection, returnType, originalSql, paramInfos, "_conn", isStatic: false, isAsync: false, isFirst, queryId, mapperCall, procName, schema?.Dialect, isStream);
        sb.AppendLine();
        // Static sync
        EmitMethodBody(sb, query, projection, returnType, originalSql, paramInfos, "conn", isStatic: true, isAsync: false, isFirst, queryId, mapperCall, procName, schema?.Dialect, isStream);
        sb.AppendLine();
        // Instance async
        EmitMethodBody(sb, query, projection, returnType, originalSql, paramInfos, "_conn", isStatic: false, isAsync: true, isFirst, queryId, mapperCall, procName, schema?.Dialect, isStream);
        sb.AppendLine();
        // Static async
        EmitMethodBody(sb, query, projection, returnType, originalSql, paramInfos, "conn", isStatic: true, isAsync: true, isFirst, queryId, mapperCall, procName, schema?.Dialect, isStream);
    }

    private static void EmitMethodBody(
        System.Text.StringBuilder sb,
        QueryModel query,
        ProjectionModel projection,
        string returnType,
        string originalSql,
        System.Collections.Generic.List<EmittedParam> paramInfos,
        string connVar,
        bool isStatic,
        bool isAsync,
        bool isFirst,
        string queryId,
        string mapperCall,
        string? procName = null,
        string? dialect = null,
        bool isStream = false)
    {
        string modifier = isStatic ? "public static" : "public";
        // A streaming method is an iterator: sync -> IEnumerable<T> (no `async`),
        // async -> IAsyncEnumerable<T> with `async`. yield return inside the
        // existing try/finally is legal (no catch), and disposing the enumerator
        // early runs the finally, closing the reader/connection deterministically.
        string asyncModifier = (isAsync && !isStream) ? " async"
            : (isAsync && isStream) ? " async" : "";
        string syncReturn;
        if (isStream)
            syncReturn = isAsync
                ? $"System.Collections.Generic.IAsyncEnumerable<{returnType}>"
                : $"System.Collections.Generic.IEnumerable<{returnType}>";
        else
            syncReturn = isFirst ? $"{returnType}?" : $"System.Collections.Generic.List<{returnType}>";
        // Non-stream async wraps the sync return in Task<>; stream async returns
        // IAsyncEnumerable<T> directly (it is itself awaitable-by-iteration).
        string declaredReturn = (isAsync && !isStream)
            ? $"System.Threading.Tasks.Task<{syncReturn}>"
            : syncReturn;
        string methodName = isAsync ? $"{query.Name}Async" : query.Name;
        // Async streaming iterators need [EnumeratorCancellation] on the token so
        // `await foreach (... .WithCancellation(ct))` flows the token through.
        bool cancelAttr = isAsync && isStream;
        string paramList = BuildParamList(paramInfos, isStatic, isAsync, enumeratorCancellation: cancelAttr);

        sb.AppendLine($"        {modifier}{asyncModifier} {declaredReturn} {methodName}({paramList})");
        sb.AppendLine("        {");

        EmitValueGuards(sb, paramInfos);

        // Connection lifecycle
        sb.AppendLine($"            bool weOpened = {connVar}.State != System.Data.ConnectionState.Open;");
        sb.AppendLine(isAsync
            ? $"            if (weOpened) await {connVar}.OpenAsync(cancellationToken).ConfigureAwait(false);"
            : $"            if (weOpened) {connVar}.Open();");
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        // Create command
        sb.AppendLine($"                using var cmd = {connVar}.CreateCommand();");
        if (!isStatic)
        {
            sb.AppendLine("                if (_db?.CurrentTransaction != null) cmd.Transaction = _db.CurrentTransaction;");
        }
        if (procName != null)
        {
            sb.AppendLine($"                cmd.CommandText = \"{procName}\";");
            sb.AppendLine("                cmd.CommandType = System.Data.CommandType.StoredProcedure;");
        }
        else
        {
            sb.AppendLine($"                cmd.CommandText = @\"{EscapeVerbatimString(StripLeadingSqlComments(originalSql))}\";");
        }

        EmitParameterBinding(sb, paramInfos, dialect);

        // Execute reader + one-time shape guard. SingleResult (and SingleRow
        // for @first) lets the provider optimize buffering for the shape we
        // are guaranteed to consume.
        string behavior = isFirst
            ? "System.Data.CommandBehavior.SingleRow | System.Data.CommandBehavior.SingleResult"
            : "System.Data.CommandBehavior.SingleResult";
        sb.AppendLine();
        sb.AppendLine(isAsync
            ? $"                using var reader = await cmd.ExecuteReaderAsync({behavior}, cancellationToken).ConfigureAwait(false);"
            : $"                using var reader = cmd.ExecuteReader({behavior});");
        sb.AppendLine($"                if (System.Threading.Volatile.Read(ref __{query.Name}Validated) == 0)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    global::JauntyQ.Generated.JauntyQShapeGuard.Validate(reader, __{query.Name}Columns, \"{queryId}\");");
        sb.AppendLine($"                    System.Threading.Volatile.Write(ref __{query.Name}Validated, 1);");
        sb.AppendLine("                }");

        string readCall = isAsync
            ? "await reader.ReadAsync(cancellationToken).ConfigureAwait(false)"
            : "reader.Read()";

        if (isStream)
        {
            // Iterator: yield each row straight off the reader. Nothing is
            // buffered, so memory stays constant regardless of result-set size.
            // The reader/command/connection are held open by the enclosing
            // try/finally until the consumer finishes (or disposes) enumeration.
            sb.AppendLine($"                while ({readCall})");
            sb.AppendLine("                {");
            sb.AppendLine($"                    yield return {mapperCall};");
            sb.AppendLine("                }");
        }
        else if (isFirst)
        {
            sb.AppendLine($"                if (!({readCall}))");
            sb.AppendLine("                    return null;");
            sb.AppendLine($"                return {mapperCall};");
        }
        else
        {
            sb.AppendLine($"                var results = new System.Collections.Generic.List<{returnType}>();");
            sb.AppendLine($"                while ({readCall})");
            sb.AppendLine("                {");
            sb.AppendLine($"                    results.Add({mapperCall});");
            sb.AppendLine("                }");
            sb.AppendLine("                return results;");
        }

        EmitFinallyClose(sb, connVar, isAsync);
        sb.AppendLine("        }");
    }

    private static void EmitColumnAssignments(System.Text.StringBuilder sb, ProjectionModel projection, string indent)
    {
        for (int i = 0; i < projection.Columns.Count; i++)
        {
            var col = projection.Columns[i];
            string readerCall = GetReaderCall(col.Type, col.Ordinal);
            string comma = i < projection.Columns.Count - 1 ? "," : "";
            sb.AppendLine($"{indent}{IdentifierGuard.Escape(col.Name)} = {readerCall}{comma}");
        }
    }

    private static string GetReaderCall(string csharpType, int ordinal)
    {
        // Handle nullable types
        bool isNullable = csharpType.EndsWith("?");
        string baseType = isNullable ? csharpType.TrimEnd('?') : csharpType;

        string getMethod = baseType switch
        {
            "int" => $"reader.GetInt32({ordinal})",
            "long" => $"reader.GetInt64({ordinal})",
            "short" => $"reader.GetInt16({ordinal})",
            "bool" => $"reader.GetBoolean({ordinal})",
            "decimal" => $"reader.GetDecimal({ordinal})",
            "double" => $"reader.GetDouble({ordinal})",
            "float" => $"reader.GetFloat({ordinal})",
            "string" => $"reader.GetString({ordinal})",
            "System.DateTime" => $"reader.GetDateTime({ordinal})",
            "System.Guid" => $"reader.GetGuid({ordinal})",
            "byte[]" => $"(byte[])reader.GetValue({ordinal})",
            _ => $"reader.GetValue({ordinal})"
        };

        if (isNullable)
        {
            return $"reader.IsDBNull({ordinal}) ? default : {getMethod}";
        }

        // String is a reference type — always needs null check
        if (csharpType == "string")
        {
            return $"reader.IsDBNull({ordinal}) ? null! : {getMethod}";
        }

        return getMethod;
    }

    public static string InferParameterType(string paramName, QueryModel query, ProjectionModel projection, DatabaseSchema? schema = null, Directives.DirectiveModel? directives = null)
    {
        // 0. Check @params directive first
        if (directives?.ExplicitParams != null)
        {
            foreach (var ep in directives.ExplicitParams)
            {
                if (string.Equals(ep.Name, paramName, StringComparison.OrdinalIgnoreCase))
                    return ep.CSharpType;
            }
        }

        // 1. Try binding-based inference (col = @param parsed by ExtractParameterBindings)
        var paramRef = query.Parameters.FirstOrDefault(p => p.Name == paramName);
        if (paramRef != null && !string.IsNullOrEmpty(paramRef.BoundColumnName) && schema != null)
        {
            var resolved = ResolveColumnType(paramRef.BoundTableAlias, paramRef.BoundColumnName, query, schema);
            if (resolved != null)
                return resolved;
        }

        // 2. Fallback: match parameter name to a projection column name
        foreach (var col in projection.Columns)
        {
            if (col.Name.Equals(DialectMapper.ToPascalCase(paramName), StringComparison.OrdinalIgnoreCase))
            {
                return col.Type;
            }
        }

        return "object";
    }

    private static string? ResolveColumnType(string tableAlias, string columnName, QueryModel query, DatabaseSchema schema)
    {
        if (!string.IsNullOrEmpty(tableAlias))
        {
            // Qualified — resolve alias to table name
            string? tableName = ResolveAlias(tableAlias, query);
            if (tableName != null &&
                schema.Tables.TryGetValue(tableName, out var tableSchema) &&
                tableSchema.Columns.TryGetValue(columnName, out var colSchema))
            {
                return DialectMapper.MapColumnToCSharp(colSchema);
            }
        }
        else
        {
            // Unqualified — search all referenced tables
            foreach (var table in query.Tables)
            {
                if (schema.Tables.TryGetValue(table.TableName, out var tableSchema) &&
                    tableSchema.Columns.TryGetValue(columnName, out var colSchema))
                {
                    return DialectMapper.MapColumnToCSharp(colSchema);
                }
            }
        }

        return null;
    }

    private static string? ResolveAlias(string alias, QueryModel query)
    {
        foreach (var table in query.Tables)
        {
            string key = !string.IsNullOrEmpty(table.Alias) ? table.Alias : table.TableName;
            if (string.Equals(key, alias, StringComparison.OrdinalIgnoreCase))
                return table.TableName;
        }
        return null;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string? ResolveProcName(Directives.DirectiveModel? directives, string entityName, string methodName)
    {
        if (directives == null || !directives.IsProc)
            return null;
        return directives.ProcName ?? $"{entityName}_{methodName}";
    }

    /// <summary>
    /// Strips leading blank lines and leading whole-line `--` comments so
    /// commented-out old queries at the top of a .sql file are not embedded
    /// into every generated CommandText. Mid-query comments are preserved.
    /// </summary>
    internal static string StripLeadingSqlComments(string sql)
    {
        var lines = sql.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
        int start = 0;
        while (start < lines.Length)
        {
            var trimmed = lines[start].TrimStart();
            if (trimmed.Length == 0 || trimmed.StartsWith("--"))
            {
                start++;
                continue;
            }
            break;
        }
        return string.Join("\n", lines, start, lines.Length - start).Trim();
    }

    private static void EmitProcScript(
        System.Text.StringBuilder sb,
        string procName,
        string methodName,
        string originalSql,
        QueryModel query,
        ProjectionModel? projection,
        DatabaseSchema? schema,
        Directives.DirectiveModel? directives,
        bool isCrud)
    {
        // Build parameter list for CREATE PROCEDURE
        var procParams = new System.Collections.Generic.List<string>();
        foreach (var param in query.Parameters)
        {
            string csharpType;
            if (isCrud)
                csharpType = InferCrudParameterType(param, query, schema, directives);
            else if (projection != null)
                csharpType = InferParameterType(param.Name, query, projection, schema, directives);
            else
                csharpType = "object";

            var sqlType = CSharpToSqlTypeMapper.Map(csharpType);
            procParams.Add($"    @{param.Name} {sqlType}");
        }

        var paramBlock = procParams.Count > 0
            ? "\n" + string.Join(",\n", procParams) + "\n"
            : "";

        var procSql = $"CREATE OR ALTER PROCEDURE [{procName}]{paramBlock}AS\nBEGIN\n    SET NOCOUNT ON;\n    {StripLeadingSqlComments(originalSql)}\nEND";

        sb.AppendLine("        public static partial class Proc");
        sb.AppendLine("        {");
        sb.AppendLine($"            public const string {methodName} = @\"{EscapeVerbatimString(procSql)}\";");
        sb.AppendLine("        }");
    }

    /// <summary>
    /// Emits a typed call to a stored procedure that already exists in the
    /// database (bound via -- @call). Unlike EmitProcScript, JauntyQ does not
    /// author the body — it reads the callable contract (params, result columns)
    /// from the schema snapshot and emits a CommandType.StoredProcedure call
    /// with ordinal result materialization. Supports IN and OUT/INOUT params;
    /// v1 handles a single result set.
    /// </summary>
    public static string EmitProcCall(string entityName, string methodName, JauntyQ.Schema.ProcedureSchema procedure, string? dialect)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        bool hasResults = procedure.Results.Count > 0;
        string resultType = $"Result.{methodName}";

        // Result DTO (only when the proc returns rows).
        if (hasResults)
        {
            sb.AppendLine("        public static partial class Result");
            sb.AppendLine("        {");
            sb.AppendLine($"            public class {methodName}");
            sb.AppendLine("            {");
            foreach (var col in procedure.Results)
            {
                string ct = DialectMapper.MapColumnToCSharp(col);
                sb.AppendLine($"                public required {ct} {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} {{ get; set; }}");
            }
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Ordinal materializer (mirrors the SELECT path).
            sb.AppendLine($"        private static {resultType} __Map{methodName}(System.Data.Common.DbDataReader reader) => new {resultType}");
            sb.AppendLine("        {");
            for (int i = 0; i < procedure.Results.Count; i++)
            {
                var col = procedure.Results[i];
                string ct = DialectMapper.MapColumnToCSharp(col);
                string comma = i < procedure.Results.Count - 1 ? "," : "";
                sb.AppendLine($"            {IdentifierGuard.Escape(DialectMapper.ToPascalCase(col.Name))} = {GetReaderCall(ct, i)}{comma}");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "_conn", isStatic: false, isAsync: false, dialect);
        sb.AppendLine();
        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "conn", isStatic: true, isAsync: false, dialect);
        sb.AppendLine();
        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "_conn", isStatic: false, isAsync: true, dialect);
        sb.AppendLine();
        EmitProcCallBody(sb, methodName, procedure, resultType, hasResults, "conn", isStatic: true, isAsync: true, dialect);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitProcCallBody(
        System.Text.StringBuilder sb,
        string methodName,
        JauntyQ.Schema.ProcedureSchema procedure,
        string resultType,
        bool hasResults,
        string connVar,
        bool isStatic,
        bool isAsync,
        string? dialect)
    {
        string modifier = isStatic ? "public static" : "public";
        string asyncModifier = isAsync ? " async" : "";
        // Return: List<Result> for row-returning procs, else int (row count).
        string syncReturn = hasResults ? $"System.Collections.Generic.List<{resultType}>" : "int";
        string declaredReturn = isAsync ? $"System.Threading.Tasks.Task<{syncReturn}>" : syncReturn;
        string name = isAsync ? $"{methodName}Async" : methodName;

        // Parameter list: IN params by value, OUT/INOUT params as C# `out`.
        var parts = new System.Collections.Generic.List<string>();
        if (isStatic)
            parts.Add("System.Data.Common.DbConnection conn");
        foreach (var p in procedure.Params)
        {
            if (p.Direction == JauntyQ.Schema.ProcedureParamDirection.ReturnValue)
                continue;
            string ct = DialectMapper.MapDbTypeToCSharp(p.DbType, p.IsNullable);
            string pname = IdentifierGuard.Escape(ToCamelCase(DialectMapper.ToPascalCase(p.Name)));
            if (p.Direction == JauntyQ.Schema.ProcedureParamDirection.Out)
                parts.Add($"out {ct} {pname}");
            else if (p.Direction == JauntyQ.Schema.ProcedureParamDirection.InOut)
                parts.Add($"ref {ct} {pname}");
            else
                parts.Add($"{ct} {pname}");
        }
        if (isAsync)
            parts.Add("System.Threading.CancellationToken cancellationToken = default");

        sb.AppendLine($"        {modifier}{asyncModifier} {declaredReturn} {name}({string.Join(", ", parts)})");
        sb.AppendLine("        {");

        // Pre-assign out params so the method is definitely-assigned on all paths.
        foreach (var p in procedure.Params)
        {
            if (p.Direction == JauntyQ.Schema.ProcedureParamDirection.Out)
            {
                string pname = IdentifierGuard.Escape(ToCamelCase(DialectMapper.ToPascalCase(p.Name)));
                sb.AppendLine($"            {pname} = default;");
            }
        }

        sb.AppendLine($"            bool weOpened = {connVar}.State != System.Data.ConnectionState.Open;");
        sb.AppendLine(isAsync
            ? $"            if (weOpened) await {connVar}.OpenAsync(cancellationToken).ConfigureAwait(false);"
            : $"            if (weOpened) {connVar}.Open();");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                using var cmd = {connVar}.CreateCommand();");
        if (!isStatic)
            sb.AppendLine("                if (_db?.CurrentTransaction != null) cmd.Transaction = _db.CurrentTransaction;");
        sb.AppendLine($"                cmd.CommandText = \"{IdentifierGuard.ToStringLiteral(procedure.Name)}\";");
        sb.AppendLine("                cmd.CommandType = System.Data.CommandType.StoredProcedure;");

        // Bind parameters. Track OUT/INOUT parameter variable names for readback.
        var outReadback = new System.Collections.Generic.List<(string ParamVar, string CSharpName, string CSharpType, bool Nullable)>();
        int idx = 0;
        foreach (var p in procedure.Params)
        {
            if (p.Direction == JauntyQ.Schema.ProcedureParamDirection.ReturnValue)
                continue;
            string varName = $"p{idx++}";
            string ct = DialectMapper.MapDbTypeToCSharp(p.DbType, p.IsNullable);
            string pname = IdentifierGuard.Escape(ToCamelCase(DialectMapper.ToPascalCase(p.Name)));
            sb.AppendLine($"                var {varName} = cmd.CreateParameter();");
            sb.AppendLine($"                {varName}.ParameterName = \"@{p.Name}\";");
            string? adoDbType = MapCSharpTypeToAdoDbType(ct);
            if (adoDbType != null)
                sb.AppendLine($"                {varName}.DbType = System.Data.DbType.{adoDbType};");
            switch (p.Direction)
            {
                case JauntyQ.Schema.ProcedureParamDirection.Out:
                    sb.AppendLine($"                {varName}.Direction = System.Data.ParameterDirection.Output;");
                    if (p.MaxLength is int ml && ml != 0)
                        sb.AppendLine($"                {varName}.Size = {ml};");
                    outReadback.Add((varName, pname, ct, p.IsNullable || !IsNonNullableValueType(ct)));
                    break;
                case JauntyQ.Schema.ProcedureParamDirection.InOut:
                    sb.AppendLine($"                {varName}.Direction = System.Data.ParameterDirection.InputOutput;");
                    if (p.MaxLength is int ml2 && ml2 != 0)
                        sb.AppendLine($"                {varName}.Size = {ml2};");
                    sb.AppendLine(IsNonNullableValueType(ct)
                        ? $"                {varName}.Value = {pname};"
                        : $"                {varName}.Value = (object?){pname} ?? System.DBNull.Value;");
                    outReadback.Add((varName, pname, ct, p.IsNullable || !IsNonNullableValueType(ct)));
                    break;
                default:
                    sb.AppendLine(IsNonNullableValueType(ct)
                        ? $"                {varName}.Value = {pname};"
                        : $"                {varName}.Value = (object?){pname} ?? System.DBNull.Value;");
                    break;
            }
            sb.AppendLine($"                cmd.Parameters.Add({varName});");
        }
        sb.AppendLine();

        if (hasResults)
        {
            string behavior = "System.Data.CommandBehavior.SingleResult";
            sb.AppendLine(isAsync
                ? $"                using (var reader = await cmd.ExecuteReaderAsync({behavior}, cancellationToken).ConfigureAwait(false))"
                : $"                using (var reader = cmd.ExecuteReader({behavior}))");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var results = new System.Collections.Generic.List<{resultType}>();");
            string readCall = isAsync ? "await reader.ReadAsync(cancellationToken).ConfigureAwait(false)" : "reader.Read()";
            sb.AppendLine($"                    while ({readCall})");
            sb.AppendLine($"                        results.Add(__Map{methodName}(reader));");
            EmitProcOutReadback(sb, outReadback, "                    ");
            sb.AppendLine("                    return results;");
            sb.AppendLine("                }");
        }
        else
        {
            sb.AppendLine(isAsync
                ? "                int __affected = await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);"
                : "                int __affected = cmd.ExecuteNonQuery();");
            EmitProcOutReadback(sb, outReadback, "                ");
            sb.AppendLine("                return __affected;");
        }

        EmitFinallyClose(sb, connVar, isAsync);
        sb.AppendLine("        }");
    }

    /// <summary>Reads OUT/INOUT parameter values back into the C# out/ref args.</summary>
    private static void EmitProcOutReadback(
        System.Text.StringBuilder sb,
        System.Collections.Generic.List<(string ParamVar, string CSharpName, string CSharpType, bool Nullable)> outParams,
        string indent)
    {
        foreach (var (paramVar, csName, csType, nullable) in outParams)
        {
            string baseType = csType.EndsWith("?") ? csType.Substring(0, csType.Length - 1) : csType;
            // DBNull -> default; otherwise unbox to the declared type.
            sb.AppendLine($"{indent}{csName} = {paramVar}.Value is null || {paramVar}.Value is System.DBNull ? default! : ({csType})({baseType}){paramVar}.Value;");
        }
    }

    private static string EscapeVerbatimString(string s)
    {
        return s.Replace("\"", "\"\"");
    }
}
