using JauntyQ.Analysis.Migrations;
using JauntyQ.Schema;
using Xunit;

namespace JauntyQ.Analysis.Tests;

[Trait("Category", "AuditRegression")]
public class MigrationParserMalformedInputTests
{
    private static MigrationStatement Only(string sql)
    {
        var statements = MigrationParser.Parse(sql);
        return Assert.Single(statements);
    }

    private static void AssertUnsupported(string sql)
    {
        Assert.Equal(MigrationStatementKind.Unsupported, Only(sql).Kind);
    }

    [Fact]
    public void CreateTable_WithALeadingEmptyColumnSlot_SkipsItAndParsesTheRest()
    {
        var stmt = Only("create table widgets (, id int primary key)");

        Assert.Equal(MigrationStatementKind.CreateTable, stmt.Kind);
        Assert.Equal("widgets", stmt.TableName);
        var column = Assert.Single(stmt.Columns);
        Assert.Equal("id", column.Name);
    }

    [Fact]
    public void CreateTable_WhoseBodyIsOnlyATableLevelConstraint_IsUnsupported()
    {
        AssertUnsupported("create table widgets (check (price > 0))");
    }

    [Fact]
    public void CreateTable_WithNoBody_IsUnsupported()
    {
        AssertUnsupported("create table widgets");
    }

    [Fact]
    public void DropTable_WithNoName_IsUnsupported()
    {
        AssertUnsupported("drop table");
    }

    [Fact]
    public void AlterTable_WithNoName_IsUnsupported()
    {
        AssertUnsupported("alter table");
    }

    [Fact]
    public void AlterTable_WithNoActionAtAll_IsUnsupported()
    {
        AssertUnsupported("alter table widgets");
    }

    [Fact]
    public void AlterTable_WhoseFirstClauseHasNoActionVerb_IsUnsupported()
    {
        AssertUnsupported("alter table widgets rename to gadgets");
    }

    [Fact]
    public void AlterTable_WithAnEmptyClauseBetweenTwoActions_SkipsItAndKeepsBoth()
    {
        var statements = MigrationParser.Parse("alter table widgets add a int, , add b int");

        Assert.Equal(2, statements.Count);
        Assert.All(statements, s => Assert.Equal(MigrationStatementKind.AddColumn, s.Kind));
        Assert.Equal("a", statements[0].Columns[0].Name);
        Assert.Equal("b", statements[1].Columns[0].Name);
    }

    [Fact]
    public void AddPrimaryKey_WithNoColumnList_IsUnsupportedRatherThanAnEmptyKey()
    {
        AssertUnsupported("alter table widgets add primary key");
    }

    [Fact]
    public void AddColumn_WithATypeButNoName_IsUnsupported()
    {
        AssertUnsupported("alter table widgets add column note");
    }

    [Fact]
    public void AddColumn_WhoseTypeIsNotAnIdentifier_IsUnsupported()
    {
        AssertUnsupported("alter table widgets add column note 42");
    }

    [Fact]
    public void AlterColumn_WithACommaContinuation_IsUnsupportedInEveryDialect()
    {
        var statements = MigrationParser.Parse("alter table widgets alter column a int, b int");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    [Fact]
    public void Alter_WithoutTheColumnKeyword_IsUnsupported()
    {
        AssertUnsupported("alter table widgets alter a int");
    }

    [Fact]
    public void AlterColumn_WithNoNewType_IsUnsupported()
    {
        AssertUnsupported("alter table widgets alter column a");
    }

    [Fact]
    public void ComputedColumn_DeclaredExplicitlyNullable_KeepsIsNullable()
    {
        var stmt = Only("create table widgets (id int, total as (qty * price) null)");

        var computed = stmt.Columns[1];
        Assert.True(computed.IsComputed);
        Assert.True(computed.IsNullable);
    }

    [Fact]
    public void ComputedColumn_WithAnUnrecognizedTrailingFlag_SkipsItAndStaysComputed()
    {
        var stmt = Only("create table widgets (id int, total as (qty * price) collate latin1)");

        var computed = stmt.Columns[1];
        Assert.True(computed.IsComputed);
        Assert.Equal("total", computed.Name);
    }

    [Fact]
    public void Column_WithABareDefaultValue_SkipsItAndKeepsTheDeclaredType()
    {
        var stmt = Only("create table widgets (quantity int default 0 not null)");

        var column = Assert.Single(stmt.Columns);
        Assert.Equal("int", column.DbType);
        Assert.False(column.IsNullable);
    }

    [Fact]
    public void GeneratedByDefaultAsIdentity_IsAnIdentityColumn()
    {
        var stmt = Only("create table widgets (id int generated by default as identity)");

        var column = Assert.Single(stmt.Columns);
        Assert.True(column.IsIdentity);
    }

    [Fact]
    public void GeneratedAlwaysAsIdentity_WithSequenceOptions_SkipsThemAndStaysIdentity()
    {
        var stmt = Only("create table widgets (id int generated always as identity (start with 100 increment by 5), name varchar(10))");

        Assert.Equal(2, stmt.Columns.Count);
        Assert.True(stmt.Columns[0].IsIdentity);
        Assert.Equal("name", stmt.Columns[1].Name);
    }

    [Theory]
    [InlineData("create table dbo.gadgets (id int)")]
    [InlineData("create table [dbo].[gadgets] (id int)")]
    public void SchemaQualifiedTableName_ResolvesToItsBareName(string sql)
    {
        var stmt = Only(sql);

        Assert.Equal(MigrationStatementKind.CreateTable, stmt.Kind);
        Assert.Equal("gadgets", stmt.TableName);
    }
}
