<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <RootNamespace>JauntyQ.Analysis</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\JauntyQ.Schema\JauntyQ.Schema.csproj" />
    <ProjectReference Include="..\JauntyQ.SqlParser\JauntyQ.SqlParser.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
</Project>
