using Extrode.JauntyQ.Schema;
using Extrode.JauntyQ.SqlParser.IR;

namespace Extrode.JauntyQ.Generator;

public static partial class CodeEmitter
{
    /// <summary>
    /// POCO-taking overloads for the synthetic write methods:
    /// Update(product), Insert(shipper) (with identity write-back),
    /// Delete(product), Upsert(customer). Emitted only when the scalar
    /// method is the synthetic one - a user override owns its own signature.
    /// </summary>
    public static string EmitPocoOverloads(
        string entityName,
        string rowType,
        TableSchema tableSchema,
        string dialect,
        bool hasInsert,
        bool hasUpdate,
        bool hasDelete,
        bool hasUpsert,
        DatabaseSchema? schema = null,
        System.Collections.Generic.List<ColumnSchema>? scopeCols = null)
    {
        string taskType = TypeRef(schema, "Task", "System.Threading.Tasks");
        var columns = new System.Collections.Generic.List<ColumnSchema>(tableSchema.Columns.Values);
        var versionCols = CrudColumnRules.RowVersionColumns(columns);
        var pkCols = CrudColumnRules.PrimaryKeyColumns(columns);
        // Spec 021: a scoped table's overloads take the scope value before the
        // row and forward it in place of the row's own scope property, in the
        // order AutoCrud.Synthesize put it in the SQL.
        scopeCols ??= new System.Collections.Generic.List<ColumnSchema>();
        // CrudColumnRules.UpdatableColumns is the single source of truth this
        // must match: it supplies the Update(row) POCO overload's forwarded
        // arguments, which have to line up with the synthesized SQL's
        // @parameter list (AutoCrud.cs) one-for-one.
        var setCols = CrudColumnRules.UpdatableColumns(columns);
        setCols.RemoveAll(scopeCols.Contains);
        var insertCols = AutoCrud.ScopeFirst(CrudColumnRules.InsertableColumns(columns), scopeCols);
        var identityCol = CrudColumnRules.SingleIdentityColumn(columns);
        bool insertReturnsId = identityCol != null && !string.IsNullOrEmpty(dialect);

        string ScopeName(ColumnSchema c) => IdentifierGuard.Escape(c.Name);
        // A scope parameter is named after its column, so it can take one of
        // these overloads' own names; ours gives way on a collision, as the
        // query and procedure emitters' "conn"/"cancellationToken" do.
        string Own(string name) => scopeCols.Exists(c => ScopeName(c) == name) ? "__" + name : name;
        string connName = Own("conn");
        string rowName = Own("row");
        string tokenName = Own("cancellationToken");
        string idLocal = Own("id");
        // A scope parameter named like the method being forwarded to hides
        // that method group inside the forwarding call, so qualify the call;
        // and if another scope parameter is named like the entity, qualify that too.
        string entityRef = scopeCols.Exists(c => ScopeName(c) == entityName)
            ? GlobalTypeName(entityName, "Extrode.JauntyQ.Generated")
            : entityName;
        string Call(string method, bool isStatic)
            => scopeCols.Exists(c => ScopeName(c) == method) ? (isStatic ? $"{entityRef}.{method}" : $"this.{method}") : method;
        string Args(System.Collections.Generic.List<ColumnSchema> cols)
            => JoinColumns(cols, ", ", c => scopeCols.Contains(c) ? ScopeName(c) : $"{rowName}.{IdentifierGuard.Escape(DialectMapper.ToPascalCase(c.Name))}");
        string scopeParams = JoinColumns(scopeCols, "", c =>
            $"{ShortenValueTypeName(schema, DialectMapper.MapColumnToCSharp(c, dialect, schema))} {ScopeName(c)}, ");

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace Extrode.JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        // The scalar static targets only carry the optional DbTransaction when
        // no column parameter is itself named "transaction" (the same guard as
        // HasStaticTransactionParam); mirror that so forwarding stays in sync.
        bool TxForwardable(System.Collections.Generic.List<ColumnSchema> cols)
            => !cols.Exists(c => string.Equals(c.Name, "transaction", StringComparison.OrdinalIgnoreCase));

        void Forward(string method, System.Collections.Generic.List<ColumnSchema> cols)
        {
            string args = Args(cols);
            bool tx = TxForwardable(cols);
            string txParam = tx ? ", DbTransaction? transaction = null" : "";
            string txArg = tx ? ", transaction" : "";
            sb.AppendLine($"        public int {method}({scopeParams}{rowType} {rowName}) => {Call(method, false)}({args});");
            sb.AppendLine($"        public static int {method}(DbConnection {connName}, {scopeParams}{rowType} {rowName}{txParam}) => {Call(method, true)}({connName}, {args}{txArg});");
            sb.AppendLine($"        public {taskType}<int> {method}Async({scopeParams}{rowType} {rowName}, CancellationToken {tokenName} = default) => {Call(method + "Async", false)}({args}, {tokenName});");
            sb.AppendLine($"        public static {taskType}<int> {method}Async(DbConnection {connName}, {scopeParams}{rowType} {rowName}{txParam}, CancellationToken {tokenName} = default) => {Call(method + "Async", true)}({connName}, {args}{txArg}, {tokenName});");
            sb.AppendLine();
        }

        if (hasInsert && insertCols.Count > 0)
        {
            if (insertReturnsId)
            {
                string idProp = IdentifierGuard.Escape(DialectMapper.ToPascalCase(identityCol!.Name));
                string idType = ShortenValueTypeName(schema, DialectMapper.MapDbTypeToCSharp(identityCol.DbType, isNullable: false, dialect: dialect));
                string args = Args(insertCols);
                sb.AppendLine($"        /// <summary>Inserts the row and writes the database-assigned {idProp} back onto it.</summary>");
                sb.AppendLine($"        public {idType} Insert({scopeParams}{rowType} {rowName})");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} {idLocal} = {Call("Insert", false)}({args});");
                sb.AppendLine($"            {rowName}.{idProp} = {idLocal};");
                sb.AppendLine($"            return {idLocal};");
                sb.AppendLine("        }");
                sb.AppendLine();
                bool insertTx = TxForwardable(insertCols);
                string insertTxParam = insertTx ? ", DbTransaction? transaction = null" : "";
                string insertTxArg = insertTx ? ", transaction" : "";
                sb.AppendLine($"        public static {idType} Insert(DbConnection {connName}, {scopeParams}{rowType} {rowName}{insertTxParam})");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} {idLocal} = {Call("Insert", true)}({connName}, {args}{insertTxArg});");
                sb.AppendLine($"            {rowName}.{idProp} = {idLocal};");
                sb.AppendLine($"            return {idLocal};");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public async {taskType}<{idType}> InsertAsync({scopeParams}{rowType} {rowName}, CancellationToken {tokenName} = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} {idLocal} = await {Call("InsertAsync", false)}({args}, {tokenName}).ConfigureAwait(false);");
                sb.AppendLine($"            {rowName}.{idProp} = {idLocal};");
                sb.AppendLine($"            return {idLocal};");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public static async {taskType}<{idType}> InsertAsync(DbConnection {connName}, {scopeParams}{rowType} {rowName}{insertTxParam}, CancellationToken {tokenName} = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} {idLocal} = await {Call("InsertAsync", true)}({connName}, {args}{insertTxArg}, {tokenName}).ConfigureAwait(false);");
                sb.AppendLine($"            {rowName}.{idProp} = {idLocal};");
                sb.AppendLine($"            return {idLocal};");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            else
            {
                Forward("Insert", insertCols);
            }
        }

        if (hasUpdate && setCols.Count > 0 && pkCols.Count > 0)
        {
            // scalar Update parameter order: scope, SET, then PK columns
            var updateArgsCols = new System.Collections.Generic.List<ColumnSchema>(scopeCols);
            updateArgsCols.AddRange(setCols);
            updateArgsCols.AddRange(pkCols);
            updateArgsCols.AddRange(versionCols);
            Forward("Update", updateArgsCols);
        }

        if (hasDelete && pkCols.Count > 0)
        {
            var deleteArgsCols = new System.Collections.Generic.List<ColumnSchema>(scopeCols);
            deleteArgsCols.AddRange(pkCols);
            deleteArgsCols.AddRange(versionCols);
            Forward("Delete", deleteArgsCols);
        }

        if (hasUpsert)
        {
            // CrudColumnRules.UpsertColumns is the single source of truth
            // this must match: EmitUpsert (CodeEmitter.Part6.cs) builds its
            // MERGE/ON CONFLICT SQL from the exact same column set.
            var upsertKey = ResolveUpsertKey(tableSchema)
                ?? throw new System.InvalidOperationException(
                    $"Table '{tableSchema.Name}' has no usable upsert key: no primary key, or an " +
                    "identity-only primary key with no secondary UNIQUE index to match on instead.");
            // AUD-R37-01: same defensive backstop as CodeEmitter.Part6.cs's
            // EmitUpsert -- AutoCrud.Synthesize's gate already excludes a
            // table whose key contains an unbindable Computed/RowVersion
            // column, but a direct caller of this method must get the same
            // loud failure Part6.cs gives instead of a POCO overload that
            // forwards to a scalar Upsert(...) signature Part6.cs would
            // refuse to emit for the identical table.
            if (CrudColumnRules.HasUnbindableUpsertKeyColumn(columns, upsertKey))
                throw new System.InvalidOperationException(
                    $"Table '{tableSchema.Name}' has no usable upsert key: its primary key contains a " +
                    "Computed or RowVersion column, and no dialect can bind a value for one on the " +
                    "INSERT/conflict-target side of an upsert.");
            var upsertCols = AutoCrud.ScopeFirst(CrudColumnRules.UpsertColumns(columns, upsertKey), scopeCols);
            Forward("Upsert", upsertCols);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDto(System.Text.StringBuilder sb, ProjectionModel projection, DatabaseSchema? schema = null)
    {
        sb.AppendLine($"            public class {projection.Name}");
        sb.AppendLine("            {");
        foreach (var col in projection.Columns)
        {
            // `required` keeps non-nullable reference properties honest (no CS8618)
            // and costs nothing: generated mapping always sets every property.
            sb.AppendLine($"                public required {ShortenValueTypeName(schema, col.Type)} {IdentifierGuard.Escape(col.Name)} {{ get; set; }}");
        }
        sb.AppendLine("            }");
    }

}
