using Extrode.JauntyQ.Schema;
using Extrode.JauntyQ.SqlParser.IR;

namespace Extrode.JauntyQ.Generator;

public static partial class CodeEmitter
{
    /// <summary>
    /// POCO-taking overloads for the synthetic write methods:
    /// Update(product), Insert(shipper) (with identity write-back),
    /// Delete(product), Upsert(customer). Emitted only when the scalar
    /// method is the synthetic one - a user override owns its own signature.
    /// </summary>
    public static string EmitPocoOverloads(
        string entityName,
        string rowType,
        TableSchema tableSchema,
        string dialect,
        bool hasInsert,
        bool hasUpdate,
        bool hasDelete,
        bool hasUpsert,
        DatabaseSchema? schema = null)
    {
        string taskType = TypeRef(schema, "Task", "System.Threading.Tasks");
        var columns = new System.Collections.Generic.List<ColumnSchema>(tableSchema.Columns.Values);
        var versionCols = CrudColumnRules.RowVersionColumns(columns);
        var pkCols = CrudColumnRules.PrimaryKeyColumns(columns);
        // CrudColumnRules.UpdatableColumns is the single source of truth this
        // must match: it supplies the Update(row) POCO overload's forwarded
        // arguments, which have to line up with the synthesized SQL's
        // @parameter list (AutoCrud.cs) one-for-one.
        var setCols = CrudColumnRules.UpdatableColumns(columns);
        var insertCols = CrudColumnRules.InsertableColumns(columns);
        var identityCol = CrudColumnRules.SingleIdentityColumn(columns);
        bool insertReturnsId = identityCol != null && !string.IsNullOrEmpty(dialect);

        string Args(System.Collections.Generic.List<ColumnSchema> cols)
            => JoinColumns(cols, ", ", c => $"row.{IdentifierGuard.Escape(DialectMapper.ToPascalCase(c.Name))}");

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace Extrode.JauntyQ.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        // The scalar static targets only carry the optional DbTransaction when
        // no column parameter is itself named "transaction" (the same guard as
        // HasStaticTransactionParam); mirror that so forwarding stays in sync.
        bool TxForwardable(System.Collections.Generic.List<ColumnSchema> cols)
            => !cols.Exists(c => string.Equals(c.Name, "transaction", StringComparison.OrdinalIgnoreCase));

        void Forward(string method, System.Collections.Generic.List<ColumnSchema> cols)
        {
            string args = Args(cols);
            bool tx = TxForwardable(cols);
            string txParam = tx ? ", DbTransaction? transaction = null" : "";
            string txArg = tx ? ", transaction" : "";
            sb.AppendLine($"        public int {method}({rowType} row) => {method}({args});");
            sb.AppendLine($"        public static int {method}(DbConnection conn, {rowType} row{txParam}) => {method}(conn, {args}{txArg});");
            sb.AppendLine($"        public {taskType}<int> {method}Async({rowType} row, CancellationToken cancellationToken = default) => {method}Async({args}, cancellationToken);");
            sb.AppendLine($"        public static {taskType}<int> {method}Async(DbConnection conn, {rowType} row{txParam}, CancellationToken cancellationToken = default) => {method}Async(conn, {args}{txArg}, cancellationToken);");
            sb.AppendLine();
        }

        if (hasInsert && insertCols.Count > 0)
        {
            if (insertReturnsId)
            {
                string idProp = IdentifierGuard.Escape(DialectMapper.ToPascalCase(identityCol!.Name));
                string idType = ShortenValueTypeName(schema, DialectMapper.MapDbTypeToCSharp(identityCol.DbType, isNullable: false, dialect: dialect));
                string args = Args(insertCols);
                sb.AppendLine($"        /// <summary>Inserts the row and writes the database-assigned {idProp} back onto it.</summary>");
                sb.AppendLine($"        public {idType} Insert({rowType} row)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = Insert({args});");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                bool insertTx = TxForwardable(insertCols);
                string insertTxParam = insertTx ? ", DbTransaction? transaction = null" : "";
                string insertTxArg = insertTx ? ", transaction" : "";
                sb.AppendLine($"        public static {idType} Insert(DbConnection conn, {rowType} row{insertTxParam})");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = Insert(conn, {args}{insertTxArg});");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public async {taskType}<{idType}> InsertAsync({rowType} row, CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = await InsertAsync({args}, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public static async {taskType}<{idType}> InsertAsync(DbConnection conn, {rowType} row{insertTxParam}, CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {idType} id = await InsertAsync(conn, {args}{insertTxArg}, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"            row.{idProp} = id;");
                sb.AppendLine("            return id;");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            else
            {
                Forward("Insert", insertCols);
            }
        }

        if (hasUpdate && setCols.Count > 0 && pkCols.Count > 0)
        {
            // scalar Update parameter order: SET columns then PK columns
            var updateArgsCols = new System.Collections.Generic.List<ColumnSchema>(setCols);
            updateArgsCols.AddRange(pkCols);
            updateArgsCols.AddRange(versionCols);
            Forward("Update", updateArgsCols);
        }

        if (hasDelete && pkCols.Count > 0)
        {
            var deleteArgsCols = new System.Collections.Generic.List<ColumnSchema>(pkCols);
            deleteArgsCols.AddRange(versionCols);
            Forward("Delete", deleteArgsCols);
        }

        if (hasUpsert)
        {
            // CrudColumnRules.UpsertColumns is the single source of truth
            // this must match: EmitUpsert (CodeEmitter.Part6.cs) builds its
            // MERGE/ON CONFLICT SQL from the exact same column set.
            var upsertKey = ResolveUpsertKey(tableSchema)
                ?? throw new System.InvalidOperationException(
                    $"Table '{tableSchema.Name}' has no usable upsert key: no primary key, or an " +
                    "identity-only primary key with no secondary UNIQUE index to match on instead.");
            // AUD-R37-01: same defensive backstop as CodeEmitter.Part6.cs's
            // EmitUpsert -- AutoCrud.Synthesize's gate already excludes a
            // table whose key contains an unbindable Computed/RowVersion
            // column, but a direct caller of this method must get the same
            // loud failure Part6.cs gives instead of a POCO overload that
            // forwards to a scalar Upsert(...) signature Part6.cs would
            // refuse to emit for the identical table.
            if (CrudColumnRules.HasUnbindableUpsertKeyColumn(columns, upsertKey))
                throw new System.InvalidOperationException(
                    $"Table '{tableSchema.Name}' has no usable upsert key: its primary key contains a " +
                    "Computed or RowVersion column, and no dialect can bind a value for one on the " +
                    "INSERT/conflict-target side of an upsert.");
            var upsertCols = CrudColumnRules.UpsertColumns(columns, upsertKey);
            Forward("Upsert", upsertCols);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDto(System.Text.StringBuilder sb, ProjectionModel projection, DatabaseSchema? schema = null)
    {
        sb.AppendLine($"            public class {projection.Name}");
        sb.AppendLine("            {");
        foreach (var col in projection.Columns)
        {
            // `required` keeps non-nullable reference properties honest (no CS8618)
            // and costs nothing: generated mapping always sets every property.
            sb.AppendLine($"                public required {ShortenValueTypeName(schema, col.Type)} {IdentifierGuard.Escape(col.Name)} {{ get; set; }}");
        }
        sb.AppendLine("            }");
    }

}
