using Extrode.JauntyQ.Analysis.Migrations;
using Extrode.JauntyQ.Schema;
using Xunit;

namespace Extrode.JauntyQ.Analysis.Tests;

[Trait("Category", "AuditRegression")]
public class AnalysisDisableAuditTests
{
    [Fact]
    public void GeneratedByDefaultAsExpression_IsComputed()
    {
        var stmt = Assert.Single(MigrationParser.Parse("CREATE TABLE t (c int GENERATED BY DEFAULT AS (a + 1) STORED)"));
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsComputed);
        Assert.False(col.IsIdentity);
    }

    [Fact]
    public void DropMissingColumn_LeavesIndexWithNullColumnEntryUntouched()
    {
        var schema = new DatabaseSchema { Dialect = "postgres" };
        schema.Tables["t"] = new TableSchema
        {
            Name = "t",
            Columns = { ["a"] = new ColumnSchema { Name = "a", DbType = "int" } },
            Indexes = { new IndexSchema { Name = "IX", Columns = new List<string> { null! } } }
        };
        var errors = new List<AnalysisDiagnostic>();

        var result = SchemaSimulator.Apply(
            schema,
            new List<(string, List<MigrationStatement>)> { ("0001.sql", MigrationParser.Parse("ALTER TABLE t DROP COLUMN missing")) },
            errors);

        Assert.Equal("JNT9002", Assert.Single(errors).Code);
        var index = Assert.Single(result.Tables["t"].Indexes);
        Assert.Equal("IX", index.Name);
        Assert.Null(Assert.Single(index.Columns));
    }

    [Theory]
    [InlineData("postgres")]
    [InlineData("mysql")]
    [InlineData("sqlserver")]
    [InlineData("sqlite")]
    public void NullOrEmptyName_IsNeverReserved(string dialect)
    {
        foreach (var position in new[] { SqlIdentifierPosition.Column, SqlIdentifierPosition.Object })
        {
            Assert.False(DialectReservedWords.IsReservedInDialect(null!, dialect, position));
            Assert.False(DialectReservedWords.IsReservedInDialect("", dialect, position));
        }
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    public void NullOrEmptyDialect_ReservesNothing(string? dialect)
    {
        Assert.False(DialectReservedWords.IsReservedInDialect("select", dialect, SqlIdentifierPosition.Column));
        Assert.False(DialectReservedWords.IsReservedInDialect("select", dialect, SqlIdentifierPosition.Object));
    }
}