using Extrode.JauntyQ.Analysis.Migrations;
using Xunit;

namespace Extrode.JauntyQ.Analysis.Tests;

/// <summary>
/// Direct coverage for MigrationParser gaps not exercised by
/// MigrationParserTests: the ALTER COLUMN SET/DROP and identity-toggle
/// guard chains under operator-precedence-changing mutations, the ADD
/// CONSTRAINT-keyword string literals, WITH TIME ZONE's exact match vs. a
/// same-first-word false positive, MySQL UNSIGNED without ZEROFILL still
/// reaching the NULL flag, GENERATED BY (missing DEFAULT) AS IDENTITY,
/// the default-nullable initializer, GroupAlterActions' malformed-first-
/// clause guard, and ReadObjectName's multi-level dotted-name loop.
/// </summary>
[Trait("Category", "AuditRegression")]
public class MigrationParserMutationCoverageTests
{
    // ── ALTER COLUMN SET/DROP guard: isAlterColumn term must gate the whole chain ──

    [Fact]
    public void ModifyForm_SetNotNullShapedBody_DoesNotMisfireTheAlterColumnOnlySetDropGuard()
    {
        // MODIFY never supports the SET/DROP NOT NULL forms (Postgres-only,
        // ALTER COLUMN-only) -- isAlterColumn=false must gate the whole
        // chain regardless of what the rest of the body looks like. "set"
        // tokenizes as a Keyword, so falling through to ParseColumnDef
        // correctly yields Unsupported too -- both paths must agree.
        var statements = MigrationParser.Parse("alter table products modify product_name set not null");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    [Fact]
    public void ModifyForm_AddGeneratedShapedBody_FallsThroughToOrdinaryColumnDef_NotUnsupported()
    {
        // Same isAlterColumn gate on the identity-toggle chain: MODIFY
        // + "add generated" must NOT be recognized as the toggle form.
        // "add"/"generated" both tokenize as plain Identifiers, so the
        // fallthrough misparses this as an ordinary column named "product_name"
        // whose type-clause loop consumes "add" as DbType and "generated" as
        // an unrecognized flag -- still a real (if nonsensical) AlterColumn,
        // not Unsupported.
        var statements = MigrationParser.Parse("alter table products modify product_name add generated");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.AlterColumn, stmt.Kind);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("add", col.DbType);
    }

    [Fact]
    public void AlterColumn_NothingAfterTheColumnKeyword_IsUnsupported_NoIndexOutOfRange()
    {
        // p == body.Count exactly after consuming "COLUMN": both the
        // SET/DROP and identity-toggle guards must short-circuit on
        // "p < body.Count" before ever indexing body[p], or this throws
        // instead of returning a diagnostic.
        var statements = MigrationParser.Parse("alter table products alter column");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    [Fact]
    public void AlterColumnDefault_SetDefaultNull_IsIgnored_NotMisreadAsNullabilityChange()
    {
        // "SET DEFAULT NULL": the NOT-NULL branch's own two-token check
        // (Is(p+2,"NOT") && Is(p+3,"NULL")) must require NOT literally
        // present, not treat the unrelated trailing "NULL" of "DEFAULT NULL"
        // as satisfying it.
        var statements = MigrationParser.Parse("alter table products alter column product_name set default null");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Ignored, stmt.Kind);
    }

    // ── ADD CONSTRAINT-keyword recognition: each keyword's own string literal ──

    [Theory]
    [InlineData("alter table products add unique int")]
    [InlineData("alter table products add foreign int")]
    [InlineData("alter table products add check int")]
    public void AddConstraintKeyword_FollowedByAValidTypeToken_StillReportsUnsupported_NotMisparsedAsAColumn(string sql)
    {
        // Each of UNIQUE/FOREIGN/CHECK routes ADD into the constraint
        // branch, which always returns Unsupported for anything but a
        // recognized "PRIMARY KEY (...)" shape. If the literal keyword
        // check for one of these three is lost, "add <keyword> int" falls
        // through and misparses as an ordinary column definition named
        // after the keyword instead.
        var statements = MigrationParser.Parse(sql);

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── WITH TIME ZONE: all three words must match, not just the first two/first ──

    [Theory]
    [InlineData("alter table t add col time with time foo not null")] // WITH+TIME true, ZONE false
    [InlineData("alter table t add col time with foo zone not null")] // WITH true, TIME false, ZONE true
    public void TimeColumn_PartialWithTimeZoneMatch_DbTypeStaysBare_NotWronglyExtended(string sql)
    {
        var statements = MigrationParser.Parse(sql);

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("time", col.DbType);
        Assert.False(col.IsNullable);
    }

    // ── MySQL UNSIGNED without ZEROFILL: NOT NULL flag must still be reached ──

    [Fact]
    public void MySqlUnsigned_NoZerofill_TrailingNotNullFlagStillRecognized()
    {
        var statements = MigrationParser.Parse("alter table t add col smallint unsigned not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("smallint unsigned", col.DbType);
        Assert.False(col.IsNullable);
    }

    // ── GENERATED BY (malformed, missing DEFAULT) AS IDENTITY ──

    [Fact]
    public void GeneratedByWithoutDefault_FallsThroughToTheStandaloneIdentityFlag()
    {
        // "BY" alone (no "DEFAULT" following) must not be consumed as the
        // "BY DEFAULT" unit -- it's skipped as an unrecognized flag token,
        // and the very next "IDENTITY" token is then read by the
        // standalone IDENTITY/AUTO_INCREMENT/SERIAL flag check instead.
        var statements = MigrationParser.Parse("alter table t add col int generated by identity");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
    }

    // ── Default-nullable initializer: no explicit flag at all ──

    [Fact]
    public void ColumnWithNoNullabilityFlagAtAll_DefaultsToNullable()
    {
        var statements = MigrationParser.Parse("alter table t add col nvarchar(max)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsNullable);
    }

    // ── Computed column shorthand guard: both Keyword-type AND value=="AS" required ──

    [Fact]
    public void ColumnStartingWithAKeywordThatIsNotAs_FollowedByParens_IsNotMistakenForComputedShorthand()
    {
        // "case" tokenizes as a Keyword (satisfying the Type check alone),
        // but isn't "AS" -- both conditions must hold, or a column literally
        // named after some other keyword and followed by any parenthesized
        // token would be wrongly treated as a computed-column expression.
        var statements = MigrationParser.Parse("alter table t add total case (1)");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── IDENTITY(seed,increment): unterminated paren greedily consumes to EOF ──

    [Fact]
    public void IdentityParen_MissingClosingParen_GreedilyConsumesRestOfDefinition_IncludingNotNull()
    {
        // Documents the current (if surprising) behavior: with no closing
        // ")" anywhere in the remaining tokens, the seed/increment skip loop
        // runs to the end of the definition looking for one that never
        // comes, silently swallowing a trailing "NOT NULL" along with it.
        var statements = MigrationParser.Parse("alter table t add col int identity(1,1 not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
        Assert.True(col.IsNullable);
    }

    // ── GroupAlterActions: malformed first clause ──

    [Fact]
    public void AlterTable_FirstClauseHasNoRecognizedActionVerb_IsUnsupported()
    {
        var statements = MigrationParser.Parse("alter table products rename column a to b");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── ReadObjectName: multi-level dotted names ──

    [Fact]
    public void CreateTable_ThreeLevelSchemaQualifiedName_KeepsOnlyTheFinalSegment()
    {
        var statements = MigrationParser.Parse("create table db.dbo.gadgets (id int primary key)");

        var stmt = Assert.Single(statements);
        Assert.Equal("gadgets", stmt.TableName);
    }
}
