using System.Linq;
using Extrode.JauntyQ.Analysis.Migrations;
using Xunit;

namespace Extrode.JauntyQ.Analysis.Tests;

/// <summary>
/// Direct coverage for MigrationParser gaps not exercised by
/// MigrationParserTests: the ALTER COLUMN SET/DROP and identity-toggle
/// guard chains under operator-precedence-changing mutations, the ADD
/// CONSTRAINT-keyword string literals, WITH TIME ZONE's exact match vs. a
/// same-first-word false positive, MySQL UNSIGNED without ZEROFILL still
/// reaching the NULL flag, GENERATED BY (missing DEFAULT) AS IDENTITY,
/// the default-nullable initializer, GroupAlterActions' malformed-first-
/// clause guard, and ReadObjectName's multi-level dotted-name loop.
/// </summary>
[Trait("Category", "AuditRegression")]
public class MigrationParserMutationCoverageTests
{
    // ── ALTER COLUMN SET/DROP guard: isAlterColumn term must gate the whole chain ──

    [Fact]
    public void ModifyForm_SetNotNullShapedBody_DoesNotMisfireTheAlterColumnOnlySetDropGuard()
    {
        // MODIFY never supports the SET/DROP NOT NULL forms (Postgres-only,
        // ALTER COLUMN-only) -- isAlterColumn=false must gate the whole
        // chain regardless of what the rest of the body looks like. "set"
        // tokenizes as a Keyword, so falling through to ParseColumnDef
        // correctly yields Unsupported too -- both paths must agree.
        var statements = MigrationParser.Parse("alter table products modify product_name set not null");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    [Fact]
    public void ModifyForm_AddGeneratedShapedBody_FallsThroughToOrdinaryColumnDef_NotUnsupported()
    {
        // Same isAlterColumn gate on the identity-toggle chain: MODIFY
        // + "add generated" must NOT be recognized as the toggle form.
        // "add"/"generated" both tokenize as plain Identifiers, so the
        // fallthrough misparses this as an ordinary column named "product_name"
        // whose type-clause loop consumes "add" as DbType and "generated" as
        // an unrecognized flag -- still a real (if nonsensical) AlterColumn,
        // not Unsupported.
        var statements = MigrationParser.Parse("alter table products modify product_name add generated");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.AlterColumn, stmt.Kind);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("add", col.DbType);
    }

    [Fact]
    public void AlterColumn_NothingAfterTheColumnKeyword_IsUnsupported_NoIndexOutOfRange()
    {
        // p == body.Count exactly after consuming "COLUMN": both the
        // SET/DROP and identity-toggle guards must short-circuit on
        // "p < body.Count" before ever indexing body[p], or this throws
        // instead of returning a diagnostic.
        var statements = MigrationParser.Parse("alter table products alter column");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    [Fact]
    public void AlterColumnDefault_SetDefaultNull_IsIgnored_NotMisreadAsNullabilityChange()
    {
        // "SET DEFAULT NULL": the NOT-NULL branch's own two-token check
        // (Is(p+2,"NOT") && Is(p+3,"NULL")) must require NOT literally
        // present, not treat the unrelated trailing "NULL" of "DEFAULT NULL"
        // as satisfying it.
        var statements = MigrationParser.Parse("alter table products alter column product_name set default null");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Ignored, stmt.Kind);
    }

    // ── ADD CONSTRAINT-keyword recognition: each keyword's own string literal ──

    [Theory]
    [InlineData("alter table products add unique int")]
    [InlineData("alter table products add foreign int")]
    [InlineData("alter table products add check int")]
    public void AddConstraintKeyword_FollowedByAValidTypeToken_StillReportsUnsupported_NotMisparsedAsAColumn(string sql)
    {
        // Each of UNIQUE/FOREIGN/CHECK routes ADD into the constraint
        // branch, which always returns Unsupported for anything but a
        // recognized "PRIMARY KEY (...)" shape. If the literal keyword
        // check for one of these three is lost, "add <keyword> int" falls
        // through and misparses as an ordinary column definition named
        // after the keyword instead.
        var statements = MigrationParser.Parse(sql);

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── WITH TIME ZONE: all three words must match, not just the first two/first ──

    [Theory]
    [InlineData("alter table t add col time with time foo not null")] // WITH+TIME true, ZONE false
    [InlineData("alter table t add col time with foo zone not null")] // WITH true, TIME false, ZONE true
    public void TimeColumn_PartialWithTimeZoneMatch_DbTypeStaysBare_NotWronglyExtended(string sql)
    {
        var statements = MigrationParser.Parse(sql);

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("time", col.DbType);
        Assert.False(col.IsNullable);
    }

    // ── MySQL UNSIGNED without ZEROFILL: NOT NULL flag must still be reached ──

    [Fact]
    public void MySqlUnsigned_NoZerofill_TrailingNotNullFlagStillRecognized()
    {
        var statements = MigrationParser.Parse("alter table t add col smallint unsigned not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("smallint unsigned", col.DbType);
        Assert.False(col.IsNullable);
    }

    // ── GENERATED BY (malformed, missing DEFAULT) AS IDENTITY ──

    [Fact]
    public void GeneratedByWithoutDefault_FallsThroughToTheStandaloneIdentityFlag()
    {
        // "BY" alone (no "DEFAULT" following) must not be consumed as the
        // "BY DEFAULT" unit -- it's skipped as an unrecognized flag token,
        // and the very next "IDENTITY" token is then read by the
        // standalone IDENTITY/AUTO_INCREMENT/SERIAL flag check instead.
        var statements = MigrationParser.Parse("alter table t add col int generated by identity");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
    }

    // ── Default-nullable initializer: no explicit flag at all ──

    [Fact]
    public void ColumnWithNoNullabilityFlagAtAll_DefaultsToNullable()
    {
        var statements = MigrationParser.Parse("alter table t add col nvarchar(max)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsNullable);
    }

    // ── Computed column shorthand guard: both Keyword-type AND value=="AS" required ──

    [Fact]
    public void ColumnStartingWithAKeywordThatIsNotAs_FollowedByParens_IsNotMistakenForComputedShorthand()
    {
        // "case" tokenizes as a Keyword (satisfying the Type check alone),
        // but isn't "AS" -- both conditions must hold, or a column literally
        // named after some other keyword and followed by any parenthesized
        // token would be wrongly treated as a computed-column expression.
        var statements = MigrationParser.Parse("alter table t add total case (1)");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── IDENTITY(seed,increment): unterminated paren greedily consumes to EOF ──

    [Fact]
    public void IdentityParen_MissingClosingParen_GreedilyConsumesRestOfDefinition_IncludingNotNull()
    {
        // Documents the current (if surprising) behavior: with no closing
        // ")" anywhere in the remaining tokens, the seed/increment skip loop
        // runs to the end of the definition looking for one that never
        // comes, silently swallowing a trailing "NOT NULL" along with it.
        var statements = MigrationParser.Parse("alter table t add col int identity(1,1 not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
        Assert.True(col.IsNullable);
    }

    // ── SplitTopLevel / ReadParenNameList: unterminated paren, no crash ──

    [Fact]
    public void CreateTable_UnterminatedColumnList_StopsAtEndOfTokens_NoIndexOutOfRange()
    {
        // No closing ")" anywhere -- SplitTopLevel's own loop bound must
        // stop at tokens.Count, not run one iteration past the end trying
        // to index a token that doesn't exist.
        var statements = MigrationParser.Parse("create table t (id int");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.CreateTable, stmt.Kind);
        Assert.Equal("id", Assert.Single(stmt.Columns).Name);
    }

    [Fact]
    public void AddPrimaryKey_UnterminatedColumnList_StopsAtEndOfTokens_NoIndexOutOfRange()
    {
        // Same bound, in ReadParenNameList's own for-loop: an ADD
        // CONSTRAINT ... PRIMARY KEY (a, b with no closing paren must not
        // walk past the end of the token list.
        var statements = MigrationParser.Parse("alter table products add constraint pk_products primary key (product_id");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.AddPrimaryKey, stmt.Kind);
        Assert.Equal("product_id", Assert.Single(stmt.ColumnNames));
    }

    // ── GroupAlterActions: malformed first clause ──

    [Fact]
    public void AlterTable_FirstClauseHasNoRecognizedActionVerb_IsUnsupported()
    {
        var statements = MigrationParser.Parse("alter table products rename column a to b");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── ReadObjectName: multi-level dotted names ──

    [Fact]
    public void CreateTable_ThreeLevelSchemaQualifiedName_KeepsOnlyTheFinalSegment()
    {
        var statements = MigrationParser.Parse("create table db.dbo.gadgets (id int primary key)");

        var stmt = Assert.Single(statements);
        Assert.Equal("gadgets", stmt.TableName);
    }

    // ── ParseCreateTable: an empty def between two commas is skipped, not counted ──

    [Fact]
    public void CreateTable_DoubleCommaBetweenColumns_ProducesEmptyDef_SilentlySkipped()
    {
        var statements = MigrationParser.Parse("create table t (id int primary key,, name varchar(20))");

        var stmt = Assert.Single(statements);
        Assert.Equal(2, stmt.Columns.Count);
        Assert.Equal("id", stmt.Columns[0].Name);
        Assert.Equal("name", stmt.Columns[1].Name);
    }

    // ── ParseCreateTable: zero parsed columns falls back to Unsupported ──

    [Fact]
    public void CreateTable_EmptyColumnList_IsUnsupported_NotAZeroColumnTable()
    {
        var statements = MigrationParser.Parse("create table t ()");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── ALTER COLUMN ... SET GENERATED/IDENTITY: unmodeled, same as ADD/DROP ──

    [Fact]
    public void AlterColumn_SetGenerated_IsUnsupported_SameAsAddOrDropGenerated()
    {
        var statements = MigrationParser.Parse("alter table t alter column c set generated always as identity");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── SkipParenGroup: guard must not consume tokens when not positioned on "(" ──

    [Fact]
    public void GeneratedAlwaysAsIdentity_WithNoSeedParen_DoesNotConsumeTheFollowingNotNull()
    {
        // If SkipParenGroup's own "am I even at a '('?" guard were bypassed,
        // its scan loop would run from "not" onward with nothing to match,
        // silently swallowing "not null" one token at a time and leaving
        // IsNullable at its default (true) instead of being set false.
        var statements = MigrationParser.Parse("alter table t add id int generated always as identity not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
        Assert.False(col.IsNullable);
    }

    // ── SkipParenGroup / DEFAULT-expression paren skip: nested-paren depth must be tracked ──

    [Fact]
    public void ComputedColumn_GeneratedAsExpressionWithNestedFunctionCall_StoredThenNotNullStillParsed()
    {
        // round(price, 2) nests a second "(" / ")" pair inside the outer
        // GENERATED ... AS (...) group. If SkipParenGroup's depth counter
        // isn't correctly incremented/decremented/compared per paren, the
        // scan either stops at the wrong (inner) ")" or never terminates --
        // either way "stored" and the trailing "not null" would land in the
        // wrong place, or get swallowed, and IsNullable would stay at its
        // default (true) instead of being set false.
        var statements = MigrationParser.Parse(
            "alter table t add total decimal generated always as (round(price, 2)) stored not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsComputed);
        Assert.False(col.IsNullable);
    }

    [Fact]
    public void DefaultExpression_WithNestedFunctionCall_DepthTracksCorrectly_NotNullStillParsed()
    {
        // Same nested-paren depth-tracking requirement as SkipParenGroup,
        // but in the inline DEFAULT-expression skip loop: if depth is
        // mistracked, the trailing "not null" gets absorbed into the
        // runaway "skip the default expression" scan instead of being seen
        // by the flags loop, leaving IsNullable at its default (true).
        var statements = MigrationParser.Parse(
            "alter table t add col decimal default (round(price, 2)) not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.False(col.IsNullable);
    }

    // ── Facet paren: unterminated "(" at end of definition doesn't overrun ──

    [Fact]
    public void FacetParen_UnterminatedWithNoDigits_DoesNotThrow_NoCrash()
    {
        var statements = MigrationParser.Parse("alter table t add price decimal(");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("decimal", col.DbType);
    }

    [Fact]
    public void FacetParen_UnterminatedAfterCommaWithNoSecondDigit_DoesNotThrow_NoCrash()
    {
        var statements = MigrationParser.Parse("alter table t add price decimal(10,");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("decimal", col.DbType);
        Assert.Equal(10, col.Precision);
    }

    // ── ApplyFacets: isDecimal's other three literals, not just "decimal" ──

    [Theory]
    [InlineData("numeric")]
    [InlineData("money")]
    [InlineData("smallmoney")]
    public void ApplyFacets_EachDecimalLikeDbType_GetsPrecisionAndScaleFromFacets(string dbType)
    {
        var statements = MigrationParser.Parse($"alter table t add amount {dbType}(8,3)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal(8, col.Precision);
        Assert.Equal(3, col.Scale);
    }

    // ── Facet paren: the scale is the SECOND number, distinct from precision ──

    [Fact]
    public void FacetParen_PrecisionAndScale_ScaleReadsTheSecondDigitGroupNotTheFirst()
    {
        // With precision and scale set to different values, a mutant that
        // re-reads the first number's own token for the second facet
        // instead of advancing past the comma would report Scale equal to
        // Precision instead of the actual second number.
        var statements = MigrationParser.Parse("create table t (a decimal(10,2))");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal(10, col.Precision);
        Assert.Equal(2, col.Scale);
    }

    // ── ApplyFacets: IsUnicode is false for a non-"n"-prefixed text type ──

    [Fact]
    public void ApplyFacets_PlainVarchar_IsUnicodeIsFalse_NotJustUnset()
    {
        var statements = MigrationParser.Parse("alter table t add name varchar(50)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.False(col.IsUnicode);
    }

    // ── GroupAlterActions: a malformed first clause must void the WHOLE
    // statement, not just get silently dropped while later well-formed
    // clauses still parse ──

    [Fact]
    public void AlterTable_MalformedFirstClauseFollowedByWellFormedClause_IsUnsupported_NotPartiallyParsed()
    {
        // A single malformed clause with nothing after it already returns
        // Unsupported via the empty-groups-list fallback regardless of
        // whether GroupAlterActions' own "return null" fires -- both paths
        // converge on Count==0. Only a well-formed clause AFTER the
        // malformed one can distinguish them: if the early return is
        // skipped, "add c int" would still be recognized as its own group
        // and the statement would wrongly come back parsed instead of
        // Unsupported.
        var statements = MigrationParser.Parse("alter table t rename column a to b, add c int");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── Computed-column inline flags loop: NOT+NULL pair must both be present ──

    [Fact]
    public void ComputedColumn_JunkTokenImmediatelyBeforeNull_DoesNotFalselyMarkNonNullable()
    {
        // A widened (OR'd) "Is(NOT) || Is(cp+1, NULL)" check would fire on
        // ANY token immediately preceding a bare "NULL", not just "NOT" --
        // wrongly flipping IsNullable to false instead of leaving the
        // generic-skip loop to reach "NULL" on its own next iteration (which
        // correctly sets IsNullable true).
        var statements = MigrationParser.Parse("create table t (total as (a + b) collate null)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsNullable);
    }

    // ── Computed-column inline flags loop: bare NULL check must require an exact match ──

    [Fact]
    public void ComputedColumn_JunkTokenAfterAnExplicitNotNull_DoesNotFlipNullabilityBack()
    {
        // A negated "!(Is(cp, NULL))" bare-NULL check would fire on every
        // token that ISN'T literally "NULL" -- including a trailing junk
        // token after an already-correct "NOT NULL", wrongly flipping
        // IsNullable back to true.
        var statements = MigrationParser.Parse("create table t (total as (a + b) not null collate)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.False(col.IsNullable);
    }

    // ── Computed-column inline flags loop: NOT+NULL branch must "continue", not fall through ──

    [Fact]
    public void ComputedColumn_RedundantNotNullRepeatedTwice_StaysNonNullable()
    {
        // If the NOT+NULL branch's own "continue" were dropped, matching the
        // first "NOT NULL" pair would still set IsNullable=false and advance
        // cp by 2, but then fall straight into this same iteration's
        // trailing bare-NULL check instead of restarting the loop. That
        // check only tests a single token, so it can't recognize the second
        // "NOT" as the start of another NOT+NULL pair -- it falls through to
        // the generic skip instead, leaving cp on the second pair's trailing
        // "NULL" token, which the bare-NULL check on the *next* iteration
        // then matches on its own, wrongly flipping IsNullable back to true
        // even though "NOT NULL" was stated twice.
        var statements = MigrationParser.Parse("create table t (total as (x) not null not null)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.False(col.IsNullable);
    }

    // ── Computed-column inline flags loop: a trailing bare NULL must still flip nullability back ──

    [Fact]
    public void ComputedColumn_NotNullFollowedByBareNull_FlipsBackToNullable()
    {
        // The bare-NULL branch's own recognition of "NULL" is what lets a
        // trailing bare NULL override an earlier "NOT NULL" -- if that
        // check were disabled (or its handler statement dropped), the
        // second token would fall through to the generic single-token skip
        // instead, leaving IsNullable at whatever the "NOT NULL" pair set it
        // to (false), even though the column's last stated flag was NULL.
        var statements = MigrationParser.Parse("create table t (total as (x) not null null)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsNullable);
    }

    // ── GENERATED ... AS (expr) computed column: expr must be skipped as an opaque paren group ──

    [Fact]
    public void GeneratedComputedColumn_ExpressionContainsNotNull_DoesNotFlipNullability()
    {
        // The GENERATED ALWAYS AS (expr) STORED/VIRTUAL branch relies on
        // SkipParenGroup to jump straight past the parenthesized expression
        // as one opaque unit. If that call were dropped, pos would be left
        // sitting on the expression's own opening "(" and the outer flags
        // loop would re-examine every token *inside* the expression one at a
        // time from the top of the if-chain -- so a "not null" appearing
        // inside the expression's own text (e.g. an IS NOT NULL check) gets
        // misread as a real trailing NOT NULL flag on the column itself,
        // incorrectly flipping IsNullable to false even though no flag was
        // ever stated outside the parens.
        var statements = MigrationParser.Parse(
            "create table t (b bool, a bool generated always as (b is not null) stored)");

        var stmt = Assert.Single(statements);
        var col = stmt.Columns.Find(x => x.Name == "a");
        Assert.NotNull(col);
        Assert.True(col!.IsComputed);
        Assert.True(col.IsNullable);
    }

    // ── Column-level PRIMARY KEY flag: both tokens required, not "PRIMARY" alone ──

    [Fact]
    public void ColumnLevelPrimary_WithoutAFollowingKeyToken_DoesNotSetIsPrimaryKey()
    {
        // ColumnLevelPrimaryKey_RequiresBothTokens_NotKeyAlone (existing)
        // contains neither "primary" nor "key" at all, so it can't
        // distinguish the real "&&" from a widened "||" -- this needs
        // "primary" actually present with nothing valid following it.
        var statements = MigrationParser.Parse("create table t (id int not null primary, name varchar(10))");

        var stmt = Assert.Single(statements);
        var col = stmt.Columns.Single(c => c.Name == "id");
        Assert.False(col.IsPrimaryKey);
    }

    // ── Table-level PRIMARY KEY (...) column list: must stop at its own closing paren ──

    [Fact]
    public void TableLevelPrimaryKeyParenList_StopsAtClosingParen_DoesNotConsumeTrailingIdentifier()
    {
        // If the closing-")" check inside ReadParenNameList's scan loop
        // never matched (e.g. requiring the token NOT be a Symbol, which a
        // real ")" token never satisfies), the loop would run past the
        // paren list's own closing paren and pick up any identifier tokens
        // that happen to follow within the same clause -- wrongly treating
        // them as additional primary-key column names.
        var statements = MigrationParser.Parse(
            "create table t (a int, extra_ident int, primary key (a) extra_ident)");

        var stmt = Assert.Single(statements);
        var extra = stmt.Columns.Single(c => c.Name == "extra_ident");
        Assert.False(extra.IsPrimaryKey);
    }

    // ── Computed-column-shorthand (AS shorthand): SkipParenGroup must skip the expression atomically ──

    [Fact]
    public void ComputedColumnShorthand_ExpressionContainsNotNullTokensInternally_DoesNotLeakIntoNullabilityFlag()
    {
        // If SkipParenGroup's own call were removed (or SkipParenGroup itself
        // became a no-op), the "AS (...)" expression would be consumed one
        // token at a time by this loop's own PERSISTED/NOT+NULL/NULL checks
        // instead of atomically -- and a "not null" appearing INSIDE the
        // expression (not as a trailing flag) would wrongly flip IsNullable
        // to false, even though no trailing flag was given at all.
        var statements = MigrationParser.Parse(
            "create table t (total as (case when x is not null then 1 else 0 end))");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsComputed);
        Assert.True(col.IsNullable);
    }

    // ── Flags loop DEFAULT branch: the parenthesized expression must be skipped atomically ──

    [Fact]
    public void DefaultExpression_ParenthesizedExpressionContainsNotNullTokensInternally_DoesNotLeakIntoNullabilityFlag()
    {
        // If the "DEFAULT" keyword check were disabled, the default's own
        // parenthesized expression would no longer be recognized and skipped
        // as one atomic unit -- it would instead be walked token-by-token by
        // this same loop's own flag checks, and a "not null" appearing
        // INSIDE the expression would wrongly flip IsNullable to false with
        // no trailing flag actually present.
        var statements = MigrationParser.Parse(
            "create table t (x int default (case when y is not null then 1 else 0 end))");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsNullable);
    }

    [Fact]
    public void DefaultExpression_SingleTokenNullValueAfterExplicitNotNull_DoesNotFlipNullabilityBack()
    {
        // Mirrors the parenthesized-expression test above, but for the
        // single-token (non-paren) DEFAULT value branch: if the trailing
        // "pos < def.Count" guard that skips DEFAULT's value token were
        // inverted, the guard's body would never run whenever a real value
        // token follows DEFAULT, leaving "NULL" unconsumed -- it would then
        // leak back into this same loop's own flag checks and wrongly flip
        // IsNullable back to true even though "NOT NULL" already appeared.
        var statements = MigrationParser.Parse("create table t (a int not null default null)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.False(col.IsNullable);
    }

    [Fact]
    public void GeneratedAsComputedColumn_WithoutAlwaysKeyword_StillMarkedComputed()
    {
        // If the leading "GENERATED" check were negated, the block would
        // never fire on the real "GENERATED" token -- but the generic
        // unknown-flag fallback then advances pos by exactly one, so the
        // very next loop iteration re-enters the same (now inverted, so
        // true-when-not-"GENERATED") block one token later than intended.
        // With the optional "ALWAYS"/"BY DEFAULT" prefix present, that
        // one-token misalignment happens to self-correct (the block's own
        // forward search for "AS" still lands in the right place one
        // iteration later) -- which is why every other GENERATED test in
        // this suite doesn't distinguish this mutant. Omitting "ALWAYS"
        // breaks that accidental resynchronization: the misaligned block
        // consumes the real "AS" token itself as if it were the flag
        // keyword, so its own "AS" search then looks one token too late
        // (at "(") and never finds it -- IsComputed silently stays false.
        var statements = MigrationParser.Parse("create table t (total int generated as (x))");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsComputed);
    }

    // ── ALTER COLUMN ... ADD/DROP GENERATED|IDENTITY: unmodeled, same as SET ──

    [Fact]
    public void AlterColumn_AddGenerated_IsUnsupported_SameAsSetOrDropGenerated()
    {
        var statements = MigrationParser.Parse("alter table t alter column c add generated always as identity");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    [Fact]
    public void AlterColumn_DropIdentity_IsUnsupported_SameAsAddOrSetGenerated()
    {
        var statements = MigrationParser.Parse("alter table t alter column c drop identity");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── Flags loop: NOT+NULL branch must "continue", not fall through ──

    [Fact]
    public void ColumnFlag_RedundantNotNullRepeatedTwice_StaysNonNullable()
    {
        // Same fall-through hazard as the computed-column shorthand's own
        // NOT+NULL branch (see ComputedColumn_RedundantNotNullRepeatedTwice_
        // StaysNonNullable above): if this branch's "continue" were dropped,
        // matching the first "NOT NULL" pair would still advance pos by 2
        // and set IsNullable=false, but then fall straight into this same
        // iteration's bare-NULL check instead of restarting the loop. That
        // check only tests a single token, so it can't recognize the second
        // "NOT" as the start of another NOT+NULL pair -- it falls through to
        // PRIMARY KEY/IDENTITY/etc. (all false), then the generic unknown-
        // flag skip, leaving pos on the second pair's trailing "NULL" token,
        // which the bare-NULL check on the *next* iteration then matches on
        // its own, wrongly flipping IsNullable back to true even though
        // "NOT NULL" was stated twice.
        var statements = MigrationParser.Parse("create table t (a int not null not null)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.False(col.IsNullable);
    }

    // ── Flags loop: bare NULL branch must "continue", not fall through ──

    [Fact]
    public void ColumnFlag_BareNullFollowedByNotNull_NotNullTakesEffect()
    {
        // Same fall-through hazard, mirrored: if the bare-NULL branch's own
        // "continue" were dropped, matching "NULL" would still advance pos
        // by 1 and set IsNullable=true, but then fall straight into this
        // same iteration's PRIMARY KEY/IDENTITY/UNSIGNED/DEFAULT/GENERATED
        // checks (all false here) and the generic unknown-flag skip -- which
        // consumes the following "NOT" as an unrecognized token instead of
        // recognizing it as the start of a NOT+NULL pair (that compound
        // check sits *earlier* in the if-chain, before the bare-NULL branch,
        // so the fall-through never revisits it). The trailing "NULL" is
        // then caught by the bare-NULL check on the *next* iteration,
        // leaving IsNullable=true even though "NOT NULL" was stated right
        // after "NULL" and should win.
        var statements = MigrationParser.Parse("create table t (a int null not null)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.False(col.IsNullable);
    }

    // ── Flags loop: DEFAULT branch's parenthesized-expression skip must stop at the matching close paren ──

    [Fact]
    public void ColumnFlag_ParenthesizedDefaultExpression_TrailingNotNullStillRecognized()
    {
        // The DEFAULT branch's paren-depth scan only breaks out of its
        // token-skipping loop when the running depth returns to zero on a
        // ")" -- i.e. the ")" that matches the expression's own opening "(".
        // If that check were flipped to fire on any *nonzero* depth instead,
        // it would never break at the single balanced pair in "(5)" (depth
        // goes 1 -> 0, which no longer satisfies "!= 0"), so the scan runs
        // past the closing paren with nothing to stop it, silently
        // swallowing the trailing "not null" flag as part of the "skipped
        // default expression" instead of parsing it.
        var statements = MigrationParser.Parse("create table t (a int default (5) not null)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.False(col.IsNullable);
    }

    // ── Flags loop: bare NULL after PRIMARY KEY must flip nullability back to true ──

    [Fact]
    public void ColumnLevelPrimaryKey_FollowedByExplicitNull_FlipsNullabilityBackToTrue()
    {
        var statements = MigrationParser.Parse("create table t (id int primary key null)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsPrimaryKey);
        Assert.True(col.IsNullable);
    }

    // ── Flags loop: bare AUTOINCREMENT/SERIAL keyword flags (not the SERIAL sugar DbType) ──

    [Fact]
    public void ColumnFlag_BareAutoincrementKeyword_SetsIsIdentity()
    {
        var statements = MigrationParser.Parse("create table t (id integer autoincrement)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
    }

    [Fact]
    public void ColumnFlag_BareSerialKeyword_OnNonSerialDbType_SetsIsIdentity()
    {
        var statements = MigrationParser.Parse("create table t (id int serial)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
    }

    // ── IDENTITY(seed,increment): a properly terminated paren must not swallow what follows ──

    [Fact]
    public void IdentityParen_ProperlyTerminated_DoesNotSwallowTrailingNotNull()
    {
        // Complements IdentityParen_MissingClosingParen_GreedilyConsumesRestOfDefinition_IncludingNotNull:
        // that test documents the unterminated case; this one proves the
        // seed/increment skip loop's own closing-paren detection actually
        // stops there when a real ")" is present, instead of always running
        // to end of input regardless.
        //
        // Traced by hand (not just re-read): with a real ")" present, this
        // only kills the loop's `&&`->`||` mutation (an infinite loop /
        // Timeout). The `<`->`>` and `!IsSymbol`->`IsSymbol` mutants on the
        // same line are already killed by the unterminated-paren test above,
        // not by this one, and `<`->`<=` is genuinely equivalent in both
        // cases: IsSymbol self-bounds-checks its index, so the one extra
        // iteration `<=` allows never observably changes where `pos` ends up
        // relative to `def.Count` once the outer flags loop re-checks its own
        // `pos < def.Count` condition. This test's real, distinct job is the
        // Timeout mutant plus the "does it stop at a real )" regression it's
        // named for -- not a `<=` boundary kill.
        var statements = MigrationParser.Parse("alter table t add col int identity(1,1) not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
        Assert.False(col.IsNullable);
    }

    // ── ReadObjectName: tokenizer-split bracket-quoted dotted name ──

    [Fact]
    public void CreateTable_BracketQuotedSchemaAndTableName_TokenizerMergesToOneIdentifier()
    {
        // Correction, 2026-09-20 (whole-project re-run follow-up): this was
        // previously believed to exercise ReadObjectName's while-loop
        // (lines 815-818), but SqlTokenizer.MergeQualifiedIdentifiers (see
        // SqlTokenizer.cs) unconditionally fuses adjacent
        // Identifier '.' Identifier tokens -- including bracket-quoted ones
        // like [dbo].[Gadgets] -- into a single Identifier token BEFORE
        // ReadObjectName ever runs. So this input reaches ReadObjectName's
        // single-token branch (BareName's own LastIndexOf('.')), not the
        // while-loop; it is kept as a regression test for that merge
        // behavior, not as coverage for the while-loop.
        var statements = MigrationParser.Parse("create table [dbo].[Gadgets] (id int primary key)");

        var stmt = Assert.Single(statements);
        Assert.Equal("Gadgets", stmt.TableName);
    }

    [Fact]
    public void CreateTable_BracketQuotedNameContainingLiteralDot_TokenizerLeavesUnmergedForReadObjectNamesLoop()
    {
        // MergeQualifiedIdentifiers deliberately leaves a Identifier '.'
        // Identifier sequence unmerged when the left identifier's own value
        // already contains a literal dot and this isn't a chain
        // continuation -- exactly the case a bracket-quoted segment with a
        // period inside it produces (e.g. a schema pathologically named
        // "db.with.dots"). That is the one input shape that actually
        // reaches ReadObjectName's while-loop (lines 815-818): pos advances
        // past the un-merged "." and second Identifier, and the final
        // segment wins.
        var statements = MigrationParser.Parse("create table [db.with.dots].[Gadgets] (id int primary key)");

        var stmt = Assert.Single(statements);
        Assert.Equal("Gadgets", stmt.TableName);
    }

    // ── ReadObjectName: the segment after "." must itself be an Identifier ──

    [Fact]
    public void CreateTable_DottedNameSegmentFollowedByNonIdentifierToken_DoesNotMergeAndIsUnsupported()
    {
        // Correction, 2026-09-20 (re-audit): a prior pass here claimed the
        // while-loop's `tokens[pos + 1].Type == TokenType.Identifier` check
        // was equivalent to `tokens[pos - 1]...` on the theory that
        // tokens[pos - 1] (the segment just consumed) is always an
        // Identifier at this point, so the check is "always true either
        // way." That's true only when tokens[pos + 1] *also* happens to be
        // an Identifier -- but the whole point of the real check is to
        // reject the case where it ISN'T, and tokens[pos - 1] can't see
        // that at all. SqlTokenizer.MergeQualifiedIdentifiers only fuses
        // Identifier '.' Identifier; "[dbo].5" leaves the '.' and the
        // Number '5' as separate tokens. With the correct check the loop
        // refuses to merge (tokens[pos + 1] is a Number, not an
        // Identifier), ReadObjectName returns just "dbo", pos is left
        // sitting on the unconsumed '.', and the caller's `!IsSymbol(pos,
        // "(")` guard correctly falls back to Unsupported. With the
        // mutated `tokens[pos - 1]` check (always true), the loop wrongly
        // merges anyway, name becomes the Number's own text ("5"), pos
        // skips past it to the real "(", and the statement is wrongly
        // accepted as CreateTable with TableName "5".
        var statements = MigrationParser.Parse("create table [dbo].5 (a int)");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    [Fact]
    public void CreateTable_TrailingDotWithNoFollowingIdentifier_DoesNotOverrunTheTokenArray()
    {
        // Guards the while-loop's `pos + 1 < tokens.Count` bound: if that
        // check were loosened (e.g. an off-by-one to `pos - 1 < tokens.Count`,
        // which is true almost everywhere), the unmutated inner check
        // `tokens[pos + 1].Type == TokenType.Identifier` would index one
        // past the end of the token list once the unmerged "." is the very
        // last token -- an IndexOutOfRangeException instead of the correct
        // "no more segments, stop" fallthrough. Needs a literal-dot name
        // (see the sibling test above) so the tokenizer's merge pass leaves
        // the trailing "." unconsumed, and no "(" or anything else after it
        // so the token list truly ends there.
        var statements = MigrationParser.Parse("create table [db.with.dots].");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── SplitTopLevel: comma-detection must not fire on every top-level symbol ──

    [Fact]
    public void CreateTable_NegativeNumericDefaultFollowedByNotNull_DoesNotSpuriouslySplitOnTheMinusSign()
    {
        // The unary "-" before a negative DEFAULT literal tokenizes as its
        // own standalone Symbol token at depth 0 (same depth as the real
        // comma between column defs). SplitTopLevel's comma check must key
        // off Value == "," specifically -- if it instead treated any
        // top-level Symbol as a separator, "a int default -1 not null"
        // would fracture at "-": column "a" loses everything from "-1"
        // onward (including the trailing NOT NULL), and the orphaned
        // "1 not null" fragment starts with a Number token, so
        // ParseColumnDef's def[0].Type != Identifier guard silently drops
        // it instead of surfacing the lost NOT NULL anywhere.
        var statements = MigrationParser.Parse("create table t (a int default -1 not null, b int)");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.CreateTable, stmt.Kind);
        Assert.Equal(2, stmt.Columns.Count);
        Assert.Equal("a", stmt.Columns[0].Name);
        Assert.False(stmt.Columns[0].IsNullable);
        Assert.Equal("b", stmt.Columns[1].Name);
    }
}
