using System.Linq;
using Extrode.JauntyQ.Analysis.Migrations;
using Xunit;

namespace Extrode.JauntyQ.Analysis.Tests;

/// <summary>
/// Direct coverage for MigrationParser gaps not exercised by
/// MigrationParserTests: the ALTER COLUMN SET/DROP and identity-toggle
/// guard chains under operator-precedence-changing mutations, the ADD
/// CONSTRAINT-keyword string literals, WITH TIME ZONE's exact match vs. a
/// same-first-word false positive, MySQL UNSIGNED without ZEROFILL still
/// reaching the NULL flag, GENERATED BY (missing DEFAULT) AS IDENTITY,
/// the default-nullable initializer, GroupAlterActions' malformed-first-
/// clause guard, and ReadObjectName's multi-level dotted-name loop.
/// </summary>
[Trait("Category", "AuditRegression")]
public class MigrationParserMutationCoverageTests
{
    // ── ALTER COLUMN SET/DROP guard: isAlterColumn term must gate the whole chain ──

    [Fact]
    public void ModifyForm_SetNotNullShapedBody_DoesNotMisfireTheAlterColumnOnlySetDropGuard()
    {
        // MODIFY never supports the SET/DROP NOT NULL forms (Postgres-only,
        // ALTER COLUMN-only) -- isAlterColumn=false must gate the whole
        // chain regardless of what the rest of the body looks like. "set"
        // tokenizes as a Keyword, so falling through to ParseColumnDef
        // correctly yields Unsupported too -- both paths must agree.
        var statements = MigrationParser.Parse("alter table products modify product_name set not null");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    [Fact]
    public void ModifyForm_AddGeneratedShapedBody_FallsThroughToOrdinaryColumnDef_NotUnsupported()
    {
        // Same isAlterColumn gate on the identity-toggle chain: MODIFY
        // + "add generated" must NOT be recognized as the toggle form.
        // "add"/"generated" both tokenize as plain Identifiers, so the
        // fallthrough misparses this as an ordinary column named "product_name"
        // whose type-clause loop consumes "add" as DbType and "generated" as
        // an unrecognized flag -- still a real (if nonsensical) AlterColumn,
        // not Unsupported.
        var statements = MigrationParser.Parse("alter table products modify product_name add generated");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.AlterColumn, stmt.Kind);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("add", col.DbType);
    }

    [Fact]
    public void AlterColumn_NothingAfterTheColumnKeyword_IsUnsupported_NoIndexOutOfRange()
    {
        // p == body.Count exactly after consuming "COLUMN": both the
        // SET/DROP and identity-toggle guards must short-circuit on
        // "p < body.Count" before ever indexing body[p], or this throws
        // instead of returning a diagnostic.
        var statements = MigrationParser.Parse("alter table products alter column");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    [Fact]
    public void AlterColumnDefault_SetDefaultNull_IsIgnored_NotMisreadAsNullabilityChange()
    {
        // "SET DEFAULT NULL": the NOT-NULL branch's own two-token check
        // (Is(p+2,"NOT") && Is(p+3,"NULL")) must require NOT literally
        // present, not treat the unrelated trailing "NULL" of "DEFAULT NULL"
        // as satisfying it.
        var statements = MigrationParser.Parse("alter table products alter column product_name set default null");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Ignored, stmt.Kind);
    }

    // ── ADD CONSTRAINT-keyword recognition: each keyword's own string literal ──

    [Theory]
    [InlineData("alter table products add unique int")]
    [InlineData("alter table products add foreign int")]
    [InlineData("alter table products add check int")]
    public void AddConstraintKeyword_FollowedByAValidTypeToken_StillReportsUnsupported_NotMisparsedAsAColumn(string sql)
    {
        // Each of UNIQUE/FOREIGN/CHECK routes ADD into the constraint
        // branch, which always returns Unsupported for anything but a
        // recognized "PRIMARY KEY (...)" shape. If the literal keyword
        // check for one of these three is lost, "add <keyword> int" falls
        // through and misparses as an ordinary column definition named
        // after the keyword instead.
        var statements = MigrationParser.Parse(sql);

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── WITH TIME ZONE: all three words must match, not just the first two/first ──

    [Theory]
    [InlineData("alter table t add col time with time foo not null")] // WITH+TIME true, ZONE false
    [InlineData("alter table t add col time with foo zone not null")] // WITH true, TIME false, ZONE true
    public void TimeColumn_PartialWithTimeZoneMatch_DbTypeStaysBare_NotWronglyExtended(string sql)
    {
        var statements = MigrationParser.Parse(sql);

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("time", col.DbType);
        Assert.False(col.IsNullable);
    }

    // ── MySQL UNSIGNED without ZEROFILL: NOT NULL flag must still be reached ──

    [Fact]
    public void MySqlUnsigned_NoZerofill_TrailingNotNullFlagStillRecognized()
    {
        var statements = MigrationParser.Parse("alter table t add col smallint unsigned not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("smallint unsigned", col.DbType);
        Assert.False(col.IsNullable);
    }

    // ── GENERATED BY (malformed, missing DEFAULT) AS IDENTITY ──

    [Fact]
    public void GeneratedByWithoutDefault_FallsThroughToTheStandaloneIdentityFlag()
    {
        // "BY" alone (no "DEFAULT" following) must not be consumed as the
        // "BY DEFAULT" unit -- it's skipped as an unrecognized flag token,
        // and the very next "IDENTITY" token is then read by the
        // standalone IDENTITY/AUTO_INCREMENT/SERIAL flag check instead.
        var statements = MigrationParser.Parse("alter table t add col int generated by identity");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
    }

    // ── Default-nullable initializer: no explicit flag at all ──

    [Fact]
    public void ColumnWithNoNullabilityFlagAtAll_DefaultsToNullable()
    {
        var statements = MigrationParser.Parse("alter table t add col nvarchar(max)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsNullable);
    }

    // ── Computed column shorthand guard: both Keyword-type AND value=="AS" required ──

    [Fact]
    public void ColumnStartingWithAKeywordThatIsNotAs_FollowedByParens_IsNotMistakenForComputedShorthand()
    {
        // "case" tokenizes as a Keyword (satisfying the Type check alone),
        // but isn't "AS" -- both conditions must hold, or a column literally
        // named after some other keyword and followed by any parenthesized
        // token would be wrongly treated as a computed-column expression.
        var statements = MigrationParser.Parse("alter table t add total case (1)");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── IDENTITY(seed,increment): unterminated paren greedily consumes to EOF ──

    [Fact]
    public void IdentityParen_MissingClosingParen_GreedilyConsumesRestOfDefinition_IncludingNotNull()
    {
        // Documents the current (if surprising) behavior: with no closing
        // ")" anywhere in the remaining tokens, the seed/increment skip loop
        // runs to the end of the definition looking for one that never
        // comes, silently swallowing a trailing "NOT NULL" along with it.
        var statements = MigrationParser.Parse("alter table t add col int identity(1,1 not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
        Assert.True(col.IsNullable);
    }

    // ── SplitTopLevel / ReadParenNameList: unterminated paren, no crash ──

    [Fact]
    public void CreateTable_UnterminatedColumnList_StopsAtEndOfTokens_NoIndexOutOfRange()
    {
        // No closing ")" anywhere -- SplitTopLevel's own loop bound must
        // stop at tokens.Count, not run one iteration past the end trying
        // to index a token that doesn't exist.
        var statements = MigrationParser.Parse("create table t (id int");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.CreateTable, stmt.Kind);
        Assert.Equal("id", Assert.Single(stmt.Columns).Name);
    }

    [Fact]
    public void AddPrimaryKey_UnterminatedColumnList_StopsAtEndOfTokens_NoIndexOutOfRange()
    {
        // Same bound, in ReadParenNameList's own for-loop: an ADD
        // CONSTRAINT ... PRIMARY KEY (a, b with no closing paren must not
        // walk past the end of the token list.
        var statements = MigrationParser.Parse("alter table products add constraint pk_products primary key (product_id");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.AddPrimaryKey, stmt.Kind);
        Assert.Equal("product_id", Assert.Single(stmt.ColumnNames));
    }

    // ── GroupAlterActions: malformed first clause ──

    [Fact]
    public void AlterTable_FirstClauseHasNoRecognizedActionVerb_IsUnsupported()
    {
        var statements = MigrationParser.Parse("alter table products rename column a to b");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── ReadObjectName: multi-level dotted names ──

    [Fact]
    public void CreateTable_ThreeLevelSchemaQualifiedName_KeepsOnlyTheFinalSegment()
    {
        var statements = MigrationParser.Parse("create table db.dbo.gadgets (id int primary key)");

        var stmt = Assert.Single(statements);
        Assert.Equal("gadgets", stmt.TableName);
    }

    // ── ParseCreateTable: an empty def between two commas is skipped, not counted ──

    [Fact]
    public void CreateTable_DoubleCommaBetweenColumns_ProducesEmptyDef_SilentlySkipped()
    {
        var statements = MigrationParser.Parse("create table t (id int primary key,, name varchar(20))");

        var stmt = Assert.Single(statements);
        Assert.Equal(2, stmt.Columns.Count);
        Assert.Equal("id", stmt.Columns[0].Name);
        Assert.Equal("name", stmt.Columns[1].Name);
    }

    // ── ParseCreateTable: zero parsed columns falls back to Unsupported ──

    [Fact]
    public void CreateTable_EmptyColumnList_IsUnsupported_NotAZeroColumnTable()
    {
        var statements = MigrationParser.Parse("create table t ()");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── ALTER COLUMN ... SET GENERATED/IDENTITY: unmodeled, same as ADD/DROP ──

    [Fact]
    public void AlterColumn_SetGenerated_IsUnsupported_SameAsAddOrDropGenerated()
    {
        var statements = MigrationParser.Parse("alter table t alter column c set generated always as identity");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── SkipParenGroup: guard must not consume tokens when not positioned on "(" ──

    [Fact]
    public void GeneratedAlwaysAsIdentity_WithNoSeedParen_DoesNotConsumeTheFollowingNotNull()
    {
        // If SkipParenGroup's own "am I even at a '('?" guard were bypassed,
        // its scan loop would run from "not" onward with nothing to match,
        // silently swallowing "not null" one token at a time and leaving
        // IsNullable at its default (true) instead of being set false.
        var statements = MigrationParser.Parse("alter table t add id int generated always as identity not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
        Assert.False(col.IsNullable);
    }

    // ── SkipParenGroup / DEFAULT-expression paren skip: nested-paren depth must be tracked ──

    [Fact]
    public void ComputedColumn_GeneratedAsExpressionWithNestedFunctionCall_StoredThenNotNullStillParsed()
    {
        // round(price, 2) nests a second "(" / ")" pair inside the outer
        // GENERATED ... AS (...) group. If SkipParenGroup's depth counter
        // isn't correctly incremented/decremented/compared per paren, the
        // scan either stops at the wrong (inner) ")" or never terminates --
        // either way "stored" and the trailing "not null" would land in the
        // wrong place, or get swallowed, and IsNullable would stay at its
        // default (true) instead of being set false.
        var statements = MigrationParser.Parse(
            "alter table t add total decimal generated always as (round(price, 2)) stored not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsComputed);
        Assert.False(col.IsNullable);
    }

    [Fact]
    public void DefaultExpression_WithNestedFunctionCall_DepthTracksCorrectly_NotNullStillParsed()
    {
        // Same nested-paren depth-tracking requirement as SkipParenGroup,
        // but in the inline DEFAULT-expression skip loop: if depth is
        // mistracked, the trailing "not null" gets absorbed into the
        // runaway "skip the default expression" scan instead of being seen
        // by the flags loop, leaving IsNullable at its default (true).
        var statements = MigrationParser.Parse(
            "alter table t add col decimal default (round(price, 2)) not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.False(col.IsNullable);
    }

    // ── Facet paren: unterminated "(" at end of definition doesn't overrun ──

    [Fact]
    public void FacetParen_UnterminatedWithNoDigits_DoesNotThrow_NoCrash()
    {
        var statements = MigrationParser.Parse("alter table t add price decimal(");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("decimal", col.DbType);
    }

    [Fact]
    public void FacetParen_UnterminatedAfterCommaWithNoSecondDigit_DoesNotThrow_NoCrash()
    {
        var statements = MigrationParser.Parse("alter table t add price decimal(10,");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal("decimal", col.DbType);
        Assert.Equal(10, col.Precision);
    }

    // ── ApplyFacets: isDecimal's other three literals, not just "decimal" ──

    [Theory]
    [InlineData("numeric")]
    [InlineData("money")]
    [InlineData("smallmoney")]
    public void ApplyFacets_EachDecimalLikeDbType_GetsPrecisionAndScaleFromFacets(string dbType)
    {
        var statements = MigrationParser.Parse($"alter table t add amount {dbType}(8,3)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.Equal(8, col.Precision);
        Assert.Equal(3, col.Scale);
    }

    // ── ApplyFacets: IsUnicode is false for a non-"n"-prefixed text type ──

    [Fact]
    public void ApplyFacets_PlainVarchar_IsUnicodeIsFalse_NotJustUnset()
    {
        var statements = MigrationParser.Parse("alter table t add name varchar(50)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.False(col.IsUnicode);
    }

    // ── GroupAlterActions: a malformed first clause must void the WHOLE
    // statement, not just get silently dropped while later well-formed
    // clauses still parse ──

    [Fact]
    public void AlterTable_MalformedFirstClauseFollowedByWellFormedClause_IsUnsupported_NotPartiallyParsed()
    {
        // A single malformed clause with nothing after it already returns
        // Unsupported via the empty-groups-list fallback regardless of
        // whether GroupAlterActions' own "return null" fires -- both paths
        // converge on Count==0. Only a well-formed clause AFTER the
        // malformed one can distinguish them: if the early return is
        // skipped, "add c int" would still be recognized as its own group
        // and the statement would wrongly come back parsed instead of
        // Unsupported.
        var statements = MigrationParser.Parse("alter table t rename column a to b, add c int");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── Computed-column inline flags loop: NOT+NULL pair must both be present ──

    [Fact]
    public void ComputedColumn_JunkTokenImmediatelyBeforeNull_DoesNotFalselyMarkNonNullable()
    {
        // A widened (OR'd) "Is(NOT) || Is(cp+1, NULL)" check would fire on
        // ANY token immediately preceding a bare "NULL", not just "NOT" --
        // wrongly flipping IsNullable to false instead of leaving the
        // generic-skip loop to reach "NULL" on its own next iteration (which
        // correctly sets IsNullable true).
        var statements = MigrationParser.Parse("create table t (total as (a + b) collate null)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsNullable);
    }

    // ── Computed-column inline flags loop: bare NULL check must require an exact match ──

    [Fact]
    public void ComputedColumn_JunkTokenAfterAnExplicitNotNull_DoesNotFlipNullabilityBack()
    {
        // A negated "!(Is(cp, NULL))" bare-NULL check would fire on every
        // token that ISN'T literally "NULL" -- including a trailing junk
        // token after an already-correct "NOT NULL", wrongly flipping
        // IsNullable back to true.
        var statements = MigrationParser.Parse("create table t (total as (a + b) not null collate)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.False(col.IsNullable);
    }

    // ── Column-level PRIMARY KEY flag: both tokens required, not "PRIMARY" alone ──

    [Fact]
    public void ColumnLevelPrimary_WithoutAFollowingKeyToken_DoesNotSetIsPrimaryKey()
    {
        // ColumnLevelPrimaryKey_RequiresBothTokens_NotKeyAlone (existing)
        // contains neither "primary" nor "key" at all, so it can't
        // distinguish the real "&&" from a widened "||" -- this needs
        // "primary" actually present with nothing valid following it.
        var statements = MigrationParser.Parse("create table t (id int not null primary, name varchar(10))");

        var stmt = Assert.Single(statements);
        var col = stmt.Columns.Single(c => c.Name == "id");
        Assert.False(col.IsPrimaryKey);
    }

    // ── Computed-column-shorthand (AS shorthand): SkipParenGroup must skip the expression atomically ──

    [Fact]
    public void ComputedColumnShorthand_ExpressionContainsNotNullTokensInternally_DoesNotLeakIntoNullabilityFlag()
    {
        // If SkipParenGroup's own call were removed (or SkipParenGroup itself
        // became a no-op), the "AS (...)" expression would be consumed one
        // token at a time by this loop's own PERSISTED/NOT+NULL/NULL checks
        // instead of atomically -- and a "not null" appearing INSIDE the
        // expression (not as a trailing flag) would wrongly flip IsNullable
        // to false, even though no trailing flag was given at all.
        var statements = MigrationParser.Parse(
            "create table t (total as (case when x is not null then 1 else 0 end))");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsComputed);
        Assert.True(col.IsNullable);
    }

    // ── Flags loop DEFAULT branch: the parenthesized expression must be skipped atomically ──

    [Fact]
    public void DefaultExpression_ParenthesizedExpressionContainsNotNullTokensInternally_DoesNotLeakIntoNullabilityFlag()
    {
        // If the "DEFAULT" keyword check were disabled, the default's own
        // parenthesized expression would no longer be recognized and skipped
        // as one atomic unit -- it would instead be walked token-by-token by
        // this same loop's own flag checks, and a "not null" appearing
        // INSIDE the expression would wrongly flip IsNullable to false with
        // no trailing flag actually present.
        var statements = MigrationParser.Parse(
            "create table t (x int default (case when y is not null then 1 else 0 end))");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsNullable);
    }

    // ── ALTER COLUMN ... ADD/DROP GENERATED|IDENTITY: unmodeled, same as SET ──

    [Fact]
    public void AlterColumn_AddGenerated_IsUnsupported_SameAsSetOrDropGenerated()
    {
        var statements = MigrationParser.Parse("alter table t alter column c add generated always as identity");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    [Fact]
    public void AlterColumn_DropIdentity_IsUnsupported_SameAsAddOrSetGenerated()
    {
        var statements = MigrationParser.Parse("alter table t alter column c drop identity");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.Unsupported, stmt.Kind);
    }

    // ── Flags loop: bare NULL after PRIMARY KEY must flip nullability back to true ──

    [Fact]
    public void ColumnLevelPrimaryKey_FollowedByExplicitNull_FlipsNullabilityBackToTrue()
    {
        var statements = MigrationParser.Parse("create table t (id int primary key null)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsPrimaryKey);
        Assert.True(col.IsNullable);
    }

    // ── Flags loop: bare AUTOINCREMENT/SERIAL keyword flags (not the SERIAL sugar DbType) ──

    [Fact]
    public void ColumnFlag_BareAutoincrementKeyword_SetsIsIdentity()
    {
        var statements = MigrationParser.Parse("create table t (id integer autoincrement)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
    }

    [Fact]
    public void ColumnFlag_BareSerialKeyword_OnNonSerialDbType_SetsIsIdentity()
    {
        var statements = MigrationParser.Parse("create table t (id int serial)");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
    }

    // ── IDENTITY(seed,increment): a properly terminated paren must not swallow what follows ──

    [Fact]
    public void IdentityParen_ProperlyTerminated_DoesNotSwallowTrailingNotNull()
    {
        // Complements IdentityParen_MissingClosingParen_GreedilyConsumesRestOfDefinition_IncludingNotNull:
        // that test documents the unterminated case; this one proves the
        // seed/increment skip loop's own closing-paren detection actually
        // stops there when a real ")" is present, instead of always running
        // to end of input regardless.
        var statements = MigrationParser.Parse("alter table t add col int identity(1,1) not null");

        var stmt = Assert.Single(statements);
        var col = Assert.Single(stmt.Columns);
        Assert.True(col.IsIdentity);
        Assert.False(col.IsNullable);
    }

    // ── ReadObjectName: tokenizer-split bracket-quoted dotted name ──

    [Fact]
    public void CreateTable_BracketQuotedSchemaAndTableName_TokenizerSplitDotJoinsToFinalSegment()
    {
        // "db.dbo.gadgets" (no brackets) tokenizes as a single compound
        // identifier, so BareName's own LastIndexOf('.') handles it alone --
        // ReadObjectName's while-loop is never reached. Bracket-quoted
        // segments tokenize as separate Identifier/Symbol('.')/Identifier
        // pieces (per the tokenizer-split comment on ReadObjectName), which
        // is what actually drives that loop.
        var statements = MigrationParser.Parse("create table [dbo].[Gadgets] (id int primary key)");

        var stmt = Assert.Single(statements);
        Assert.Equal("Gadgets", stmt.TableName);
    }

    // ── SplitTopLevel: comma-detection must not fire on every top-level symbol ──

    [Fact]
    public void CreateTable_NegativeNumericDefaultFollowedByNotNull_DoesNotSpuriouslySplitOnTheMinusSign()
    {
        // The unary "-" before a negative DEFAULT literal tokenizes as its
        // own standalone Symbol token at depth 0 (same depth as the real
        // comma between column defs). SplitTopLevel's comma check must key
        // off Value == "," specifically -- if it instead treated any
        // top-level Symbol as a separator, "a int default -1 not null"
        // would fracture at "-": column "a" loses everything from "-1"
        // onward (including the trailing NOT NULL), and the orphaned
        // "1 not null" fragment starts with a Number token, so
        // ParseColumnDef's def[0].Type != Identifier guard silently drops
        // it instead of surfacing the lost NOT NULL anywhere.
        var statements = MigrationParser.Parse("create table t (a int default -1 not null, b int)");

        var stmt = Assert.Single(statements);
        Assert.Equal(MigrationStatementKind.CreateTable, stmt.Kind);
        Assert.Equal(2, stmt.Columns.Count);
        Assert.Equal("a", stmt.Columns[0].Name);
        Assert.False(stmt.Columns[0].IsNullable);
        Assert.Equal("b", stmt.Columns[1].Name);
    }
}
